In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/cyrinemejrii/data-generation/c10_llm_requirement_rewrites.csv
/kaggle/input/datasets/cyrinemejrii/data-generation/c9_multimodal_requirement_quality_scores.csv
/kaggle/input/datasets/cyrinemejrii/data-generation/c9_section_quality_summary.csv
/kaggle/input/datasets/cyrinemejrii/data-generation/c11_final_document_report.csv
/kaggle/input/datasets/cyrinemejrii/data-generation/c11_final_requirement_report.csv

In [2]:
# =========================================================
# MODULE G0 — LOAD SRS GENERATION INPUTS
# =========================================================

from pathlib import Path
import os
import re
import json
import ast
import pandas as pd
import numpy as np

print("=" * 80)
print("MODULE G0 — LOAD SRS GENERATION INPUTS")
print("=" * 80)

def find_file(filename, search_roots=None):
    if search_roots is None:
        search_roots = [Path("/kaggle/input"), Path("/kaggle/working")]
    
    matches = []
    
    for root in search_roots:
        if root.exists():
            direct_matches = list(root.rglob(filename))
            matches.extend(direct_matches)
    
    matches = sorted(list(set(matches)))
    return matches[0] if len(matches) > 0 else None


generation_files = {
    "c9_quality": "c9_multimodal_requirement_quality_scores.csv",
    "c10_rewrites": "c10_llm_requirement_rewrites.csv",
    "c11_requirement_report": "c11_final_requirement_report.csv",
    "c11_document_report": "c11_final_document_report.csv",
    "c9_section_summary": "c9_section_quality_summary.csv"
}

found_paths = {}

for key, filename in generation_files.items():
    path = find_file(filename)
    found_paths[key] = path
    print(f"{key}: {filename}")
    print(" ->", path)
    print()

critical_files = [
    "c9_quality",
    "c10_rewrites",
    "c11_requirement_report"
]

for key in critical_files:
    if found_paths[key] is None:
        raise FileNotFoundError(
            f"Missing required file: {generation_files[key]}. "
            "Please add the data_generation dataset to this notebook."
        )

print("All critical generation files found.")

================================================================================
MODULE G0 — LOAD SRS GENERATION INPUTS
================================================================================
c9_quality: c9_multimodal_requirement_quality_scores.csv
 -> /kaggle/input/datasets/cyrinemejrii/data-generation/c9_multimodal_requirement_quality_scores.csv

c10_rewrites: c10_llm_requirement_rewrites.csv
 -> /kaggle/input/datasets/cyrinemejrii/data-generation/c10_llm_requirement_rewrites.csv

c11_requirement_report: c11_final_requirement_report.csv
 -> /kaggle/input/datasets/cyrinemejrii/data-generation/c11_final_requirement_report.csv

c11_document_report: c11_final_document_report.csv
 -> /kaggle/input/datasets/cyrinemejrii/data-generation/c11_final_document_report.csv

c9_section_summary: c9_section_quality_summary.csv
 -> /kaggle/input/datasets/cyrinemejrii/data-generation/c9_section_quality_summary.csv

All critical generation files found.

In [3]:
# =========================================================
# MODULE G1 — READ GENERATION DATASETS
# =========================================================

print("=" * 80)
print("MODULE G1 — READ GENERATION DATASETS")
print("=" * 80)

df_c9_quality = pd.read_csv(found_paths["c9_quality"])
df_c10_rewrites = pd.read_csv(found_paths["c10_rewrites"])
df_c11_requirements = pd.read_csv(found_paths["c11_requirement_report"])

if found_paths["c11_document_report"] is not None:
    df_c11_documents = pd.read_csv(found_paths["c11_document_report"])
else:
    df_c11_documents = pd.DataFrame()

if found_paths["c9_section_summary"] is not None:
    df_c9_sections = pd.read_csv(found_paths["c9_section_summary"])
else:
    df_c9_sections = pd.DataFrame()

print("C9 quality shape:", df_c9_quality.shape)
print("C10 rewrites shape:", df_c10_rewrites.shape)
print("C11 requirements shape:", df_c11_requirements.shape)
print("C11 documents shape:", df_c11_documents.shape)
print("C9 sections shape:", df_c9_sections.shape)

print("\nC9 quality columns:")
print(df_c9_quality.columns.tolist())

print("\nC10 rewrite columns:")
print(df_c10_rewrites.columns.tolist())

display(df_c9_quality.head(5))
display(df_c10_rewrites.head(5))
display(df_c11_requirements.head(5))

================================================================================
MODULE G1 — READ GENERATION DATASETS
================================================================================
C9 quality shape: (3608, 91)
C10 rewrites shape: (100, 29)
C11 requirements shape: (3608, 104)
C11 documents shape: (24, 46)
C9 sections shape: (58, 23)

C9 quality columns:
['doc_id', 'page_num', 'page_type', 'section_label', 'block_id', 'block_text', 'requirement_type_candidate', 'requirement_strength', 'requirement_confidence', 'deep_prediction', 'deep_confidence', 'deep_prediction_label', 'prediction_status', 'final_prediction', 'nfr_subtype_pred', 'nfr_subtype_confidence', 'nfr_subtype_model_name', 'ambiguity_pred_id', 'ambiguity_prediction', 'ambiguity_confidence', 'clear_probability', 'ambiguous_probability', 'ambiguity_model_name', 'ambiguity_status', 'final_ambiguity_label', 'true_page_type', 'vision_page_type', 'vision_confidence', 'vision_quality_flag', 'vision_prob_appendix_page', 'vision_prob_content_page', 'vision_prob_cover_page', 'vision_prob_low_text_page', 'vision_prob_toc_page', 'avg_vision_confidence', 'document_vision_quality_flag', 'low_confidence_pages', 'vision_accuracy_proxy', 'quality_word_count', 'has_mandatory_modal', 'has_soft_modal', 'has_numeric_constraint', 'has_threshold_language', 'has_vague_terms', 'has_actor_or_system', 'is_fr', 'is_nfr', 'is_prediction_uncertain', 'is_deep_low_confidence', 'is_ambiguous', 'is_ambiguity_uncertain', 'ambiguous_probability_signal', 'ambiguity_confidence_signal', 'is_nfr_subtype_low_confidence', 'missing_section_context', 'low_requirement_confidence', 'vision_page_mismatch', 'low_vision_confidence', 'medium_vision_confidence', 'high_vision_confidence', 'vision_says_non_content_page', 'true_page_is_content_or_appendix', 'weak_document_visual_structure', 'moderate_document_visual_structure', 'strong_document_visual_structure', 'avg_vision_confidence_signal', 'vision_confidence_signal', 'silver_quality_score', 'silver_quality_label', 'quality_label_id', 'deep_quality_pred_id', 'deep_quality_label', 'deep_quality_confidence', 'low_quality_probability', 'medium_quality_probability', 'high_quality_probability', 'quality_model_name', 'clarity_score', 'testability_score', 'measurability_score', 'classification_reliability_score', 'ambiguity_safety_score', 'visual_context_score', 'completeness_score', 'deep_quality_numeric_score', 'requirement_quality_score', 'requirement_quality_level', 'quality_issues', 'quality_recommendations', 'num_quality_issues', 'section_label_clean']

C10 rewrite columns:
['doc_id', 'page_num', 'original_requirement', 'original_quality_score', 'original_quality_level', 'final_prediction', 'final_ambiguity_label', 'vision_page_type', 'vision_confidence', 'quality_issues', 'quality_recommendations', 'improved_requirement', 'rewrite_strategy', 'what_was_fixed', 'remaining_assumptions', 'raw_llm_response', 'rewrite_word_count', 'rewrite_has_requirement_keyword', 'rewrite_has_vague_term', 'rewrite_has_numeric_constraint', 'rewrite_has_placeholder', 'rewrite_clarity_score', 'rewrite_testability_score', 'rewrite_measurability_score', 'rewrite_completeness_score', 'rewrite_validation_score', 'rewrite_validation_label', 'quality_score_improvement_proxy', 'rewrite_improvement_flag']

,doc_id,page_num,page_type,section_label,block_id,block_text,requirement_type_candidate,requirement_strength,requirement_confidence,deep_prediction,...,ambiguity_safety_score,visual_context_score,completeness_score,deep_quality_numeric_score,requirement_quality_score,requirement_quality_level,quality_issues,quality_recommendations,num_quality_issues,section_label_clean
0,0000 cctns,4,content_page,functional_requirements,9,"following investigation, police shall take the...",FR,strong,1.0,0,...,98.57,53.68,100.0,89.42,94.59,EXCELLENT,['vision_page_type_mismatch'],['Review page type consistency between NLP lab...,1,functional_requirements
1,0000 cctns,6,content_page,non_functional_requirements,9,The solution should provide detailed context-s...,NFR,medium,0.9,1,...,21.88,70.08,88.0,29.45,50.01,WEAK,"['ambiguous_requirement', 'deep_model_low_qual...",['Rewrite the requirement to remove ambiguity ...,7,non_functional_requirements
2,0000 cctns,6,content_page,non_functional_requirements,12,The help should be accessible to the users bot...,NFR,medium,0.9,1,...,10.81,70.08,88.0,27.90,54.69,WEAK,"['ambiguous_requirement', 'deep_model_low_qual...",['Rewrite the requirement to remove ambiguity ...,6,non_functional_requirements
3,0000 cctns,6,content_page,non_functional_requirements,15,The solution should provide an interface for t...,NFR,medium,0.9,1,...,97.00,70.08,100.0,85.81,85.67,EXCELLENT,"['nfr_missing_numeric_target', 'nfr_missing_th...",['Add a measurable numeric target such as resp...,2,non_functional_requirements
4,0000 cctns,6,content_page,non_functional_requirements,18,"The solution should send alerts (e.g., email, ...",NFR,medium,0.9,0,...,96.42,70.08,100.0,88.79,95.68,EXCELLENT,[],['No major quality issue detected.'],0,non_functional_requirements

,doc_id,page_num,original_requirement,original_quality_score,original_quality_level,final_prediction,final_ambiguity_label,vision_page_type,vision_confidence,quality_issues,...,rewrite_has_numeric_constraint,rewrite_has_placeholder,rewrite_clarity_score,rewrite_testability_score,rewrite_measurability_score,rewrite_completeness_score,rewrite_validation_score,rewrite_validation_label,quality_score_improvement_proxy,rewrite_improvement_flag
0,0000 cctns,11,should be sufficient so as not to impede reada...,39.44,CRITICAL,UNCERTAIN,AMBIGUOUS,content_page,0.374997,"['ambiguous_requirement', 'deep_model_low_qual...",...,False,False,100,100,65,100,91.25,STRONG_REWRITE,51.81,MAJOR_IMPROVEMENT
1,2002 evla corr,14,messages should be able to easily filter the e...,42.36,WEAK,UNCERTAIN,AMBIGUOUS,content_page,0.973620,"['ambiguous_requirement', 'deep_model_low_qual...",...,False,False,100,100,65,100,91.25,STRONG_REWRITE,48.89,MAJOR_IMPROVEMENT
2,2001 beyond,19,• The authoring tool should support easy devel...,43.93,WEAK,UNCERTAIN,AMBIGUOUS,appendix_page,0.585477,"['ambiguous_requirement', 'deep_model_low_qual...",...,True,False,100,100,100,100,100.00,STRONG_REWRITE,56.07,MAJOR_IMPROVEMENT
3,2001 beyond,25,• The UI Editor itself should be a powerful an...,44.24,WEAK,UNCERTAIN,AMBIGUOUS,content_page,0.620956,"['ambiguous_requirement', 'deep_model_low_qual...",...,False,False,75,75,40,100,72.50,ACCEPTABLE_REWRITE,28.26,MAJOR_IMPROVEMENT
4,0000 cctns scanned,12,"Use of ""white space ""White space"" On page Le. ...",44.92,WEAK,UNCERTAIN,AMBIGUOUS,content_page,0.699740,"['ambiguous_requirement', 'deep_model_low_qual...",...,False,False,75,75,40,100,72.50,ACCEPTABLE_REWRITE,27.58,MAJOR_IMPROVEMENT

,doc_id,page_num,page_type,section_label,block_id,block_text,requirement_type_candidate,requirement_strength,requirement_confidence,deep_prediction,...,rewrite_strategy,what_was_fixed,remaining_assumptions,rewrite_validation_score,rewrite_validation_label,rewrite_improvement_flag,quality_score_improvement_proxy,has_llm_rewrite,final_action_priority,priority_rank
0,0000 cctns,4,content_page,functional_requirements,9,"following investigation, police shall take the...",FR,strong,1.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,ACCEPTABLE,7
1,0000 cctns,6,content_page,non_functional_requirements,9,The solution should provide detailed context-s...,NFR,medium,0.9,1,...,json_parse_failed,[],[],81.25,ACCEPTABLE_REWRITE,MAJOR_IMPROVEMENT,31.24,True,REWRITE_REQUIRED,1
2,0000 cctns,6,content_page,non_functional_requirements,12,The help should be accessible to the users bot...,NFR,medium,0.9,1,...,Removed vague terms like 'appropriate' and 'su...,"['ambiguous_requirement', 'deep_model_low_qual...",['Ensure that the help feature is designed wit...,91.25,STRONG_REWRITE,MAJOR_IMPROVEMENT,36.56,True,REWRITE_REQUIRED,1
3,0000 cctns,6,content_page,non_functional_requirements,15,The solution should provide an interface for t...,NFR,medium,0.9,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,ACCEPTABLE,7
4,0000 cctns,6,content_page,non_functional_requirements,18,"The solution should send alerts (e.g., email, ...",NFR,medium,0.9,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,ACCEPTABLE,7

In [4]:
# =========================================================
# MODULE G2 — BUILD SRS GENERATION KNOWLEDGE BASE
# =========================================================

print("=" * 80)
print("MODULE G2 — BUILD SRS GENERATION KNOWLEDGE BASE")
print("=" * 80)

def normalize_text(x):
    x = str(x)
    x = re.sub(r"\s+", " ", x)
    return x.strip()

def safe_col(df, col, default=None):
    if col in df.columns:
        return df[col]
    return default

kb_rows = []

# ---------------------------------------------------------
# 1. High-quality requirements from C9 / C11
# ---------------------------------------------------------

source_df = df_c11_requirements.copy()

if "block_text" not in source_df.columns:
    raise ValueError("c11_final_requirement_report must contain block_text.")

for _, row in source_df.iterrows():
    text = normalize_text(row.get("block_text", ""))
    
    if len(text.split()) < 4:
        continue
    
    quality_level = str(row.get("requirement_quality_level", "UNKNOWN"))
    quality_score = float(row.get("requirement_quality_score", 0))
    
    if quality_level in ["EXCELLENT", "GOOD"] or quality_score >= 70:
        kb_rows.append({
            "kb_type": "HIGH_QUALITY_REQUIREMENT",
            "source": "c11_final_requirement_report",
            "text": text,
            "section_label": row.get("section_label", "unknown_section"),
            "requirement_type": row.get("final_prediction", "UNKNOWN"),
            "quality_score": quality_score,
            "quality_level": quality_level,
            "metadata": {
                "doc_id": row.get("doc_id", ""),
                "page_num": row.get("page_num", ""),
                "ambiguity": row.get("final_ambiguity_label", ""),
                "vision_page_type": row.get("vision_page_type", "")
            }
        })

# ---------------------------------------------------------
# 2. Rewrite examples from C10
# ---------------------------------------------------------

for _, row in df_c10_rewrites.iterrows():
    original = normalize_text(row.get("original_requirement", ""))
    improved = normalize_text(row.get("improved_requirement", ""))
    
    if len(original.split()) < 4 or len(improved.split()) < 4:
        continue
    
    kb_rows.append({
        "kb_type": "REWRITE_EXAMPLE",
        "source": "c10_llm_requirement_rewrites",
        "text": f"Original: {original}\nImproved: {improved}",
        "section_label": "requirement_improvement",
        "requirement_type": row.get("final_prediction", "UNKNOWN"),
        "quality_score": row.get("rewrite_validation_score", 0),
        "quality_level": row.get("rewrite_validation_label", "UNKNOWN"),
        "metadata": {
            "doc_id": row.get("doc_id", ""),
            "page_num": row.get("page_num", ""),
            "issues": row.get("quality_issues", ""),
            "recommendations": row.get("quality_recommendations", "")
        }
    })

df_generation_kb = pd.DataFrame(kb_rows)

print("Generation KB shape:", df_generation_kb.shape)

print("\nKB type distribution:")
print(df_generation_kb["kb_type"].value_counts())

print("\nRequirement type distribution:")
print(df_generation_kb["requirement_type"].value_counts(dropna=False))

display(df_generation_kb.head(20))

================================================================================
MODULE G2 — BUILD SRS GENERATION KNOWLEDGE BASE
================================================================================
Generation KB shape: (3306, 8)

KB type distribution:
kb_type
HIGH_QUALITY_REQUIREMENT    3206
REWRITE_EXAMPLE              100
Name: count, dtype: int64

Requirement type distribution:
requirement_type
FR           2282
UNCERTAIN     623
NFR           401
Name: count, dtype: int64

,kb_type,source,text,section_label,requirement_type,quality_score,quality_level,metadata
0,HIGH_QUALITY_REQUIREMENT,c11_final_requirement_report,"following investigation, police shall take the...",functional_requirements,FR,94.59,EXCELLENT,"{'doc_id': '0000 cctns', 'page_num': 4, 'ambig..."
1,HIGH_QUALITY_REQUIREMENT,c11_final_requirement_report,The solution should provide an interface for t...,non_functional_requirements,NFR,85.67,EXCELLENT,"{'doc_id': '0000 cctns', 'page_num': 6, 'ambig..."
2,HIGH_QUALITY_REQUIREMENT,c11_final_requirement_report,"The solution should send alerts (e.g., email, ...",non_functional_requirements,FR,95.68,EXCELLENT,"{'doc_id': '0000 cctns', 'page_num': 6, 'ambig..."
3,HIGH_QUALITY_REQUIREMENT,c11_final_requirement_report,The solution should enable the user to track t...,non_functional_requirements,FR,89.12,EXCELLENT,"{'doc_id': '0000 cctns', 'page_num': 6, 'ambig..."
4,HIGH_QUALITY_REQUIREMENT,c11_final_requirement_report,The solution should enable the help-desk user ...,non_functional_requirements,FR,92.29,EXCELLENT,"{'doc_id': '0000 cctns', 'page_num': 6, 'ambig..."
5,HIGH_QUALITY_REQUIREMENT,c11_final_requirement_report,System must keep an unalterable audit trail ca...,non_functional_requirements,NFR,84.88,GOOD,"{'doc_id': '0000 cctns', 'page_num': 6, 'ambig..."
6,HIGH_QUALITY_REQUIREMENT,c11_final_requirement_report,The System must allow a user to be a member of...,non_functional_requirements,UNCERTAIN,88.97,EXCELLENT,"{'doc_id': '0000 cctns', 'page_num': 8, 'ambig..."
7,HIGH_QUALITY_REQUIREMENT,c11_final_requirement_report,The System must allow only admin-users to set ...,non_functional_requirements,UNCERTAIN,79.52,GOOD,"{'doc_id': '0000 cctns', 'page_num': 8, 'ambig..."
8,HIGH_QUALITY_REQUIREMENT,c11_final_requirement_report,The System should allow a user to stipulate wh...,non_functional_requirements,FR,97.67,EXCELLENT,"{'doc_id': '0000 cctns', 'page_num': 8, 'ambig..."
9,HIGH_QUALITY_REQUIREMENT,c11_final_requirement_report,The System must allow changes to security attr...,non_functional_requirements,NFR,87.90,EXCELLENT,"{'doc_id': '0000 cctns', 'page_num': 8, 'ambig..."
10,HIGH_QUALITY_REQUIREMENT,c11_final_requirement_report,"right to access, the System must provide one o...",non_functional_requirements,FR,97.89,EXCELLENT,"{'doc_id': '0000 cctns', 'page_num': 8, 'ambig..."
11,HIGH_QUALITY_REQUIREMENT,c11_final_requirement_report,"If a user performs a quick or advanced search,...",non_functional_requirements,FR,97.69,EXCELLENT,"{'doc_id': '0000 cctns', 'page_num': 8, 'ambig..."
12,HIGH_QUALITY_REQUIREMENT,c11_final_requirement_report,must log these in the audit trail.,non_functional_requirements,FR,93.92,EXCELLENT,"{'doc_id': '0000 cctns', 'page_num': 8, 'ambig..."
13,HIGH_QUALITY_REQUIREMENT,c11_final_requirement_report,documents or data should also need to be store...,non_functional_requirements,NFR,74.06,GOOD,"{'doc_id': '0000 cctns', 'page_num': 8, 'ambig..."
14,HIGH_QUALITY_REQUIREMENT,c11_final_requirement_report,All error messages produced by the System must...,non_functional_requirements,NFR,83.61,GOOD,"{'doc_id': '0000 cctns', 'page_num': 8, 'ambig..."
15,HIGH_QUALITY_REQUIREMENT,c11_final_requirement_report,message will be accompanied by explanatory tex...,non_functional_requirements,FR,94.87,EXCELLENT,"{'doc_id': '0000 cctns', 'page_num': 8, 'ambig..."
16,HIGH_QUALITY_REQUIREMENT,c11_final_requirement_report,The System must employ a single set of user in...,non_functional_requirements,NFR,87.43,EXCELLENT,"{'doc_id': '0000 cctns', 'page_num': 8, 'ambig..."
17,HIGH_QUALITY_REQUIREMENT,c11_final_requirement_report,should provide the user with a clear and suffi...,non_functional_requirements,NFR,74.46,GOOD,"{'doc_id': '0000 cctns', 'page_num': 10, 'ambi..."
18,HIGH_QUALITY_REQUIREMENT,c11_final_requirement_report,or special error pages should clearly state th...,non_functional_requirements,UNCERTAIN,81.90,GOOD,"{'doc_id': '0000 cctns', 'page_num': 11, 'ambi..."
19,HIGH_QUALITY_REQUIREMENT,c11_final_requirement_report,shall be consulted for screen text legibility ...,non_functional_requirements,FR,89.69,EXCELLENT,"{'doc_id': '0000 cctns', 'page_num': 11, 'ambi..."

In [5]:
# =========================================================
# MODULE G3 — BUILD RAG RETRIEVAL ENGINE
# =========================================================

print("=" * 80)
print("MODULE G3 — BUILD RAG RETRIEVAL ENGINE")
print("=" * 80)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

df_generation_kb["rag_text"] = (
    df_generation_kb["kb_type"].astype(str) + " " +
    df_generation_kb["section_label"].astype(str) + " " +
    df_generation_kb["requirement_type"].astype(str) + " " +
    df_generation_kb["text"].astype(str)
)

rag_vectorizer = TfidfVectorizer(
    max_features=20000,
    ngram_range=(1, 2),
    stop_words="english"
)

rag_matrix = rag_vectorizer.fit_transform(df_generation_kb["rag_text"])

print("RAG matrix shape:", rag_matrix.shape)


def retrieve_rag_examples(query, top_k=8, kb_type_filter=None, requirement_type_filter=None):
    temp_df = df_generation_kb.copy()
    temp_matrix = rag_matrix
    
    mask = pd.Series([True] * len(temp_df))
    
    if kb_type_filter is not None:
        mask &= temp_df["kb_type"].isin(kb_type_filter)
    
    if requirement_type_filter is not None:
        mask &= temp_df["requirement_type"].isin(requirement_type_filter)
    
    filtered_indices = temp_df[mask].index.tolist()
    
    if len(filtered_indices) == 0:
        filtered_indices = temp_df.index.tolist()
    
    query_vec = rag_vectorizer.transform([query])
    similarities = cosine_similarity(query_vec, rag_matrix[filtered_indices]).flatten()
    
    top_positions = similarities.argsort()[::-1][:top_k]
    selected_indices = [filtered_indices[pos] for pos in top_positions]
    
    results = df_generation_kb.loc[selected_indices].copy()
    results["similarity"] = similarities[top_positions]
    
    return results.reset_index(drop=True)


test_query = "generate functional requirements for user login appointment booking security performance"
test_results = retrieve_rag_examples(test_query, top_k=5)

display(test_results[["kb_type", "requirement_type", "section_label", "similarity", "text"]])

================================================================================
MODULE G3 — BUILD RAG RETRIEVAL ENGINE
================================================================================
RAG matrix shape: (3306, 20000)

,kb_type,requirement_type,section_label,similarity,text
0,HIGH_QUALITY_REQUIREMENT,FR,introduction,0.263816,Functional requirements specify actions that a...
1,HIGH_QUALITY_REQUIREMENT,FR,design_constraints,0.262730,Functional requirements specify actions that a...
2,HIGH_QUALITY_REQUIREMENT,FR,introduction,0.257067,• The authoring tool should allow the function...
3,HIGH_QUALITY_REQUIREMENT,FR,appendices,0.249961,diagnostic will be enumerated and described un...
4,HIGH_QUALITY_REQUIREMENT,FR,appendices,0.189758,Functional requirements: A statement of a piec...

In [6]:
# =========================================================
# MODULE G4 — USER PROJECT PROMPT
# =========================================================

print("=" * 80)
print("MODULE G4 — USER PROJECT PROMPT")
print("=" * 80)

USER_PROJECT_PROMPT = """
Project title: Smart University Attendance Management System

Prepared by: Sarah Boussaidi

Project description:
The system helps universities manage student attendance using a web and mobile platform.
Teachers can create sessions, students can check in, administrators can manage courses,
and the system generates attendance reports.

Functional needs:
- Student registration and authentication
- Teacher authentication
- Course and class management
- Attendance session creation
- Student check-in
- Attendance report generation
- Admin dashboard

Non-functional needs:
- Security
- Performance
- Availability
- Usability
- Reliability
- Maintainability

Target users:
- Students
- Teachers
- Administrators

Constraints:
- The system should be accessible through web browsers.
- The system should support many students at the same time.
- The system should protect user data.
"""

print(USER_PROJECT_PROMPT)

================================================================================
MODULE G4 — USER PROJECT PROMPT
================================================================================

Project title: Smart University Attendance Management System

Prepared by: Sarah Boussaidi

Project description:
The system helps universities manage student attendance using a web and mobile platform.
Teachers can create sessions, students can check in, administrators can manage courses,
and the system generates attendance reports.

Functional needs:
- Student registration and authentication
- Teacher authentication
- Course and class management
- Attendance session creation
- Student check-in
- Attendance report generation
- Admin dashboard

Non-functional needs:
- Security
- Performance
- Availability
- Usability
- Reliability
- Maintainability

Target users:
- Students
- Teachers
- Administrators

Constraints:
- The system should be accessible through web browsers.
- The system should support many students at the same time.
- The system should protect user data.

In [7]:
# =========================================================
# MODULE G5 — PARSE USER PROJECT PROMPT
# =========================================================

print("=" * 80)
print("MODULE G5 — PARSE USER PROJECT PROMPT")
print("=" * 80)

def extract_field(prompt, field_name):
    pattern = rf"{field_name}\s*:\s*(.*)"
    match = re.search(pattern, prompt, flags=re.IGNORECASE)
    if match:
        return match.group(1).strip()
    return ""

def extract_bullets_after(prompt, section_name):
    lines = prompt.splitlines()
    collecting = False
    bullets = []
    
    for line in lines:
        clean = line.strip()
        
        if re.match(rf"{section_name}\s*:", clean, flags=re.IGNORECASE):
            collecting = True
            continue
        
        if collecting:
            if re.match(r"^[A-Za-z ].*:\s*$", clean) and not clean.startswith("-"):
                break
            
            if clean.startswith("-"):
                bullets.append(clean.lstrip("-").strip())
    
    return bullets

project_info = {
    "project_title": extract_field(USER_PROJECT_PROMPT, "Project title"),
    "prepared_by": extract_field(USER_PROJECT_PROMPT, "Prepared by"),
    "description": "",
    "functional_needs": extract_bullets_after(USER_PROJECT_PROMPT, "Functional needs"),
    "non_functional_needs": extract_bullets_after(USER_PROJECT_PROMPT, "Non-functional needs"),
    "target_users": extract_bullets_after(USER_PROJECT_PROMPT, "Target users"),
    "constraints": extract_bullets_after(USER_PROJECT_PROMPT, "Constraints")
}

# Description block extraction
desc_match = re.search(
    r"Project description\s*:\s*(.*?)(Functional needs\s*:|Non-functional needs\s*:|Target users\s*:|Constraints\s*:|$)",
    USER_PROJECT_PROMPT,
    flags=re.IGNORECASE | re.DOTALL
)

if desc_match:
    project_info["description"] = normalize_text(desc_match.group(1))

print(json.dumps(project_info, indent=2))

================================================================================
MODULE G5 — PARSE USER PROJECT PROMPT
================================================================================
{
  "project_title": "Smart University Attendance Management System",
  "prepared_by": "Sarah Boussaidi",
  "description": "The system helps universities manage student attendance using a web and mobile platform. Teachers can create sessions, students can check in, administrators can manage courses, and the system generates attendance reports.",
  "functional_needs": [
    "Student registration and authentication",
    "Teacher authentication",
    "Course and class management",
    "Attendance session creation",
    "Student check-in",
    "Attendance report generation",
    "Admin dashboard"
  ],
  "non_functional_needs": [
    "Security",
    "Performance",
    "Availability",
    "Usability",
    "Reliability",
    "Maintainability"
  ],
  "target_users": [
    "Students",
    "Teachers",
    "Administrators"
  ],
  "constraints": [
    "The system should be accessible through web browsers.",
    "The system should support many students at the same time.",
    "The system should protect user data."
  ]
}

In [8]:
# =========================================================
# MODULE G6 — LOAD INSTRUCTION-TUNED LLM
# =========================================================

print("=" * 80)
print("MODULE G6 — LOAD INSTRUCTION-TUNED LLM")
print("=" * 80)

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

LLM_MODEL_NAME = "Qwen/Qwen2.5-1.5B-Instruct"

print("Selected LLM:", LLM_MODEL_NAME)

llm_tokenizer = AutoTokenizer.from_pretrained(
    LLM_MODEL_NAME,
    trust_remote_code=True
)

llm_model = AutoModelForCausalLM.from_pretrained(
    LLM_MODEL_NAME,
    torch_dtype=torch.float16 if device == "cuda" else torch.float32,
    device_map="auto" if device == "cuda" else None,
    trust_remote_code=True
)

if device == "cpu":
    llm_model = llm_model.to(device)

llm_model.eval()

print("LLM loaded successfully.")

================================================================================
MODULE G6 — LOAD INSTRUCTION-TUNED LLM
================================================================================
Device: cpu
Selected LLM: Qwen/Qwen2.5-1.5B-Instruct

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
`torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

LLM loaded successfully.

In [9]:
# =========================================================
# MODULE G7 — LLM GENERATION HELPER
# =========================================================

print("=" * 80)
print("MODULE G7 — LLM GENERATION HELPER")
print("=" * 80)

def generate_with_llm(prompt, max_new_tokens=1200, temperature=0.25):
    messages = [
        {
            "role": "system",
            "content": (
                "You are a senior Software Requirements Specification engineer. "
                "You write professional, complete, testable, and structured SRS documents."
            )
        },
        {
            "role": "user",
            "content": prompt
        }
    ]
    
    text = llm_tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    
    inputs = llm_tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=4096
    ).to(llm_model.device)
    
    with torch.no_grad():
        outputs = llm_model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=temperature,
            top_p=0.9,
            repetition_penalty=1.08,
            pad_token_id=llm_tokenizer.eos_token_id
        )
    
    generated_ids = outputs[0][inputs["input_ids"].shape[-1]:]
    response = llm_tokenizer.decode(generated_ids, skip_special_tokens=True)
    
    return response.strip()

print("LLM generation helper ready.")

================================================================================
MODULE G7 — LLM GENERATION HELPER
================================================================================
LLM generation helper ready.

In [10]:
# =========================================================
# MODULE G8 — BUILD SECTION GENERATION PROMPTS WITH RAG
# =========================================================

print("=" * 80)
print("MODULE G8 — BUILD SECTION GENERATION PROMPTS WITH RAG")
print("=" * 80)

SRS_SECTIONS = [
    {
        "section_id": "1",
        "section_title": "Introduction",
        "goal": "Introduce the project, purpose, scope, target users, and document overview."
    },
    {
        "section_id": "2",
        "section_title": "General Description",
        "goal": "Describe system context, users, assumptions, constraints, and operating environment."
    },
    {
        "section_id": "3",
        "section_title": "Functional Requirements",
        "goal": "Generate clear functional requirements using shall statements."
    },
    {
        "section_id": "4",
        "section_title": "Non-Functional Requirements",
        "goal": "Generate measurable NFRs for security, performance, availability, usability, reliability, and maintainability."
    },
    {
        "section_id": "5",
        "section_title": "Interface Requirements",
        "goal": "Describe user interface, system interface, and external interface requirements."
    },
    {
        "section_id": "6",
        "section_title": "Performance Requirements",
        "goal": "Define measurable response time, throughput, load, and scalability requirements."
    },
    {
        "section_id": "7",
        "section_title": "Security Requirements",
        "goal": "Define authentication, authorization, privacy, audit, and data protection requirements."
    },
    {
        "section_id": "8",
        "section_title": "Acceptance Criteria",
        "goal": "Define acceptance criteria for validating the generated SRS."
    },
    {
        "section_id": "9",
        "section_title": "Risks and Assumptions",
        "goal": "List project risks, assumptions, dependencies, and limitations."
    },
    {
        "section_id": "10",
        "section_title": "Conclusion",
        "goal": "Summarize the SRS and the expected project outcome."
    }
]


def format_rag_examples(df_examples, max_chars=3500):
    chunks = []
    
    for i, row in df_examples.iterrows():
        text = str(row["text"])
        text = text[:900]
        chunks.append(
            f"Example {i + 1} | Type: {row.get('requirement_type', 'UNKNOWN')} | "
            f"Section: {row.get('section_label', 'unknown')}\n{text}"
        )
    
    final = "\n\n".join(chunks)
    
    if len(final) > max_chars:
        final = final[:max_chars] + "\n..."
    
    return final


def build_section_prompt(section, project_info):
    query = (
        project_info["project_title"] + " " +
        project_info["description"] + " " +
        section["section_title"] + " " +
        section["goal"] + " " +
        " ".join(project_info["functional_needs"]) + " " +
        " ".join(project_info["non_functional_needs"])
    )
    
    examples = retrieve_rag_examples(
        query=query,
        top_k=8,
        kb_type_filter=["HIGH_QUALITY_REQUIREMENT", "REWRITE_EXAMPLE"]
    )
    
    rag_context = format_rag_examples(examples)
    
    prompt = f"""
You are generating a professional Software Requirements Specification section.

Project information:
- Project title: {project_info["project_title"]}
- Prepared by: {project_info["prepared_by"]}
- Description: {project_info["description"]}
- Functional needs: {project_info["functional_needs"]}
- Non-functional needs: {project_info["non_functional_needs"]}
- Target users: {project_info["target_users"]}
- Constraints: {project_info["constraints"]}

Current SRS section:
- Section number: {section["section_id"]}
- Section title: {section["section_title"]}
- Section goal: {section["goal"]}

Relevant examples retrieved from previous analyzed SRS documents:
{rag_context}

Generation rules:
1. Write in a formal SRS style.
2. Use numbered subsections when useful.
3. For requirements, use clear "shall" statements.
4. Make requirements testable and measurable.
5. Do not invent impossible features.
6. Use placeholders like [SPECIFY THRESHOLD] only when a numeric value is necessary but missing.
7. Avoid vague words such as fast, easy, user-friendly, appropriate, sufficient.
8. Return only the section content in Markdown.
"""
    
    return prompt.strip(), examples


test_section_prompt, test_examples = build_section_prompt(SRS_SECTIONS[2], project_info)

print(test_section_prompt[:3000])
display(test_examples[["kb_type", "requirement_type", "similarity", "text"]].head())

================================================================================
MODULE G8 — BUILD SECTION GENERATION PROMPTS WITH RAG
================================================================================
You are generating a professional Software Requirements Specification section.

Project information:
- Project title: Smart University Attendance Management System
- Prepared by: Sarah Boussaidi
- Description: The system helps universities manage student attendance using a web and mobile platform. Teachers can create sessions, students can check in, administrators can manage courses, and the system generates attendance reports.
- Functional needs: ['Student registration and authentication', 'Teacher authentication', 'Course and class management', 'Attendance session creation', 'Student check-in', 'Attendance report generation', 'Admin dashboard']
- Non-functional needs: ['Security', 'Performance', 'Availability', 'Usability', 'Reliability', 'Maintainability']
- Target users: ['Students', 'Teachers', 'Administrators']
- Constraints: ['The system should be accessible through web browsers.', 'The system should support many students at the same time.', 'The system should protect user data.']

Current SRS section:
- Section number: 3
- Section title: Functional Requirements
- Section goal: Generate clear functional requirements using shall statements.

Relevant examples retrieved from previous analyzed SRS documents:
Example 1 | Type: FR | Section: introduction
Functional requirements specify actions that a system must be able to perform,

Example 2 | Type: FR | Section: design_constraints
Functional requirements specify actions that a system must be able to perform,

Example 3 | Type: FR | Section: introduction
• The authoring tool should allow the functional requirements specification of the

Example 4 | Type: FR | Section: appendices
diagnostic will be enumerated and described under the functional requirements section.

Example 5 | Type: NFR | Section: introduction
system performance), availability (high availability must be guaranteed through

Example 6 | Type: NFR | Section: nan
6. Non functional requirements 6.1.Usability It is mandatory that learning time is between 2 to 4 hours at maximum; because many task are delegated to working students. Web interface should use clear and consistence terminology in such a way that user; with basic experience On internet and office; find the application easy to use

Example 7 | Type: NFR | Section: appendices
CRS0129 Reliability and Maintainability. The system shall demonstrate a

Example 8 | Type: FR | Section: appendices
Functional requirements: A statement of a piece of required functionality or a behavior that a system will exhibit under specific conditions

Generation rules:
1. Write in a formal SRS style.
2. Use numbered subsections when useful.
3. For requirements, use clear "shall" statements.
4. Make requirements testable and measurable.
5. Do not invent impossible features.
6. Use placeholders like [SPECIFY THRESHOLD] only when a numeric value is necessary but missing.
7. Avoid vague words such as fast, easy, user-friendly, appropriate, sufficient.
8. Return only the section content in Markdown.

,kb_type,requirement_type,similarity,text
0,HIGH_QUALITY_REQUIREMENT,FR,0.169710,Functional requirements specify actions that a...
1,HIGH_QUALITY_REQUIREMENT,FR,0.169011,Functional requirements specify actions that a...
2,HIGH_QUALITY_REQUIREMENT,FR,0.165368,• The authoring tool should allow the function...
3,HIGH_QUALITY_REQUIREMENT,FR,0.160797,diagnostic will be enumerated and described un...
4,HIGH_QUALITY_REQUIREMENT,NFR,0.139650,"system performance), availability (high availa..."

In [11]:
# =========================================================
# MODULE G9 — GENERATE FULL SRS SECTION BY SECTION
# =========================================================

print("=" * 80)
print("MODULE G9 — GENERATE FULL SRS SECTION BY SECTION")
print("=" * 80)

from tqdm.auto import tqdm

generated_sections = []
rag_reference_rows = []

for section in tqdm(SRS_SECTIONS, desc="Generating SRS sections"):
    prompt, examples = build_section_prompt(section, project_info)
    
    section_text = generate_with_llm(
        prompt,
        max_new_tokens=1200,
        temperature=0.25
    )
    
    generated_sections.append({
        "section_id": section["section_id"],
        "section_title": section["section_title"],
        "section_goal": section["goal"],
        "generated_text": section_text
    })
    
    examples = examples.copy()
    examples["generated_section_id"] = section["section_id"]
    examples["generated_section_title"] = section["section_title"]
    rag_reference_rows.append(examples)

df_generated_sections = pd.DataFrame(generated_sections)

if len(rag_reference_rows) > 0:
    df_rag_references = pd.concat(rag_reference_rows, ignore_index=True)
else:
    df_rag_references = pd.DataFrame()

print("Generated sections shape:", df_generated_sections.shape)
print("RAG references shape:", df_rag_references.shape)

display(df_generated_sections)

================================================================================
MODULE G9 — GENERATE FULL SRS SECTION BY SECTION
================================================================================

Generating SRS sections:   0%|          | 0/10 [00:00<?, ?it/s]

Generated sections shape: (10, 4)
RAG references shape: (80, 12)

,section_id,section_title,section_goal,generated_text
0,1,Introduction,"Introduce the project, purpose, scope, target ...",# 1. Introduction\n\n## 1.1 Purpose\nThe Smart...
1,2,General Description,"Describe system context, users, assumptions, c...",# 2. General Description\n\n## 2.1 Introductio...
2,3,Functional Requirements,Generate clear functional requirements using s...,### 3. Functional Requirements\n\n#### 3.1 Stu...
3,4,Non-Functional Requirements,"Generate measurable NFRs for security, perform...",# Non-Functional Requirements\n\n## 4. Non-Fun...
4,5,Interface Requirements,"Describe user interface, system interface, and...",# Interface Requirements\n\n## 5.1 User Interf...
5,6,Performance Requirements,"Define measurable response time, throughput, l...",# 6. Performance Requirements\n\n## 6.1 Respon...
6,7,Security Requirements,"Define authentication, authorization, privacy,...",### Section 7: Security Requirements\n\n#### S...
7,8,Acceptance Criteria,Define acceptance criteria for validating the ...,# Acceptance Criteria\n\n## 8. Acceptance Crit...
8,9,Risks and Assumptions,"List project risks, assumptions, dependencies,...",# Risks and Assumptions\n\n## Risks\n\n### Sec...
9,10,Conclusion,Summarize the SRS and the expected project out...,# 10. Conclusion\n\n## Goal\nSummarize the Sof...

In [12]:
# =========================================================
# MODULE G10 — EXTRACT GENERATED REQUIREMENTS
# =========================================================

print("=" * 80)
print("MODULE G10 — EXTRACT GENERATED REQUIREMENTS")
print("=" * 80)

def extract_generated_requirements(section_text):
    lines = section_text.splitlines()
    reqs = []
    
    for line in lines:
        clean = line.strip()
        clean = re.sub(r"^[\-\*\d\.\)\s]+", "", clean).strip()
        
        if re.search(r"\b(shall|must|should)\b", clean, flags=re.IGNORECASE):
            if len(clean.split()) >= 5:
                reqs.append(clean)
    
    return reqs

generated_req_rows = []

for _, row in df_generated_sections.iterrows():
    reqs = extract_generated_requirements(row["generated_text"])
    
    for i, req in enumerate(reqs, start=1):
        generated_req_rows.append({
            "section_id": row["section_id"],
            "section_title": row["section_title"],
            "generated_requirement_id": f"GREQ-{row['section_id']}-{i:03d}",
            "generated_requirement_text": req
        })

df_generated_requirements = pd.DataFrame(generated_req_rows)

print("Generated requirements shape:", df_generated_requirements.shape)

display(df_generated_requirements.head(50))

================================================================================
MODULE G10 — EXTRACT GENERATED REQUIREMENTS
================================================================================
Generated requirements shape: (144, 4)

,section_id,section_title,generated_requirement_id,generated_requirement_text
0,2,General Description,GREQ-2-001,Accessibility: The system must be accessible v...
1,2,General Description,GREQ-2-002,Scalability: The system should support high tr...
2,2,General Description,GREQ-2-003,Requirement:** Students must be able to regist...
3,2,General Description,GREQ-2-004,Requirement:** Teachers must be authenticated ...
4,2,General Description,GREQ-2-005,Requirement:** Administrators must be able to ...
5,2,General Description,GREQ-2-006,Requirement:** Teachers must be able to create...
6,2,General Description,GREQ-2-007,Requirement:** Students must be able to check ...
7,2,General Description,GREQ-2-008,Requirement:** Administrators must be able to ...
8,2,General Description,GREQ-2-009,Requirement:** Administrators must have a dedi...
9,2,General Description,GREQ-2-010,Requirement:** All user data must be protected...
10,2,General Description,GREQ-2-011,Requirement:** The system must perform well un...
11,2,General Description,GREQ-2-012,Requirement:** The system must be available 24...
12,2,General Description,GREQ-2-013,Requirement:** The interface must be intuitive...
13,2,General Description,GREQ-2-014,Requirement:** The system must function reliab...
14,2,General Description,GREQ-2-015,Requirement:** The system must be easily maint...
15,2,General Description,GREQ-2-016,Note:** The system shall demonstrate a high le...
16,2,General Description,GREQ-2-017,Note:** The system shall comply with the lates...
17,2,General Description,GREQ-2-018,Note:** The system shall support multi-tier au...
18,3,Functional Requirements,GREQ-3-001,Shall** the system provide a secure and effici...
19,3,Functional Requirements,GREQ-3-002,Description**: Students shall be able to sign ...
20,3,Functional Requirements,GREQ-3-003,Shall** the system enable teachers to log in s...
21,3,Functional Requirements,GREQ-3-004,Description**: Teachers shall be able to acces...
22,3,Functional Requirements,GREQ-3-005,Shall** the system facilitate the creation and...
23,3,Functional Requirements,GREQ-3-006,Description**: Teachers shall be able to creat...
24,3,Functional Requirements,GREQ-3-007,Shall** the system allow teachers to schedule ...
25,3,Functional Requirements,GREQ-3-008,Description**: Teachers shall be able to creat...
26,3,Functional Requirements,GREQ-3-009,Shall** the system enable students to check in...
27,3,Functional Requirements,GREQ-3-010,Description**: Students shall be able to log i...
28,3,Functional Requirements,GREQ-3-011,Shall** the system generate detailed attendanc...
29,3,Functional Requirements,GREQ-3-012,Description**: The system shall automatically ...
30,3,Functional Requirements,GREQ-3-013,Shall** the system provide an admin dashboard ...
31,3,Functional Requirements,GREQ-3-014,Description**: Administrators shall have acces...
32,3,Functional Requirements,GREQ-3-015,Shall** the system ensure robust security meas...
33,3,Functional Requirements,GREQ-3-016,Description**: The system shall implement encr...
34,3,Functional Requirements,GREQ-3-017,Shall** the system maintain acceptable perform...
35,3,Functional Requirements,GREQ-3-018,Description**: The system shall scale well to ...
36,3,Functional Requirements,GREQ-3-019,Shall** the system remain available to users c...
37,3,Functional Requirements,GREQ-3-020,Description**: The system shall operate reliab...
38,3,Functional Requirements,GREQ-3-021,Shall** the system meet usability standards to...
39,3,Functional Requirements,GREQ-3-022,Description**: The system shall be intuitive a...
40,3,Functional Requirements,GREQ-3-023,Shall** the system demonstrate reliability and...
41,4,Non-Functional Requirements,GREQ-4-001,The system shall ensure secure user authentica...
42,4,Non-Functional Requirements,GREQ-4-002,The system shall be designed to handle concurr...
43,4,Non-Functional Requirements,GREQ-4-003,The system shall operate continuously without ...
44,4,Non-Functional Requirements,GREQ-4-004,The user interface shall be intuitive and cons...
45,4,Non-Functional Requirements,GREQ-4-005,The system shall exhibit high reliability with...
46,4,Non-Functional Requirements,GREQ-4-006,"The system shall be modular and extensible, fa..."
47,5,Interface Requirements,GREQ-5-001,Requirement:** The system shall provide an int...
48,5,Interface Requirements,GREQ-5-002,Requirement:** The system shall allow teachers...
49,5,Interface Requirements,GREQ-5-003,Requirement:** The system shall enable adminis...

In [13]:
# =========================================================
# MODULE G11 — VALIDATE GENERATED REQUIREMENTS
# =========================================================

print("=" * 80)
print("MODULE G11 — VALIDATE GENERATED REQUIREMENTS")
print("=" * 80)

vague_terms = [
    "fast", "quick", "easy", "simple", "user-friendly", "appropriate",
    "sufficient", "adequate", "as needed", "as required", "etc",
    "efficient", "robust", "seamless", "good", "bad", "normal"
]

numeric_pattern = r"\d+|%|seconds?|minutes?|hours?|days?|ms|milliseconds?|kb|mb|gb|users?|requests?|transactions?|availability|uptime"

def validate_generated_requirement(text):
    text = str(text)
    low = text.lower()
    word_count = len(low.split())
    
    has_modal = bool(re.search(r"\b(shall|must|should)\b", low))
    has_vague = any(term in low for term in vague_terms)
    has_numeric = bool(re.search(numeric_pattern, low))
    has_actor_system = bool(re.search(r"\b(system|user|student|teacher|administrator|admin|application|platform)\b", low))
    
    clarity = 100
    testability = 100
    measurability = 100
    completeness = 100
    
    if word_count < 8:
        clarity -= 25
        completeness -= 25
    
    if not has_modal:
        clarity -= 20
        testability -= 25
    
    if has_vague:
        clarity -= 30
        testability -= 20
        measurability -= 20
    
    if not has_numeric:
        measurability -= 20
    
    if not has_actor_system:
        completeness -= 20
    
    final_score = np.mean([clarity, testability, measurability, completeness])
    final_score = max(0, min(100, round(final_score, 2)))
    
    if final_score >= 85:
        label = "STRONG_GENERATED_REQUIREMENT"
    elif final_score >= 70:
        label = "ACCEPTABLE_GENERATED_REQUIREMENT"
    elif final_score >= 50:
        label = "NEEDS_REVIEW"
    else:
        label = "WEAK_GENERATED_REQUIREMENT"
    
    return pd.Series({
        "generated_word_count": word_count,
        "generated_has_modal": has_modal,
        "generated_has_vague_terms": has_vague,
        "generated_has_numeric_or_quality_constraint": has_numeric,
        "generated_has_actor_or_system": has_actor_system,
        "generated_clarity_score": round(clarity, 2),
        "generated_testability_score": round(testability, 2),
        "generated_measurability_score": round(measurability, 2),
        "generated_completeness_score": round(completeness, 2),
        "generated_quality_score": final_score,
        "generated_quality_label": label
    })

if len(df_generated_requirements) > 0:
    df_generated_validation = df_generated_requirements["generated_requirement_text"].apply(
        validate_generated_requirement
    )
    
    df_generated_requirements = pd.concat(
        [df_generated_requirements.reset_index(drop=True), df_generated_validation.reset_index(drop=True)],
        axis=1
    )

print("Generated requirement quality distribution:")
print(df_generated_requirements["generated_quality_label"].value_counts())

print("\nGenerated quality score summary:")
display(df_generated_requirements["generated_quality_score"].describe())

display(df_generated_requirements.head(50))

================================================================================
MODULE G11 — VALIDATE GENERATED REQUIREMENTS
================================================================================
Generated requirement quality distribution:
generated_quality_label
STRONG_GENERATED_REQUIREMENT        124
ACCEPTABLE_GENERATED_REQUIREMENT     20
Name: count, dtype: int64

Generated quality score summary:

count    144.000000
mean      93.680556
std        6.201345
min       77.500000
25%       90.000000
50%       95.000000
75%      100.000000
max      100.000000
Name: generated_quality_score, dtype: float64

,section_id,section_title,generated_requirement_id,generated_requirement_text,generated_word_count,generated_has_modal,generated_has_vague_terms,generated_has_numeric_or_quality_constraint,generated_has_actor_or_system,generated_clarity_score,generated_testability_score,generated_measurability_score,generated_completeness_score,generated_quality_score,generated_quality_label
0,2,General Description,GREQ-2-001,Accessibility: The system must be accessible v...,9,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
1,2,General Description,GREQ-2-002,Scalability: The system should support high tr...,11,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
2,2,General Description,GREQ-2-003,Requirement:** Students must be able to regist...,16,True,False,True,False,100,100,100,80,95.0,STRONG_GENERATED_REQUIREMENT
3,2,General Description,GREQ-2-004,Requirement:** Teachers must be authenticated ...,12,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
4,2,General Description,GREQ-2-005,Requirement:** Administrators must be able to ...,17,True,False,False,False,100,100,80,80,90.0,STRONG_GENERATED_REQUIREMENT
5,2,General Description,GREQ-2-006,Requirement:** Teachers must be able to create...,14,True,False,False,False,100,100,80,80,90.0,STRONG_GENERATED_REQUIREMENT
6,2,General Description,GREQ-2-007,Requirement:** Students must be able to check ...,12,True,False,False,False,100,100,80,80,90.0,STRONG_GENERATED_REQUIREMENT
7,2,General Description,GREQ-2-008,Requirement:** Administrators must be able to ...,15,True,False,False,False,100,100,80,80,90.0,STRONG_GENERATED_REQUIREMENT
8,2,General Description,GREQ-2-009,Requirement:** Administrators must have a dedi...,20,True,False,False,False,100,100,80,80,90.0,STRONG_GENERATED_REQUIREMENT
9,2,General Description,GREQ-2-010,Requirement:** All user data must be protected...,12,True,False,True,True,100,100,100,100,100.0,STRONG_GENERATED_REQUIREMENT
10,2,General Description,GREQ-2-011,Requirement:** The system must perform well un...,16,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
11,2,General Description,GREQ-2-012,Requirement:** The system must be available 24...,10,True,False,True,True,100,100,100,100,100.0,STRONG_GENERATED_REQUIREMENT
12,2,General Description,GREQ-2-013,Requirement:** The interface must be intuitive...,14,True,True,True,False,70,80,80,80,77.5,ACCEPTABLE_GENERATED_REQUIREMENT
13,2,General Description,GREQ-2-014,Requirement:** The system must function reliab...,11,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
14,2,General Description,GREQ-2-015,Requirement:** The system must be easily maint...,9,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
15,2,General Description,GREQ-2-016,Note:** The system shall demonstrate a high le...,27,True,False,True,True,100,100,100,100,100.0,STRONG_GENERATED_REQUIREMENT
16,2,General Description,GREQ-2-017,Note:** The system shall comply with the lates...,15,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
17,2,General Description,GREQ-2-018,Note:** The system shall support multi-tier au...,12,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
18,3,Functional Requirements,GREQ-3-001,Shall** the system provide a secure and effici...,16,True,True,True,True,70,80,80,100,82.5,ACCEPTABLE_GENERATED_REQUIREMENT
19,3,Functional Requirements,GREQ-3-002,Description**: Students shall be able to sign ...,32,True,False,False,False,100,100,80,80,90.0,STRONG_GENERATED_REQUIREMENT
20,3,Functional Requirements,GREQ-3-003,Shall** the system enable teachers to log in s...,12,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
21,3,Functional Requirements,GREQ-3-004,Description**: Teachers shall be able to acces...,27,True,False,True,True,100,100,100,100,100.0,STRONG_GENERATED_REQUIREMENT
22,3,Functional Requirements,GREQ-3-005,Shall** the system facilitate the creation and...,14,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
23,3,Functional Requirements,GREQ-3-006,Description**: Teachers shall be able to creat...,32,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
24,3,Functional Requirements,GREQ-3-007,Shall** the system allow teachers to schedule ...,11,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
25,3,Functional Requirements,GREQ-3-008,Description**: Teachers shall be able to creat...,30,True,False,False,False,100,100,80,80,90.0,STRONG_GENERATED_REQUIREMENT
26,3,Functional Requirements,GREQ-3-009,Shall** the system enable students to check in...,10,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
27,3,Functional Requirements,GREQ-3-010,Description**: Students shall be able to log i...,33,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
28,3,Functional Requirements,GREQ-3-011,Shall** the system generate detailed attendanc...,8,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
29,3,Functional Requirements,GREQ-3-012,Description**: The system shall automatically ...,30,True,False,True,True,100,100,100,100,100.0,STRONG_GENERATED_REQUIREMENT
30,3,Functional Requirements,GREQ-3-013,Shall** the system provide an admin dashboard ...,14,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
31,3,Functional Requirements,GREQ-3-014,Description**: Administrators shall have acces...,31,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
32,3,Functional Requirements,GREQ-3-015,Shall** the system ensure robust security meas...,11,True,True,True,True,70,80,80,100,82.5,ACCEPTABLE_GENERATED_REQUIREMENT
33,3,Functional Requirements,GREQ-3-016,Description**: The system shall implement encr...,25,True,False,True,True,100,100,100,100,100.0,STRONG_GENERATED_REQUIREMENT
34,3,Functional Requirements,GREQ-3-017,Shall** the system maintain acceptable perform...,10,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
35,3,Functional Requirements,GREQ-3-018,Description**: The system shall scale well to ...,28,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
36,3,Functional Requirements,GREQ-3-019,Shall** the system remain available to users c...,8,True,False,True,True,100,100,100,100,100.0,STRONG_GENERATED_REQUIREMENT
37,3,Functional Requirements,GREQ-3-020,Description**: The system shall operate reliab...,21,True,False,True,True,100,100,100,100,100.0,STRONG_GENERATED_REQUIREMENT
38,3,Functional Requirements,GREQ-3-021,Shall** the system meet usability standards to...,10,True,False,True,True,100,100,100,100,100.0,STRONG_GENERATED_REQUIREMENT
39,3,Functional Requirements,GREQ-3-022,Description**: The system shall be intuitive a...,23,True,True,True,True,70,80,80,100,82.5,ACCEPTABLE_GENERATED_REQUIREMENT
40,3,Functional Requirements,GREQ-3-023,Shall** the system demonstrate reliability and...,7,True,False,False,True,75,100,80,75,82.5,ACCEPTABLE_GENERATED_REQUIREMENT
41,4,Non-Functional Requirements,GREQ-4-001,The system shall ensure secure user authentica...,34,True,False,True,True,100,100,100,100,100.0,STRONG_GENERATED_REQUIREMENT
42,4,Non-Functional Requirements,GREQ-4-002,The system shall be designed to handle concurr...,42,True,True,True,True,70,80,80,100,82.5,ACCEPTABLE_GENERATED_REQUIREMENT
43,4,Non-Functional Requirements,GREQ-4-003,The system shall operate continuously without ...,36,True,False,True,True,100,100,100,100,100.0,STRONG_GENERATED_REQUIREMENT
44,4,Non-Functional Requirements,GREQ-4-004,The user interface shall be intuitive and cons...,42,True,True,True,True,70,80,80,100,82.5,ACCEPTABLE_GENERATED_REQUIREMENT
45,4,Non-Functional Requirements,GREQ-4-005,The system shall exhibit high reliability with...,28,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
46,4,Non-Functional Requirements,GREQ-4-006,"The system shall be modular and extensible, fa...",32,True,True,False,True,70,80,60,100,77.5,ACCEPTABLE_GENERATED_REQUIREMENT
47,5,Interface Requirements,GREQ-5-001,Requirement:** The system shall provide an int...,25,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
48,5,Interface Requirements,GREQ-5-002,Requirement:** The system shall allow teachers...,19,True,False,True,True,100,100,100,100,100.0,STRONG_GENERATED_REQUIREMENT
49,5,Interface Requirements,GREQ-5-003,Requirement:** The system shall enable adminis...,18,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT

In [14]:
# =========================================================
# MODULE G12 — BUILD FINAL SRS DOCUMENT
# =========================================================

print("=" * 80)
print("MODULE G12 — BUILD FINAL SRS DOCUMENT")
print("=" * 80)

from datetime import datetime

project_title = project_info["project_title"] or "Generated SRS Project"
prepared_by = project_info["prepared_by"] or "Unknown Author"
generation_date = datetime.now().strftime("%Y-%m-%d %H:%M")

def build_table_of_contents(sections):
    toc = []
    for _, row in sections.iterrows():
        toc.append(f"{row['section_id']}. {row['section_title']}")
    return "\n".join(toc)

toc_text = build_table_of_contents(df_generated_sections)

cover_page = f"""
# Software Requirements Specification

## {project_title}

**Prepared by:** {prepared_by}  
**Generated on:** {generation_date}  
**Generation method:** LLM + RAG + Quality Validation  
**Knowledge base:** Previous SRS requirements analyzed by NLP, Computer Vision, XAI, and quality scoring

---

# Table of Contents

{toc_text}

---
"""

section_texts = []

for _, row in df_generated_sections.iterrows():
    section_texts.append(
        f"# {row['section_id']}. {row['section_title']}\n\n{row['generated_text']}"
    )

references_section = f"""
# References and Data Sources

This generated SRS was created using a retrieval-augmented generation pipeline.

The generation knowledge base was built from the outputs of previous notebooks:

1. `c9_multimodal_requirement_quality_scores.csv`  
   Used as the main source of requirement quality signals.

2. `c10_llm_requirement_rewrites.csv`  
   Used as examples of weak-to-improved requirement rewriting.

3. `c11_final_requirement_report.csv`  
   Used as the final enriched requirement knowledge base.

4. `c11_final_document_report.csv`  
   Used for document-level quality context.

5. `c9_section_quality_summary.csv`  
   Used for section-level quality context.

The generated requirements were validated using rule-based quality checks for clarity, testability, measurability, and completeness.
"""

final_srs_markdown = cover_page + "\n\n" + "\n\n---\n\n".join(section_texts) + "\n\n---\n\n" + references_section

print(final_srs_markdown[:4000])

================================================================================
MODULE G12 — BUILD FINAL SRS DOCUMENT
================================================================================

# Software Requirements Specification

## Smart University Attendance Management System

**Prepared by:** Sarah Boussaidi
**Generated on:** 2026-05-10 21:35
**Generation method:** LLM + RAG + Quality Validation
**Knowledge base:** Previous SRS requirements analyzed by NLP, Computer Vision, XAI, and quality scoring

---

# Table of Contents

1. Introduction
2. General Description
3. Functional Requirements
4. Non-Functional Requirements
5. Interface Requirements
6. Performance Requirements
7. Security Requirements
8. Acceptance Criteria
9. Risks and Assumptions
10. Conclusion

---


# 1. Introduction

# 1. Introduction

## 1.1 Purpose
The Smart University Attendance Management System aims to enhance university operations by providing a comprehensive solution for managing student attendance, course scheduling, and administrative tasks. This system integrates seamlessly into existing university infrastructures, ensuring accessibility through web browsers while maintaining high levels of security, performance, and usability.

## 1.2 Scope
This document outlines the functional and non-functional requirements for the Smart University Attendance Management System. It covers key functionalities such as student registration and authentication, teacher authentication, course and class management, attendance session creation, student check-in, attendance report generation, and admin dashboard. Additionally, it addresses security, performance, availability, usability, reliability, and maintainability constraints.

## 1.3 Target Users
- **Students**: Users who need to register, check in, and view their attendance records.
- **Teachers**: Administrators responsible for creating sessions, managing courses, and overseeing student attendance.
- **Administrators**: Managers tasked with course administration, reporting, and system maintenance.

## 1.4 Project Scope
According to GAMMA-J's Functional Needs Statement, the Web Store will manage customer accounts, implement an online store inventory, handle shopping carts, confirm orders, ensure secure socket layer (SSL) security, guarantee high availability, offer an optional mirror site for reliability and backups, and provide an interface for future software enhancements via "Plug-ins." The initial inventory will consist of 100 items, expandable up to 20,000 items, and be available without requiring any software installations. The system will also feature advanced capabilities that can be added in the future via "Plug-ins."

---

### 1.5 Non-Functional Requirements

#### 1.5.1 Security
- **Authentication**: Implement robust multi-factor authentication mechanisms to ensure secure access to the system.
- **Data Encryption**: Encrypt sensitive data both in transit and at rest to protect against unauthorized access.
- **Access Control**: Implement role-based access control to restrict access based on user roles and permissions.

#### 1.5.2 Performance
- **Scalability**: Design the system to scale horizontally to accommodate increasing numbers of concurrent users.
- **Latency Reduction**: Minimize response times for critical operations such as student check-in and attendance report generation.
- **Load Balancing**: Utilize load balancers to distribute traffic evenly across multiple servers to improve overall system performance.

#### 1.5.3 Availability
- **High Availability**: Ensure the system remains operational 99.999% of the time to minimize downtime.
- **Redundancy**: Implement redundant systems and backup solutions to prevent data loss or service disruption.

#### 1.5.4 Usability
- **User Interface**: Design intuitive and responsive user interfaces for seamless navigation and interaction.
- **Accessibility**: Ensure the system is accessible to users with disabilities, including those with visual impairments.
- **Training Materials**: Provide comprehensive training materials and resources for new users.

#### 1.5.5 Reliability
- **Failover Mechanisms**: Implement failover mechanisms to auto

In [15]:
# =========================================================
# MODULE G13 — EXPORT FINAL SRS OUTPUTS
# =========================================================

print("=" * 80)
print("MODULE G13 — EXPORT FINAL SRS OUTPUTS")
print("=" * 80)

OUTPUT_DIR = Path("/kaggle/working/generated_srs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

safe_project_name = re.sub(r"[^a-zA-Z0-9]+", "_", project_title).strip("_").lower()

markdown_path = OUTPUT_DIR / f"{safe_project_name}_srs.md"
html_path = OUTPUT_DIR / f"{safe_project_name}_srs.html"
sections_path = OUTPUT_DIR / f"{safe_project_name}_generated_sections.csv"
requirements_path = OUTPUT_DIR / f"{safe_project_name}_generated_requirements.csv"
rag_refs_path = OUTPUT_DIR / f"{safe_project_name}_rag_references.csv"
summary_path = OUTPUT_DIR / f"{safe_project_name}_generation_summary.txt"

with open(markdown_path, "w", encoding="utf-8") as f:
    f.write(final_srs_markdown)

# Simple HTML export
html_content = final_srs_markdown
html_content = html_content.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
html_content = re.sub(r"^# (.*)$", r"<h1>\1</h1>", html_content, flags=re.MULTILINE)
html_content = re.sub(r"^## (.*)$", r"<h2>\1</h2>", html_content, flags=re.MULTILINE)
html_content = html_content.replace("\n", "<br>\n")

html_page = f"""
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>{project_title} — SRS</title>
<style>
body {{
    font-family: Arial, sans-serif;
    margin: 40px;
    line-height: 1.6;
}}
h1 {{
    color: #12355b;
    border-bottom: 2px solid #12355b;
    padding-bottom: 6px;
}}
h2 {{
    color: #1f5f8b;
}}
</style>
</head>
<body>
{html_content}
</body>
</html>
"""

with open(html_path, "w", encoding="utf-8") as f:
    f.write(html_page)

df_generated_sections.to_csv(sections_path, index=False)
df_generated_requirements.to_csv(requirements_path, index=False)

if len(df_rag_references) > 0:
    df_rag_references.to_csv(rag_refs_path, index=False)

generation_summary = f"""
Notebook 5 — Intelligent SRS Generator Summary

Project title:
{project_title}

Prepared by:
{prepared_by}

Generation approach:
- User prompt
- RAG retrieval from previous SRS intelligence outputs
- Instruction-tuned LLM generation
- Section-by-section SRS generation
- Generated requirement extraction
- Requirement quality validation
- Final Markdown and HTML export

Model:
{LLM_MODEL_NAME}

Knowledge base size:
{len(df_generation_kb)}

Generated sections:
{len(df_generated_sections)}

Generated requirements:
{len(df_generated_requirements)}

Generated requirement quality distribution:
{df_generated_requirements["generated_quality_label"].value_counts().to_string() if len(df_generated_requirements) > 0 else "No requirements extracted"}

Saved outputs:
- {markdown_path}
- {html_path}
- {sections_path}
- {requirements_path}
- {rag_refs_path}
"""

with open(summary_path, "w", encoding="utf-8") as f:
    f.write(generation_summary)

print(generation_summary)
print("Saved Markdown:", markdown_path)
print("Saved HTML:", html_path)
print("Saved sections:", sections_path)
print("Saved requirements:", requirements_path)
print("Saved RAG references:", rag_refs_path)
print("Saved summary:", summary_path)

================================================================================
MODULE G13 — EXPORT FINAL SRS OUTPUTS
================================================================================

Notebook 5 — Intelligent SRS Generator Summary

Project title:
Smart University Attendance Management System

Prepared by:
Sarah Boussaidi

Generation approach:
- User prompt
- RAG retrieval from previous SRS intelligence outputs
- Instruction-tuned LLM generation
- Section-by-section SRS generation
- Generated requirement extraction
- Requirement quality validation
- Final Markdown and HTML export

Model:
Qwen/Qwen2.5-1.5B-Instruct

Knowledge base size:
3306

Generated sections:
10

Generated requirements:
144

Generated requirement quality distribution:
generated_quality_label
STRONG_GENERATED_REQUIREMENT        124
ACCEPTABLE_GENERATED_REQUIREMENT     20

Saved outputs:
- /kaggle/working/generated_srs/smart_university_attendance_management_system_srs.md
- /kaggle/working/generated_srs/smart_university_attendance_management_system_srs.html
- /kaggle/working/generated_srs/smart_university_attendance_management_system_generated_sections.csv
- /kaggle/working/generated_srs/smart_university_attendance_management_system_generated_requirements.csv
- /kaggle/working/generated_srs/smart_university_attendance_management_system_rag_references.csv

Saved Markdown: /kaggle/working/generated_srs/smart_university_attendance_management_system_srs.md
Saved HTML: /kaggle/working/generated_srs/smart_university_attendance_management_system_srs.html
Saved sections: /kaggle/working/generated_srs/smart_university_attendance_management_system_generated_sections.csv
Saved requirements: /kaggle/working/generated_srs/smart_university_attendance_management_system_generated_requirements.csv
Saved RAG references: /kaggle/working/generated_srs/smart_university_attendance_management_system_rag_references.csv
Saved summary: /kaggle/working/generated_srs/smart_university_attendance_management_system_generation_summary.txt

In [16]:
# =========================================================
# MODULE G14 — OPTIONAL DOCX EXPORT
# =========================================================

print("=" * 80)
print("MODULE G14 — OPTIONAL DOCX EXPORT")
print("=" * 80)

!pip install -q python-docx

from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

docx_path = OUTPUT_DIR / f"{safe_project_name}_srs.docx"

doc = Document()

# Cover title
title = doc.add_paragraph()
title.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = title.add_run("Software Requirements Specification")
run.bold = True
run.font.size = Pt(22)

subtitle = doc.add_paragraph()
subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = subtitle.add_run(project_title)
run.bold = True
run.font.size = Pt(18)

doc.add_paragraph(f"Prepared by: {prepared_by}")
doc.add_paragraph(f"Generated on: {generation_date}")
doc.add_paragraph("Generation method: LLM + RAG + Quality Validation")

doc.add_page_break()

doc.add_heading("Table of Contents", level=1)
for _, row in df_generated_sections.iterrows():
    doc.add_paragraph(f"{row['section_id']}. {row['section_title']}")

doc.add_page_break()

for _, row in df_generated_sections.iterrows():
    doc.add_heading(f"{row['section_id']}. {row['section_title']}", level=1)
    
    for paragraph in str(row["generated_text"]).split("\n"):
        paragraph = paragraph.strip()
        if paragraph:
            if paragraph.startswith("#"):
                doc.add_heading(paragraph.replace("#", "").strip(), level=2)
            else:
                doc.add_paragraph(paragraph)

doc.add_page_break()
doc.add_heading("References and Data Sources", level=1)

for line in references_section.split("\n"):
    line = line.strip()
    if line:
        if line.startswith("#"):
            doc.add_heading(line.replace("#", "").strip(), level=1)
        else:
            doc.add_paragraph(line)

doc.save(docx_path)

print("Saved DOCX:", docx_path)

================================================================================
MODULE G14 — OPTIONAL DOCX EXPORT
================================================================================
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.0/253.0 kB 3.9 MB/s eta 0:00:00ta 0:00:01
Saved DOCX: /kaggle/working/generated_srs/smart_university_attendance_management_system_srs.docx

In [17]:
# =========================================================
# MODULE G15.0 — MODEL EVALUATION OVERVIEW
# =========================================================

print("=" * 80)
print("MODULE G15.0 — MODEL EVALUATION OVERVIEW")
print("=" * 80)

print("""
Notebook 5 evaluates three components:

1. RAG Retriever Evaluation
   - Measures whether retrieved examples are relevant to each generated section.

2. LLM Generation Evaluation
   - Measures completeness, structure, requirement count, and coverage of SRS sections.

3. Generated Requirement Quality Evaluation
   - Measures clarity, testability, measurability, completeness, and overall quality.

The goal is not only to generate a SRS, but also to prove that the generated SRS is structured, explainable, and quality-controlled.
""")

================================================================================
MODULE G15.0 — MODEL EVALUATION OVERVIEW
================================================================================

Notebook 5 evaluates three components:

1. RAG Retriever Evaluation
   - Measures whether retrieved examples are relevant to each generated section.

2. LLM Generation Evaluation
   - Measures completeness, structure, requirement count, and coverage of SRS sections.

3. Generated Requirement Quality Evaluation
   - Measures clarity, testability, measurability, completeness, and overall quality.

The goal is not only to generate a SRS, but also to prove that the generated SRS is structured, explainable, and quality-controlled.

In [18]:
# =========================================================
# MODULE G15.1 — RAG RETRIEVAL EVALUATION
# =========================================================

print("=" * 80)
print("MODULE G15.1 — RAG RETRIEVAL EVALUATION")
print("=" * 80)

rag_eval_rows = []

for section in SRS_SECTIONS:
    section_id = section["section_id"]
    section_title = section["section_title"]
    
    query = (
        project_info["project_title"] + " " +
        project_info["description"] + " " +
        section_title + " " +
        section["goal"] + " " +
        " ".join(project_info["functional_needs"]) + " " +
        " ".join(project_info["non_functional_needs"])
    )
    
    examples = retrieve_rag_examples(query, top_k=10)
    
    avg_similarity = examples["similarity"].mean()
    max_similarity = examples["similarity"].max()
    min_similarity = examples["similarity"].min()
    
    high_relevance_count = (examples["similarity"] >= 0.20).sum()
    medium_relevance_count = ((examples["similarity"] >= 0.10) & (examples["similarity"] < 0.20)).sum()
    low_relevance_count = (examples["similarity"] < 0.10).sum()
    
    if avg_similarity >= 0.20:
        retrieval_quality = "STRONG_RETRIEVAL"
    elif avg_similarity >= 0.10:
        retrieval_quality = "ACCEPTABLE_RETRIEVAL"
    else:
        retrieval_quality = "WEAK_RETRIEVAL"
    
    rag_eval_rows.append({
        "section_id": section_id,
        "section_title": section_title,
        "retrieved_examples": len(examples),
        "avg_similarity": round(avg_similarity, 4),
        "max_similarity": round(max_similarity, 4),
        "min_similarity": round(min_similarity, 4),
        "high_relevance_count": int(high_relevance_count),
        "medium_relevance_count": int(medium_relevance_count),
        "low_relevance_count": int(low_relevance_count),
        "retrieval_quality": retrieval_quality
    })

df_rag_evaluation = pd.DataFrame(rag_eval_rows)

print("RAG evaluation shape:", df_rag_evaluation.shape)

print("\nRetrieval quality distribution:")
print(df_rag_evaluation["retrieval_quality"].value_counts())

display(df_rag_evaluation)

================================================================================
MODULE G15.1 — RAG RETRIEVAL EVALUATION
================================================================================
RAG evaluation shape: (10, 10)

Retrieval quality distribution:
retrieval_quality
ACCEPTABLE_RETRIEVAL    10
Name: count, dtype: int64

,section_id,section_title,retrieved_examples,avg_similarity,max_similarity,min_similarity,high_relevance_count,medium_relevance_count,low_relevance_count,retrieval_quality
0,1,Introduction,10,0.1113,0.1525,0.0877,0,8,2,ACCEPTABLE_RETRIEVAL
1,2,General Description,10,0.1072,0.1440,0.0845,0,8,2,ACCEPTABLE_RETRIEVAL
2,3,Functional Requirements,10,0.1401,0.1697,0.1035,0,10,0,ACCEPTABLE_RETRIEVAL
3,4,Non-Functional Requirements,10,0.1317,0.2423,0.0873,2,4,4,ACCEPTABLE_RETRIEVAL
4,5,Interface Requirements,10,0.1295,0.1393,0.1199,0,10,0,ACCEPTABLE_RETRIEVAL
5,6,Performance Requirements,10,0.1118,0.1617,0.0967,0,8,2,ACCEPTABLE_RETRIEVAL
6,7,Security Requirements,10,0.1143,0.1367,0.1017,0,10,0,ACCEPTABLE_RETRIEVAL
7,8,Acceptance Criteria,10,0.1092,0.1473,0.0865,0,7,3,ACCEPTABLE_RETRIEVAL
8,9,Risks and Assumptions,10,0.1089,0.1438,0.0926,0,8,2,ACCEPTABLE_RETRIEVAL
9,10,Conclusion,10,0.1102,0.1478,0.0868,0,7,3,ACCEPTABLE_RETRIEVAL

In [19]:
# =========================================================
# MODULE G15.2 — LLM GENERATION STRUCTURE EVALUATION
# =========================================================

print("=" * 80)
print("MODULE G15.2 — LLM GENERATION STRUCTURE EVALUATION")
print("=" * 80)

expected_sections = [
    "Introduction",
    "General Description",
    "Functional Requirements",
    "Non-Functional Requirements",
    "Interface Requirements",
    "Performance Requirements",
    "Security Requirements",
    "Acceptance Criteria",
    "Risks and Assumptions",
    "Conclusion"
]

generation_eval_rows = []

full_generated_text = "\n\n".join(df_generated_sections["generated_text"].astype(str).tolist())

for section_name in expected_sections:
    found = section_name.lower() in final_srs_markdown.lower()
    
    section_row = df_generated_sections[
        df_generated_sections["section_title"].str.lower() == section_name.lower()
    ]
    
    if len(section_row) > 0:
        section_text = section_row.iloc[0]["generated_text"]
        word_count = len(str(section_text).split())
        requirement_count = len(extract_generated_requirements(str(section_text)))
    else:
        word_count = 0
        requirement_count = 0
    
    generation_eval_rows.append({
        "expected_section": section_name,
        "section_found": found,
        "section_word_count": word_count,
        "section_requirement_count": requirement_count
    })

df_generation_structure_eval = pd.DataFrame(generation_eval_rows)

section_coverage = df_generation_structure_eval["section_found"].mean()
total_generated_words = df_generation_structure_eval["section_word_count"].sum()
total_generated_requirements = df_generation_structure_eval["section_requirement_count"].sum()

print("Section coverage:", round(section_coverage, 4))
print("Total generated words:", total_generated_words)
print("Total generated requirements:", total_generated_requirements)

display(df_generation_structure_eval)

================================================================================
MODULE G15.2 — LLM GENERATION STRUCTURE EVALUATION
================================================================================
Section coverage: 1.0
Total generated words: 6929
Total generated requirements: 144

,expected_section,section_found,section_word_count,section_requirement_count
0,Introduction,True,580,0
1,General Description,True,768,18
2,Functional Requirements,True,916,23
3,Non-Functional Requirements,True,271,6
4,Interface Requirements,True,809,11
5,Performance Requirements,True,796,6
6,Security Requirements,True,847,9
7,Acceptance Criteria,True,718,40
8,Risks and Assumptions,True,461,0
9,Conclusion,True,763,31

In [20]:
# =========================================================
# MODULE G15.3 — GENERATED REQUIREMENT QUALITY EVALUATION
# =========================================================

print("=" * 80)
print("MODULE G15.3 — GENERATED REQUIREMENT QUALITY EVALUATION")
print("=" * 80)

if len(df_generated_requirements) == 0:
    raise ValueError("No generated requirements available for evaluation.")

quality_eval_summary = {
    "total_generated_requirements": len(df_generated_requirements),
    "avg_quality_score": round(df_generated_requirements["generated_quality_score"].mean(), 2),
    "avg_clarity_score": round(df_generated_requirements["generated_clarity_score"].mean(), 2),
    "avg_testability_score": round(df_generated_requirements["generated_testability_score"].mean(), 2),
    "avg_measurability_score": round(df_generated_requirements["generated_measurability_score"].mean(), 2),
    "avg_completeness_score": round(df_generated_requirements["generated_completeness_score"].mean(), 2),
    "strong_requirements": int((df_generated_requirements["generated_quality_label"] == "STRONG_GENERATED_REQUIREMENT").sum()),
    "acceptable_requirements": int((df_generated_requirements["generated_quality_label"] == "ACCEPTABLE_GENERATED_REQUIREMENT").sum()),
    "needs_review_requirements": int((df_generated_requirements["generated_quality_label"] == "NEEDS_REVIEW").sum()),
    "weak_requirements": int((df_generated_requirements["generated_quality_label"] == "WEAK_GENERATED_REQUIREMENT").sum()),
    "requirements_with_modal": int(df_generated_requirements["generated_has_modal"].sum()),
    "requirements_with_numeric_or_quality_constraint": int(df_generated_requirements["generated_has_numeric_or_quality_constraint"].sum()),
    "requirements_with_actor_or_system": int(df_generated_requirements["generated_has_actor_or_system"].sum()),
    "requirements_with_vague_terms": int(df_generated_requirements["generated_has_vague_terms"].sum())
}

df_quality_eval_summary = pd.DataFrame([quality_eval_summary])

print("Generated requirement quality evaluation:")
display(df_quality_eval_summary)

print("\nGenerated quality label distribution:")
print(df_generated_requirements["generated_quality_label"].value_counts())

display(df_generated_requirements[
    [
        "section_title",
        "generated_requirement_id",
        "generated_requirement_text",
        "generated_quality_score",
        "generated_quality_label",
        "generated_clarity_score",
        "generated_testability_score",
        "generated_measurability_score",
        "generated_completeness_score"
    ]
].head(50))

================================================================================
MODULE G15.3 — GENERATED REQUIREMENT QUALITY EVALUATION
================================================================================
Generated requirement quality evaluation:

,total_generated_requirements,avg_quality_score,avg_clarity_score,avg_testability_score,avg_measurability_score,avg_completeness_score,strong_requirements,acceptable_requirements,needs_review_requirements,weak_requirements,requirements_with_modal,requirements_with_numeric_or_quality_constraint,requirements_with_actor_or_system,requirements_with_vague_terms
0,144,93.68,95.87,97.36,86.25,95.24,124,20,0,0,144,64,111,19

Generated quality label distribution:
generated_quality_label
STRONG_GENERATED_REQUIREMENT        124
ACCEPTABLE_GENERATED_REQUIREMENT     20
Name: count, dtype: int64

,section_title,generated_requirement_id,generated_requirement_text,generated_quality_score,generated_quality_label,generated_clarity_score,generated_testability_score,generated_measurability_score,generated_completeness_score
0,General Description,GREQ-2-001,Accessibility: The system must be accessible v...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,80,100
1,General Description,GREQ-2-002,Scalability: The system should support high tr...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,80,100
2,General Description,GREQ-2-003,Requirement:** Students must be able to regist...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,100,80
3,General Description,GREQ-2-004,Requirement:** Teachers must be authenticated ...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,80,100
4,General Description,GREQ-2-005,Requirement:** Administrators must be able to ...,90.0,STRONG_GENERATED_REQUIREMENT,100,100,80,80
5,General Description,GREQ-2-006,Requirement:** Teachers must be able to create...,90.0,STRONG_GENERATED_REQUIREMENT,100,100,80,80
6,General Description,GREQ-2-007,Requirement:** Students must be able to check ...,90.0,STRONG_GENERATED_REQUIREMENT,100,100,80,80
7,General Description,GREQ-2-008,Requirement:** Administrators must be able to ...,90.0,STRONG_GENERATED_REQUIREMENT,100,100,80,80
8,General Description,GREQ-2-009,Requirement:** Administrators must have a dedi...,90.0,STRONG_GENERATED_REQUIREMENT,100,100,80,80
9,General Description,GREQ-2-010,Requirement:** All user data must be protected...,100.0,STRONG_GENERATED_REQUIREMENT,100,100,100,100
10,General Description,GREQ-2-011,Requirement:** The system must perform well un...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,80,100
11,General Description,GREQ-2-012,Requirement:** The system must be available 24...,100.0,STRONG_GENERATED_REQUIREMENT,100,100,100,100
12,General Description,GREQ-2-013,Requirement:** The interface must be intuitive...,77.5,ACCEPTABLE_GENERATED_REQUIREMENT,70,80,80,80
13,General Description,GREQ-2-014,Requirement:** The system must function reliab...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,80,100
14,General Description,GREQ-2-015,Requirement:** The system must be easily maint...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,80,100
15,General Description,GREQ-2-016,Note:** The system shall demonstrate a high le...,100.0,STRONG_GENERATED_REQUIREMENT,100,100,100,100
16,General Description,GREQ-2-017,Note:** The system shall comply with the lates...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,80,100
17,General Description,GREQ-2-018,Note:** The system shall support multi-tier au...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,80,100
18,Functional Requirements,GREQ-3-001,Shall** the system provide a secure and effici...,82.5,ACCEPTABLE_GENERATED_REQUIREMENT,70,80,80,100
19,Functional Requirements,GREQ-3-002,Description**: Students shall be able to sign ...,90.0,STRONG_GENERATED_REQUIREMENT,100,100,80,80
20,Functional Requirements,GREQ-3-003,Shall** the system enable teachers to log in s...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,80,100
21,Functional Requirements,GREQ-3-004,Description**: Teachers shall be able to acces...,100.0,STRONG_GENERATED_REQUIREMENT,100,100,100,100
22,Functional Requirements,GREQ-3-005,Shall** the system facilitate the creation and...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,80,100
23,Functional Requirements,GREQ-3-006,Description**: Teachers shall be able to creat...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,80,100
24,Functional Requirements,GREQ-3-007,Shall** the system allow teachers to schedule ...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,80,100
25,Functional Requirements,GREQ-3-008,Description**: Teachers shall be able to creat...,90.0,STRONG_GENERATED_REQUIREMENT,100,100,80,80
26,Functional Requirements,GREQ-3-009,Shall** the system enable students to check in...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,80,100
27,Functional Requirements,GREQ-3-010,Description**: Students shall be able to log i...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,80,100
28,Functional Requirements,GREQ-3-011,Shall** the system generate detailed attendanc...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,80,100
29,Functional Requirements,GREQ-3-012,Description**: The system shall automatically ...,100.0,STRONG_GENERATED_REQUIREMENT,100,100,100,100
30,Functional Requirements,GREQ-3-013,Shall** the system provide an admin dashboard ...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,80,100
31,Functional Requirements,GREQ-3-014,Description**: Administrators shall have acces...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,80,100
32,Functional Requirements,GREQ-3-015,Shall** the system ensure robust security meas...,82.5,ACCEPTABLE_GENERATED_REQUIREMENT,70,80,80,100
33,Functional Requirements,GREQ-3-016,Description**: The system shall implement encr...,100.0,STRONG_GENERATED_REQUIREMENT,100,100,100,100
34,Functional Requirements,GREQ-3-017,Shall** the system maintain acceptable perform...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,80,100
35,Functional Requirements,GREQ-3-018,Description**: The system shall scale well to ...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,80,100
36,Functional Requirements,GREQ-3-019,Shall** the system remain available to users c...,100.0,STRONG_GENERATED_REQUIREMENT,100,100,100,100
37,Functional Requirements,GREQ-3-020,Description**: The system shall operate reliab...,100.0,STRONG_GENERATED_REQUIREMENT,100,100,100,100
38,Functional Requirements,GREQ-3-021,Shall** the system meet usability standards to...,100.0,STRONG_GENERATED_REQUIREMENT,100,100,100,100
39,Functional Requirements,GREQ-3-022,Description**: The system shall be intuitive a...,82.5,ACCEPTABLE_GENERATED_REQUIREMENT,70,80,80,100
40,Functional Requirements,GREQ-3-023,Shall** the system demonstrate reliability and...,82.5,ACCEPTABLE_GENERATED_REQUIREMENT,75,100,80,75
41,Non-Functional Requirements,GREQ-4-001,The system shall ensure secure user authentica...,100.0,STRONG_GENERATED_REQUIREMENT,100,100,100,100
42,Non-Functional Requirements,GREQ-4-002,The system shall be designed to handle concurr...,82.5,ACCEPTABLE_GENERATED_REQUIREMENT,70,80,80,100
43,Non-Functional Requirements,GREQ-4-003,The system shall operate continuously without ...,100.0,STRONG_GENERATED_REQUIREMENT,100,100,100,100
44,Non-Functional Requirements,GREQ-4-004,The user interface shall be intuitive and cons...,82.5,ACCEPTABLE_GENERATED_REQUIREMENT,70,80,80,100
45,Non-Functional Requirements,GREQ-4-005,The system shall exhibit high reliability with...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,80,100
46,Non-Functional Requirements,GREQ-4-006,"The system shall be modular and extensible, fa...",77.5,ACCEPTABLE_GENERATED_REQUIREMENT,70,80,60,100
47,Interface Requirements,GREQ-5-001,Requirement:** The system shall provide an int...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,80,100
48,Interface Requirements,GREQ-5-002,Requirement:** The system shall allow teachers...,100.0,STRONG_GENERATED_REQUIREMENT,100,100,100,100
49,Interface Requirements,GREQ-5-003,Requirement:** The system shall enable adminis...,95.0,STRONG_GENERATED_REQUIREMENT,100,100,80,100

In [21]:
# =========================================================
# MODULE G15.4 — FINAL SRS GENERATION SCORE
# =========================================================

print("=" * 80)
print("MODULE G15.4 — FINAL SRS GENERATION SCORE")
print("=" * 80)

avg_rag_score = df_rag_evaluation["avg_similarity"].mean()
rag_score_scaled = min(100, avg_rag_score * 400)

structure_score = section_coverage * 100

requirement_quality_score = df_generated_requirements["generated_quality_score"].mean()

requirement_count_score = min(100, total_generated_requirements * 5)

vague_penalty = (
    df_generated_requirements["generated_has_vague_terms"].mean() * 20
)

final_generation_score = (
    0.25 * rag_score_scaled +
    0.25 * structure_score +
    0.35 * requirement_quality_score +
    0.15 * requirement_count_score -
    vague_penalty
)

final_generation_score = max(0, min(100, round(final_generation_score, 2)))

if final_generation_score >= 85:
    final_generation_label = "EXCELLENT_GENERATION"
elif final_generation_score >= 70:
    final_generation_label = "GOOD_GENERATION"
elif final_generation_score >= 55:
    final_generation_label = "ACCEPTABLE_GENERATION"
else:
    final_generation_label = "NEEDS_IMPROVEMENT"

df_final_generation_evaluation = pd.DataFrame([{
    "rag_score_scaled": round(rag_score_scaled, 2),
    "structure_score": round(structure_score, 2),
    "requirement_quality_score": round(requirement_quality_score, 2),
    "requirement_count_score": round(requirement_count_score, 2),
    "vague_penalty": round(vague_penalty, 2),
    "final_generation_score": final_generation_score,
    "final_generation_label": final_generation_label
}])

display(df_final_generation_evaluation)

print("Final generation score:", final_generation_score)
print("Final generation label:", final_generation_label)

================================================================================
MODULE G15.4 — FINAL SRS GENERATION SCORE
================================================================================

,rag_score_scaled,structure_score,requirement_quality_score,requirement_count_score,vague_penalty,final_generation_score,final_generation_label
0,46.97,100.0,93.68,100,2.64,81.89,GOOD_GENERATION

Final generation score: 81.89
Final generation label: GOOD_GENERATION

In [22]:
# =========================================================
# MODULE G16.0 — XAI OVERVIEW FOR SRS GENERATION
# =========================================================

print("=" * 80)
print("MODULE G16.0 — XAI OVERVIEW FOR SRS GENERATION")
print("=" * 80)

print("""
This module explains the generated SRS using three XAI layers:

1. RAG Evidence XAI
   Explains which retrieved examples supported each generated SRS section.

2. Requirement Quality XAI
   Explains why each generated requirement received its quality score.

3. Section-Level Generation XAI
   Explains which sections are strong, weak, complete, or under-specified.

For LLM generation, we cannot inspect internal neural weights directly.
Instead, we explain the generation process through:
- retrieved evidence,
- prompt context,
- quality signals,
- validation scores,
- section coverage,
- requirement-level diagnostics.
""")

================================================================================
MODULE G16.0 — XAI OVERVIEW FOR SRS GENERATION
================================================================================

This module explains the generated SRS using three XAI layers:

1. RAG Evidence XAI
   Explains which retrieved examples supported each generated SRS section.

2. Requirement Quality XAI
   Explains why each generated requirement received its quality score.

3. Section-Level Generation XAI
   Explains which sections are strong, weak, complete, or under-specified.

For LLM generation, we cannot inspect internal neural weights directly.
Instead, we explain the generation process through:
- retrieved evidence,
- prompt context,
- quality signals,
- validation scores,
- section coverage,
- requirement-level diagnostics.

In [23]:
# =========================================================
# MODULE G16.1 — RAG EVIDENCE XAI PER GENERATED SECTION
# =========================================================

print("=" * 80)
print("MODULE G16.1 — RAG EVIDENCE XAI PER GENERATED SECTION")
print("=" * 80)

xai_rag_rows = []

for section in SRS_SECTIONS:
    section_id = section["section_id"]
    section_title = section["section_title"]
    
    query = (
        project_info["project_title"] + " " +
        project_info["description"] + " " +
        section_title + " " +
        section["goal"]
    )
    
    examples = retrieve_rag_examples(query, top_k=5)
    
    for rank, (_, ex) in enumerate(examples.iterrows(), start=1):
        xai_rag_rows.append({
            "section_id": section_id,
            "section_title": section_title,
            "evidence_rank": rank,
            "evidence_type": ex.get("kb_type", ""),
            "evidence_requirement_type": ex.get("requirement_type", ""),
            "evidence_section_label": ex.get("section_label", ""),
            "evidence_similarity": round(float(ex.get("similarity", 0)), 4),
            "evidence_text": ex.get("text", "")[:1000],
            "explanation": (
                f"This evidence was retrieved because it is semantically similar "
                f"to the requested section '{section_title}' and project context."
            )
        })

df_rag_xai = pd.DataFrame(xai_rag_rows)

print("RAG XAI evidence shape:", df_rag_xai.shape)

display(df_rag_xai.head(30))

================================================================================
MODULE G16.1 — RAG EVIDENCE XAI PER GENERATED SECTION
================================================================================
RAG XAI evidence shape: (50, 9)

,section_id,section_title,evidence_rank,evidence_type,evidence_requirement_type,evidence_section_label,evidence_similarity,evidence_text,explanation
0,1,Introduction,1,HIGH_QUALITY_REQUIREMENT,FR,functional_requirements,0.1267,5.1.4. Transfer outside university should be a...,This evidence was retrieved because it is sema...
1,1,Introduction,2,HIGH_QUALITY_REQUIREMENT,NFR,appendices,0.1220,1.4 Project Scope According to GAMMA-J's Funct...,This evidence was retrieved because it is sema...
2,1,Introduction,3,HIGH_QUALITY_REQUIREMENT,FR,appendices,0.1167,Generates a parsed target file from a target-p...,This evidence was retrieved because it is sema...
3,1,Introduction,4,HIGH_QUALITY_REQUIREMENT,FR,introduction,0.1146,The system must be able to define and manage v...,This evidence was retrieved because it is sema...
4,1,Introduction,5,HIGH_QUALITY_REQUIREMENT,FR,appendices,0.1127,The C2C project will be implemented using the ...,This evidence was retrieved because it is sema...
5,2,General Description,1,HIGH_QUALITY_REQUIREMENT,UNCERTAIN,appendices,0.1450,The TCS software shall be Defense Information ...,This evidence was retrieved because it is sema...
6,2,General Description,2,HIGH_QUALITY_REQUIREMENT,FR,functional_requirements,0.1211,5.1.4. Transfer outside university should be a...,This evidence was retrieved because it is sema...
7,2,General Description,3,HIGH_QUALITY_REQUIREMENT,FR,functional_requirements,0.1042,or products. The inventory management will all...,This evidence was retrieved because it is sema...
8,2,General Description,4,HIGH_QUALITY_REQUIREMENT,FR,appendices,0.1029,The TCS shall have the functionality necessary...,This evidence was retrieved because it is sema...
9,2,General Description,5,HIGH_QUALITY_REQUIREMENT,FR,introduction,0.1012,The system must be able to define and manage v...,This evidence was retrieved because it is sema...
10,3,Functional Requirements,1,HIGH_QUALITY_REQUIREMENT,FR,introduction,0.2361,Functional requirements specify actions that a...,This evidence was retrieved because it is sema...
11,3,Functional Requirements,2,HIGH_QUALITY_REQUIREMENT,FR,design_constraints,0.2351,Functional requirements specify actions that a...,This evidence was retrieved because it is sema...
12,3,Functional Requirements,3,HIGH_QUALITY_REQUIREMENT,FR,introduction,0.2300,• The authoring tool should allow the function...,This evidence was retrieved because it is sema...
13,3,Functional Requirements,4,HIGH_QUALITY_REQUIREMENT,FR,appendices,0.2237,diagnostic will be enumerated and described un...,This evidence was retrieved because it is sema...
14,3,Functional Requirements,5,HIGH_QUALITY_REQUIREMENT,FR,appendices,0.1698,Functional requirements: A statement of a piec...,This evidence was retrieved because it is sema...
15,4,Non-Functional Requirements,1,HIGH_QUALITY_REQUIREMENT,NFR,introduction,0.1865,"system performance), availability (high availa...",This evidence was retrieved because it is sema...
16,4,Non-Functional Requirements,2,HIGH_QUALITY_REQUIREMENT,NFR,appendices,0.1625,CRS0129 Reliability and Maintainability. The s...,This evidence was retrieved because it is sema...
17,4,Non-Functional Requirements,3,HIGH_QUALITY_REQUIREMENT,NFR,NaN,0.1593,6. Non functional requirements 6.1.Usability I...,This evidence was retrieved because it is sema...
18,4,Non-Functional Requirements,4,HIGH_QUALITY_REQUIREMENT,UNCERTAIN,NaN,0.1382,that will be considered when developing the AP...,This evidence was retrieved because it is sema...
19,4,Non-Functional Requirements,5,HIGH_QUALITY_REQUIREMENT,NFR,appendices,0.1191,1.4 Project Scope According to GAMMA-J's Funct...,This evidence was retrieved because it is sema...
20,5,Interface Requirements,1,HIGH_QUALITY_REQUIREMENT,FR,appendices,0.1911,same document. The actual user interface will ...,This evidence was retrieved because it is sema...
21,5,Interface Requirements,2,HIGH_QUALITY_REQUIREMENT,FR,appendices,0.1804,with TAMPS.[SSS565] The interface requirements...,This evidence was retrieved because it is sema...
22,5,Interface Requirements,3,HIGH_QUALITY_REQUIREMENT,FR,appendices,0.1804,with AFMSS.[SSS564] The interface requirements...,This evidence was retrieved because it is sema...
23,5,Interface Requirements,4,HIGH_QUALITY_REQUIREMENT,FR,appendices,0.1804,with JSIPS-N. [SSS294] The interface requireme...,This evidence was retrieved because it is sema...
24,5,Interface Requirements,5,HIGH_QUALITY_REQUIREMENT,FR,appendices,0.1794,with AFATDS. [SSS295] The interface requiremen...,This evidence was retrieved because it is sema...
25,6,Performance Requirements,1,HIGH_QUALITY_REQUIREMENT,FR,introduction,0.1520,The system must be able to define and manage v...,This evidence was retrieved because it is sema...
26,6,Performance Requirements,2,HIGH_QUALITY_REQUIREMENT,FR,design_constraints,0.1356,The Data Collector Requirements define what mu...,This evidence was retrieved because it is sema...
27,6,Performance Requirements,3,HIGH_QUALITY_REQUIREMENT,FR,introduction,0.1226,"functional or performance requirements, which ...",This evidence was retrieved because it is sema...
28,6,Performance Requirements,4,HIGH_QUALITY_REQUIREMENT,FR,appendices,0.1147,The TCS shall provide the capability to create...,This evidence was retrieved because it is sema...
29,6,Performance Requirements,5,HIGH_QUALITY_REQUIREMENT,FR,functional_requirements,0.1145,5.1.4. Transfer outside university should be a...,This evidence was retrieved because it is sema...

In [24]:
# =========================================================
# MODULE G16.2 — REQUIREMENT QUALITY XAI
# =========================================================

print("=" * 80)
print("MODULE G16.2 — REQUIREMENT QUALITY XAI")
print("=" * 80)

def explain_generated_requirement_quality(row):
    explanations = []
    
    if row["generated_has_modal"]:
        explanations.append("The requirement uses a clear modal verb such as shall, must, or should.")
    else:
        explanations.append("The requirement does not use a clear requirement modal verb.")
    
    if row["generated_has_vague_terms"]:
        explanations.append("The requirement contains vague terms that may reduce clarity.")
    else:
        explanations.append("No major vague term was detected.")
    
    if row["generated_has_numeric_or_quality_constraint"]:
        explanations.append("The requirement contains a numeric or quality constraint, improving measurability.")
    else:
        explanations.append("The requirement may need a measurable threshold or quality constraint.")
    
    if row["generated_has_actor_or_system"]:
        explanations.append("The requirement mentions an actor or system component.")
    else:
        explanations.append("The requirement may need a clearer actor or system component.")
    
    if row["generated_word_count"] < 8:
        explanations.append("The requirement is short and may lack detail.")
    else:
        explanations.append("The requirement has sufficient length for basic interpretation.")
    
    return explanations

df_generated_requirements["xai_quality_explanation"] = df_generated_requirements.apply(
    explain_generated_requirement_quality,
    axis=1
)

display(df_generated_requirements[
    [
        "generated_requirement_id",
        "section_title",
        "generated_requirement_text",
        "generated_quality_score",
        "generated_quality_label",
        "xai_quality_explanation"
    ]
].head(50))

================================================================================
MODULE G16.2 — REQUIREMENT QUALITY XAI
================================================================================

,generated_requirement_id,section_title,generated_requirement_text,generated_quality_score,generated_quality_label,xai_quality_explanation
0,GREQ-2-001,General Description,Accessibility: The system must be accessible v...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
1,GREQ-2-002,General Description,Scalability: The system should support high tr...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
2,GREQ-2-003,General Description,Requirement:** Students must be able to regist...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
3,GREQ-2-004,General Description,Requirement:** Teachers must be authenticated ...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
4,GREQ-2-005,General Description,Requirement:** Administrators must be able to ...,90.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
5,GREQ-2-006,General Description,Requirement:** Teachers must be able to create...,90.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
6,GREQ-2-007,General Description,Requirement:** Students must be able to check ...,90.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
7,GREQ-2-008,General Description,Requirement:** Administrators must be able to ...,90.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
8,GREQ-2-009,General Description,Requirement:** Administrators must have a dedi...,90.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
9,GREQ-2-010,General Description,Requirement:** All user data must be protected...,100.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
10,GREQ-2-011,General Description,Requirement:** The system must perform well un...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
11,GREQ-2-012,General Description,Requirement:** The system must be available 24...,100.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
12,GREQ-2-013,General Description,Requirement:** The interface must be intuitive...,77.5,ACCEPTABLE_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
13,GREQ-2-014,General Description,Requirement:** The system must function reliab...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
14,GREQ-2-015,General Description,Requirement:** The system must be easily maint...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
15,GREQ-2-016,General Description,Note:** The system shall demonstrate a high le...,100.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
16,GREQ-2-017,General Description,Note:** The system shall comply with the lates...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
17,GREQ-2-018,General Description,Note:** The system shall support multi-tier au...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
18,GREQ-3-001,Functional Requirements,Shall** the system provide a secure and effici...,82.5,ACCEPTABLE_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
19,GREQ-3-002,Functional Requirements,Description**: Students shall be able to sign ...,90.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
20,GREQ-3-003,Functional Requirements,Shall** the system enable teachers to log in s...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
21,GREQ-3-004,Functional Requirements,Description**: Teachers shall be able to acces...,100.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
22,GREQ-3-005,Functional Requirements,Shall** the system facilitate the creation and...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
23,GREQ-3-006,Functional Requirements,Description**: Teachers shall be able to creat...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
24,GREQ-3-007,Functional Requirements,Shall** the system allow teachers to schedule ...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
25,GREQ-3-008,Functional Requirements,Description**: Teachers shall be able to creat...,90.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
26,GREQ-3-009,Functional Requirements,Shall** the system enable students to check in...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
27,GREQ-3-010,Functional Requirements,Description**: Students shall be able to log i...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
28,GREQ-3-011,Functional Requirements,Shall** the system generate detailed attendanc...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
29,GREQ-3-012,Functional Requirements,Description**: The system shall automatically ...,100.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
30,GREQ-3-013,Functional Requirements,Shall** the system provide an admin dashboard ...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
31,GREQ-3-014,Functional Requirements,Description**: Administrators shall have acces...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
32,GREQ-3-015,Functional Requirements,Shall** the system ensure robust security meas...,82.5,ACCEPTABLE_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
33,GREQ-3-016,Functional Requirements,Description**: The system shall implement encr...,100.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
34,GREQ-3-017,Functional Requirements,Shall** the system maintain acceptable perform...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
35,GREQ-3-018,Functional Requirements,Description**: The system shall scale well to ...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
36,GREQ-3-019,Functional Requirements,Shall** the system remain available to users c...,100.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
37,GREQ-3-020,Functional Requirements,Description**: The system shall operate reliab...,100.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
38,GREQ-3-021,Functional Requirements,Shall** the system meet usability standards to...,100.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
39,GREQ-3-022,Functional Requirements,Description**: The system shall be intuitive a...,82.5,ACCEPTABLE_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
40,GREQ-3-023,Functional Requirements,Shall** the system demonstrate reliability and...,82.5,ACCEPTABLE_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
41,GREQ-4-001,Non-Functional Requirements,The system shall ensure secure user authentica...,100.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
42,GREQ-4-002,Non-Functional Requirements,The system shall be designed to handle concurr...,82.5,ACCEPTABLE_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
43,GREQ-4-003,Non-Functional Requirements,The system shall operate continuously without ...,100.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
44,GREQ-4-004,Non-Functional Requirements,The user interface shall be intuitive and cons...,82.5,ACCEPTABLE_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
45,GREQ-4-005,Non-Functional Requirements,The system shall exhibit high reliability with...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
46,GREQ-4-006,Non-Functional Requirements,"The system shall be modular and extensible, fa...",77.5,ACCEPTABLE_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
47,GREQ-5-001,Interface Requirements,Requirement:** The system shall provide an int...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
48,GREQ-5-002,Interface Requirements,Requirement:** The system shall allow teachers...,100.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...
49,GREQ-5-003,Interface Requirements,Requirement:** The system shall enable adminis...,95.0,STRONG_GENERATED_REQUIREMENT,[The requirement uses a clear modal verb such ...

In [25]:
# =========================================================
# MODULE G16.3 — SECTION-LEVEL GENERATION XAI
# =========================================================

print("=" * 80)
print("MODULE G16.3 — SECTION-LEVEL GENERATION XAI")
print("=" * 80)

section_xai_rows = []

for _, section in df_generated_sections.iterrows():
    section_id = section["section_id"]
    section_title = section["section_title"]
    section_text = str(section["generated_text"])
    
    section_reqs = df_generated_requirements[
        df_generated_requirements["section_id"] == section_id
    ]
    
    word_count = len(section_text.split())
    req_count = len(section_reqs)
    
    if req_count > 0:
        avg_quality = section_reqs["generated_quality_score"].mean()
        weak_count = (section_reqs["generated_quality_label"] == "WEAK_GENERATED_REQUIREMENT").sum()
        needs_review_count = (section_reqs["generated_quality_label"] == "NEEDS_REVIEW").sum()
    else:
        avg_quality = 0
        weak_count = 0
        needs_review_count = 0
    
    rag_row = df_rag_evaluation[
        df_rag_evaluation["section_id"] == section_id
    ]
    
    if len(rag_row) > 0:
        retrieval_quality = rag_row.iloc[0]["retrieval_quality"]
        avg_similarity = rag_row.iloc[0]["avg_similarity"]
    else:
        retrieval_quality = "UNKNOWN"
        avg_similarity = 0
    
    explanations = []
    
    if word_count < 80:
        explanations.append("The section is relatively short and may need more detail.")
    else:
        explanations.append("The section has sufficient textual content.")
    
    if req_count == 0 and "Requirements" in section_title:
        explanations.append("This requirement section contains no extracted shall/must/should requirement.")
    elif req_count > 0:
        explanations.append(f"This section contains {req_count} generated requirements.")
    
    if avg_quality >= 85:
        explanations.append("Generated requirements in this section are mostly strong.")
    elif avg_quality >= 70:
        explanations.append("Generated requirements in this section are acceptable.")
    elif req_count > 0:
        explanations.append("Some requirements in this section may need review.")
    
    explanations.append(f"RAG retrieval quality for this section is {retrieval_quality}.")
    
    section_xai_rows.append({
        "section_id": section_id,
        "section_title": section_title,
        "section_word_count": word_count,
        "generated_requirement_count": req_count,
        "avg_generated_requirement_quality": round(avg_quality, 2),
        "weak_generated_requirements": int(weak_count),
        "needs_review_generated_requirements": int(needs_review_count),
        "rag_avg_similarity": avg_similarity,
        "rag_retrieval_quality": retrieval_quality,
        "section_xai_explanation": explanations
    })

df_section_generation_xai = pd.DataFrame(section_xai_rows)

display(df_section_generation_xai)

================================================================================
MODULE G16.3 — SECTION-LEVEL GENERATION XAI
================================================================================

,section_id,section_title,section_word_count,generated_requirement_count,avg_generated_requirement_quality,weak_generated_requirements,needs_review_generated_requirements,rag_avg_similarity,rag_retrieval_quality,section_xai_explanation
0,1,Introduction,580,0,0.00,0,0,0.1113,ACCEPTABLE_RETRIEVAL,"[The section has sufficient textual content., ..."
1,2,General Description,768,18,93.47,0,0,0.1072,ACCEPTABLE_RETRIEVAL,"[The section has sufficient textual content., ..."
2,3,Functional Requirements,916,23,93.70,0,0,0.1401,ACCEPTABLE_RETRIEVAL,"[The section has sufficient textual content., ..."
3,4,Non-Functional Requirements,271,6,89.58,0,0,0.1317,ACCEPTABLE_RETRIEVAL,"[The section has sufficient textual content., ..."
4,5,Interface Requirements,809,11,94.55,0,0,0.1295,ACCEPTABLE_RETRIEVAL,"[The section has sufficient textual content., ..."
5,6,Performance Requirements,796,6,95.42,0,0,0.1118,ACCEPTABLE_RETRIEVAL,"[The section has sufficient textual content., ..."
6,7,Security Requirements,847,9,94.44,0,0,0.1143,ACCEPTABLE_RETRIEVAL,"[The section has sufficient textual content., ..."
7,8,Acceptance Criteria,718,40,91.69,0,0,0.1092,ACCEPTABLE_RETRIEVAL,"[The section has sufficient textual content., ..."
8,9,Risks and Assumptions,461,0,0.00,0,0,0.1089,ACCEPTABLE_RETRIEVAL,"[The section has sufficient textual content., ..."
9,10,Conclusion,763,31,96.29,0,0,0.1102,ACCEPTABLE_RETRIEVAL,"[The section has sufficient textual content., ..."

In [26]:
# =========================================================
# MODULE G16.4 — GLOBAL XAI REPORT
# =========================================================

print("=" * 80)
print("MODULE G16.4 — GLOBAL XAI REPORT")
print("=" * 80)

global_xai_report = f"""
# XAI Report — Intelligent SRS Generation

## 1. Generation Strategy

The SRS was generated using an instruction-tuned LLM supported by RAG.

The user provided:
- Project title: {project_info["project_title"]}
- Prepared by: {project_info["prepared_by"]}
- Project description: {project_info["description"]}
- Functional needs: {project_info["functional_needs"]}
- Non-functional needs: {project_info["non_functional_needs"]}

## 2. RAG Explanation

The RAG engine retrieved examples from previous SRS intelligence outputs:
- High-quality requirements
- Improved requirements from LLM rewriting
- Requirements scored by multimodal quality analysis

Average RAG similarity score:
{round(df_rag_evaluation["avg_similarity"].mean(), 4)}

RAG quality distribution:
{df_rag_evaluation["retrieval_quality"].value_counts().to_string()}

## 3. Generation Evaluation

Section coverage:
{round(section_coverage * 100, 2)}%

Total generated requirements:
{total_generated_requirements}

Average generated requirement quality:
{round(df_generated_requirements["generated_quality_score"].mean(), 2)}

Generated requirement quality distribution:
{df_generated_requirements["generated_quality_label"].value_counts().to_string()}

## 4. Final Generation Score

Final generation score:
{final_generation_score}

Final generation label:
{final_generation_label}

## 5. Explainability Summary

The generated SRS is explainable through:
1. RAG evidence per section.
2. Quality explanations per generated requirement.
3. Section-level diagnostics.
4. Final generation score decomposition.

This provides transparency over why the generated SRS is considered strong, acceptable, or needing improvement.
"""

print(global_xai_report)

================================================================================
MODULE G16.4 — GLOBAL XAI REPORT
================================================================================

# XAI Report — Intelligent SRS Generation

## 1. Generation Strategy

The SRS was generated using an instruction-tuned LLM supported by RAG.

The user provided:
- Project title: Smart University Attendance Management System
- Prepared by: Sarah Boussaidi
- Project description: The system helps universities manage student attendance using a web and mobile platform. Teachers can create sessions, students can check in, administrators can manage courses, and the system generates attendance reports.
- Functional needs: ['Student registration and authentication', 'Teacher authentication', 'Course and class management', 'Attendance session creation', 'Student check-in', 'Attendance report generation', 'Admin dashboard']
- Non-functional needs: ['Security', 'Performance', 'Availability', 'Usability', 'Reliability', 'Maintainability']

## 2. RAG Explanation

The RAG engine retrieved examples from previous SRS intelligence outputs:
- High-quality requirements
- Improved requirements from LLM rewriting
- Requirements scored by multimodal quality analysis

Average RAG similarity score:
0.1174

RAG quality distribution:
retrieval_quality
ACCEPTABLE_RETRIEVAL    10

## 3. Generation Evaluation

Section coverage:
100.0%

Total generated requirements:
144

Average generated requirement quality:
93.68

Generated requirement quality distribution:
generated_quality_label
STRONG_GENERATED_REQUIREMENT        124
ACCEPTABLE_GENERATED_REQUIREMENT     20

## 4. Final Generation Score

Final generation score:
81.89

Final generation label:
GOOD_GENERATION

## 5. Explainability Summary

The generated SRS is explainable through:
1. RAG evidence per section.
2. Quality explanations per generated requirement.
3. Section-level diagnostics.
4. Final generation score decomposition.

This provides transparency over why the generated SRS is considered strong, acceptable, or needing improvement.

In [27]:
# =========================================================
# MODULE G17 — SAVE EVALUATION AND XAI OUTPUTS
# =========================================================

print("=" * 80)
print("MODULE G17 — SAVE EVALUATION AND XAI OUTPUTS")
print("=" * 80)

eval_xai_dir = OUTPUT_DIR / "evaluation_xai"
eval_xai_dir.mkdir(parents=True, exist_ok=True)

rag_eval_path = eval_xai_dir / f"{safe_project_name}_rag_evaluation.csv"
generation_structure_eval_path = eval_xai_dir / f"{safe_project_name}_generation_structure_evaluation.csv"
quality_eval_summary_path = eval_xai_dir / f"{safe_project_name}_requirement_quality_evaluation.csv"
final_generation_eval_path = eval_xai_dir / f"{safe_project_name}_final_generation_score.csv"
rag_xai_path = eval_xai_dir / f"{safe_project_name}_rag_xai_evidence.csv"
requirement_xai_path = eval_xai_dir / f"{safe_project_name}_requirement_quality_xai.csv"
section_xai_path = eval_xai_dir / f"{safe_project_name}_section_generation_xai.csv"
global_xai_report_path = eval_xai_dir / f"{safe_project_name}_global_xai_report.md"

df_rag_evaluation.to_csv(rag_eval_path, index=False)
df_generation_structure_eval.to_csv(generation_structure_eval_path, index=False)
df_quality_eval_summary.to_csv(quality_eval_summary_path, index=False)
df_final_generation_evaluation.to_csv(final_generation_eval_path, index=False)
df_rag_xai.to_csv(rag_xai_path, index=False)
df_generated_requirements.to_csv(requirement_xai_path, index=False)
df_section_generation_xai.to_csv(section_xai_path, index=False)

with open(global_xai_report_path, "w", encoding="utf-8") as f:
    f.write(global_xai_report)

df_eval_xai_manifest = pd.DataFrame([
    {"output_name": "rag_evaluation", "path": str(rag_eval_path)},
    {"output_name": "generation_structure_evaluation", "path": str(generation_structure_eval_path)},
    {"output_name": "requirement_quality_evaluation", "path": str(quality_eval_summary_path)},
    {"output_name": "final_generation_score", "path": str(final_generation_eval_path)},
    {"output_name": "rag_xai_evidence", "path": str(rag_xai_path)},
    {"output_name": "requirement_quality_xai", "path": str(requirement_xai_path)},
    {"output_name": "section_generation_xai", "path": str(section_xai_path)},
    {"output_name": "global_xai_report", "path": str(global_xai_report_path)}
])

eval_xai_manifest_path = eval_xai_dir / f"{safe_project_name}_evaluation_xai_manifest.csv"
df_eval_xai_manifest.to_csv(eval_xai_manifest_path, index=False)

display(df_eval_xai_manifest)

print("Saved evaluation and XAI outputs in:", eval_xai_dir)
print("Saved manifest:", eval_xai_manifest_path)

================================================================================
MODULE G17 — SAVE EVALUATION AND XAI OUTPUTS
================================================================================

,output_name,path
0,rag_evaluation,/kaggle/working/generated_srs/evaluation_xai/s...
1,generation_structure_evaluation,/kaggle/working/generated_srs/evaluation_xai/s...
2,requirement_quality_evaluation,/kaggle/working/generated_srs/evaluation_xai/s...
3,final_generation_score,/kaggle/working/generated_srs/evaluation_xai/s...
4,rag_xai_evidence,/kaggle/working/generated_srs/evaluation_xai/s...
5,requirement_quality_xai,/kaggle/working/generated_srs/evaluation_xai/s...
6,section_generation_xai,/kaggle/working/generated_srs/evaluation_xai/s...
7,global_xai_report,/kaggle/working/generated_srs/evaluation_xai/s...

Saved evaluation and XAI outputs in: /kaggle/working/generated_srs/evaluation_xai
Saved manifest: /kaggle/working/generated_srs/evaluation_xai/smart_university_attendance_management_system_evaluation_xai_manifest.csv

In [28]:
import shutil
from pathlib import Path

output_dir = Path("/kaggle/working/generated_srs")
zip_path = "/kaggle/working/srs_generation_deployment_package"

shutil.make_archive(
    base_name=zip_path,
    format="zip",
    root_dir=output_dir
)

print("Saved ZIP:", zip_path + ".zip")

Saved ZIP: /kaggle/working/srs_generation_deployment_package.zip

In [29]:
# =========================================================
# MODULE G18.0 — LOAD GENERATED SRS OUTPUTS
# =========================================================

from pathlib import Path
import re
import os
import json
import pandas as pd
import numpy as np

print("=" * 80)
print("MODULE G18.0 — LOAD GENERATED SRS OUTPUTS")
print("=" * 80)

GENERATED_DIR = Path("/kaggle/working/generated_srs")

if not GENERATED_DIR.exists():
    raise FileNotFoundError("Generated SRS directory not found: /kaggle/working/generated_srs")

# Find generated markdown SRS
md_files = list(GENERATED_DIR.glob("*_srs.md"))

if len(md_files) == 0:
    raise FileNotFoundError("No generated SRS markdown file found in /kaggle/working/generated_srs")

generated_srs_md_path = md_files[0]

print("Selected generated SRS Markdown:")
print(generated_srs_md_path)

with open(generated_srs_md_path, "r", encoding="utf-8") as f:
    generated_srs_text = f.read()

print("\nGenerated SRS length:", len(generated_srs_text))
print("\nPreview:")
print(generated_srs_text[:2000])

================================================================================
MODULE G18.0 — LOAD GENERATED SRS OUTPUTS
================================================================================
Selected generated SRS Markdown:
/kaggle/working/generated_srs/smart_university_attendance_management_system_srs.md

Generated SRS length: 53720

Preview:

# Software Requirements Specification

## Smart University Attendance Management System

**Prepared by:** Sarah Boussaidi
**Generated on:** 2026-05-10 21:35
**Generation method:** LLM + RAG + Quality Validation
**Knowledge base:** Previous SRS requirements analyzed by NLP, Computer Vision, XAI, and quality scoring

---

# Table of Contents

1. Introduction
2. General Description
3. Functional Requirements
4. Non-Functional Requirements
5. Interface Requirements
6. Performance Requirements
7. Security Requirements
8. Acceptance Criteria
9. Risks and Assumptions
10. Conclusion

---


# 1. Introduction

# 1. Introduction

## 1.1 Purpose
The Smart University Attendance Management System aims to enhance university operations by providing a comprehensive solution for managing student attendance, course scheduling, and administrative tasks. This system integrates seamlessly into existing university infrastructures, ensuring accessibility through web browsers while maintaining high levels of security, performance, and usability.

## 1.2 Scope
This document outlines the functional and non-functional requirements for the Smart University Attendance Management System. It covers key functionalities such as student registration and authentication, teacher authentication, course and class management, attendance session creation, student check-in, attendance report generation, and admin dashboard. Additionally, it addresses security, performance, availability, usability, reliability, and maintainability constraints.

## 1.3 Target Users
- **Students**: Users who need to register, check in, and view their attendance records.
- **Teachers**: Administrators responsible for creating sessions, managing courses, and overseeing student attendance.
- **Administrators**: Managers tasked with course administration, reporting, and system maintenance.

## 1.4 Project Scope
According to GAMMA-J's Functional Needs Statement, the Web Store will manage customer accounts, implement an onlin

In [30]:
# =========================================================
# MODULE G18.1 — STRICT SRS QUALITY DIAGNOSTICS
# =========================================================

print("=" * 80)
print("MODULE G18.1 — STRICT SRS QUALITY DIAGNOSTICS")
print("=" * 80)

OFF_TOPIC_TERMS = [
    "gamma-j",
    "web store",
    "shopping cart",
    "shopping carts",
    "online store",
    "inventory",
    "customer accounts",
    "orders",
    "confirm orders",
    "plug-ins",
    "payment gateway",
    "products",
    "merchant",
    "store inventory"
]

PLACEHOLDER_PATTERNS = [
    r"\[SPECIFY[^\]]*\]",
    r"\[INSERT[^\]]*\]",
    r"\[DEFINE[^\]]*\]",
    r"\[TBD[^\]]*\]",
    r"\bTBD\b",
    r"\bTODO\b"
]

EXPECTED_SECTIONS = [
    "Introduction",
    "General Description",
    "Functional Requirements",
    "Non-Functional Requirements",
    "Interface Requirements",
    "Performance Requirements",
    "Security Requirements",
    "Acceptance Criteria",
    "Risks and Assumptions",
    "Conclusion"
]


def count_off_topic_terms(text):
    text_low = text.lower()
    counts = {}
    for term in OFF_TOPIC_TERMS:
        c = text_low.count(term.lower())
        if c > 0:
            counts[term] = c
    return counts


def find_placeholders(text):
    matches = []
    for pattern in PLACEHOLDER_PATTERNS:
        matches.extend(re.findall(pattern, text, flags=re.IGNORECASE))
    return matches


def detect_duplicate_headings(text):
    heading_lines = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            clean = re.sub(r"^#+\s*", "", stripped).strip()
            clean = re.sub(r"^\d+(\.\d+)*\s*", "", clean).strip()
            heading_lines.append(clean.lower())
    
    heading_counts = pd.Series(heading_lines).value_counts()
    duplicates = heading_counts[heading_counts > 1].to_dict()
    return duplicates


def detect_expected_sections(text):
    found = {}
    text_low = text.lower()
    for sec in EXPECTED_SECTIONS:
        found[sec] = sec.lower() in text_low
    return found


def detect_incomplete_lines(text):
    incomplete = []
    lines = text.splitlines()
    
    for i, line in enumerate(lines):
        stripped = line.strip()
        
        if len(stripped) == 0:
            continue
        
        # suspicious endings
        if stripped.endswith(("The system", "Documentation", "Expected Result:", "- **", "**")):
            incomplete.append({
                "line_number": i + 1,
                "line": stripped
            })
        
        # very short heading-like unfinished line
        if stripped.lower() in ["documentation", "description", "expected result:"]:
            incomplete.append({
                "line_number": i + 1,
                "line": stripped
            })
    
    return incomplete


off_topic_counts = count_off_topic_terms(generated_srs_text)
placeholders = find_placeholders(generated_srs_text)
duplicate_headings = detect_duplicate_headings(generated_srs_text)
section_presence = detect_expected_sections(generated_srs_text)
incomplete_lines = detect_incomplete_lines(generated_srs_text)

diagnostics = {
    "off_topic_counts": off_topic_counts,
    "num_off_topic_terms": sum(off_topic_counts.values()),
    "placeholders": placeholders,
    "num_placeholders": len(placeholders),
    "duplicate_headings": duplicate_headings,
    "num_duplicate_heading_types": len(duplicate_headings),
    "section_presence": section_presence,
    "missing_sections": [k for k, v in section_presence.items() if not v],
    "num_incomplete_lines": len(incomplete_lines),
    "incomplete_lines": incomplete_lines[:20]
}

print("SRS QUALITY DIAGNOSTICS")
print(json.dumps(diagnostics, indent=2))

diagnostics_path = GENERATED_DIR / "g18_strict_srs_diagnostics.json"

with open(diagnostics_path, "w", encoding="utf-8") as f:
    json.dump(diagnostics, f, indent=2)

print("\nSaved diagnostics:", diagnostics_path)

================================================================================
MODULE G18.1 — STRICT SRS QUALITY DIAGNOSTICS
================================================================================
SRS QUALITY DIAGNOSTICS
{
  "off_topic_counts": {
    "gamma-j": 1,
    "web store": 1,
    "shopping cart": 1,
    "shopping carts": 1,
    "online store": 1,
    "inventory": 2,
    "customer accounts": 1,
    "orders": 1,
    "confirm orders": 1,
    "plug-ins": 2,
    "payment gateway": 1,
    "store inventory": 1
  },
  "num_off_topic_terms": 14,
  "placeholders": [
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY NUMBER]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY THRESHOLD]",
    "[SPECIFY USER ROLE]",
    "[SPECIFY USER ROLE]",
    "[SPECIFY USER ROLE]",
    "[SPECIFY USER ROLE]",
    "[SPECIFY USER ROLE]",
    "[SPECIFY USER ROLE]",
    "[SPECIFY USER ROLE]",
    "[SPECIFY USER ROLE]",
    "[SPECIFY USER ROLE]",
    "[SPECIFY USER ROLE]",
    "[SPECIFY USER ROLE]",
    "[SPECIFY USER ROLE]",
    "[SPECIFY USER ROLE]",
    "[SPECIFY USER ROLE]",
    "[SPECIFY SECURITY REQUIREMENT]",
    "[SPECIFY SECURITY REQUIREMENT]",
    "[SPECIFY PERFORMANCE REQUIREMENT]",
    "[SPECIFY PERFORMANCE REQUIREMENT]",
    "[SPECIFY AVAILABILITY REQUIREMENT]",
    "[SPECIFY AVAILABILITY REQUIREMENT]",
    "[SPECIFY USABILITY REQUIREMENT]",
    "[SPECIFY USABILITY REQUIREMENT]",
    "[SPECIFY RELIABILITY REQUIREMENT]",
    "[SPECIFY RELIABILITY REQUIREMENT]",
    "[SPECIFY MAINTAINABILITY REQUIREMENT]",
    "[SPECIFY MAINTAINABILITY REQUIREMENT]",
    "[SPECIFY IMPROVEMENT]",
    "[SPECIFY ENHANCEMENT]",
    "[SPECIFY REFINEMENT]",
    "[SPECIFY CLARIFICATION]",
    "[SPECIFY DEFINITION]"
  ],
  "num_placeholders": 83,
  "duplicate_headings": {
    "availability": 8,
    "security": 8,
    "usability": 7,
    "performance": 7,
    "reliability": 6,
    "test cases": 6,
    "student registration and authentication": 5,
    "teacher authentication": 5,
    "course and class management": 5,
    "attendance session creation": 5,
    "attendance report generation": 5,
    "student check-in": 5,
    "admin dashboard": 5,
    "maintainability": 5,
    "non-functional requirements": 4,
    "assumptions": 2,
    ". general description": 2,
    "introduction": 2,
    ". introduction": 2,
    ". non-functional requirements": 2,
    "requirement improvement": 2,
    "functional requirements": 2,
    ". functional requirements": 2,
    ". conclusion": 2,
    ". acceptance criteria": 2,
    ". performance requirements": 2
  },
  "num_duplicate_heading_types": 26,
  "section_presence": {
    "Introduction": true,
    "General Description": true,
    "Functional Requirements": true,
    "Non-Functional Requirements": true,
    "Interface Requirements": true,
    "Performance Requirements": true,
    "Security Requirements": true,
    "Acceptance Criteria": true,
    "Risks and Assumptions": true,
    "Conclusion": true
  },
  "missing_sections": [],
  "num_incomplete_lines": 50,
  "incomplete_lines": [
    {
      "line_number": 115,
      "line": "**Test Case:**"
    },
    {
      "line_number": 122,
      "line": "**Test Case:**"
    },
    {
      "line_number": 129,
      "line": "**Test Case:**"
    },
    {
      "line_number": 136,
      "line": "**Test Case:**"
    },
    {
      "line_number": 143,
      "line": "**Test Case:**"
    },
    {
      "line_number": 150,
      "line": "**Test Case:**"
    },
    {
      "line_number": 157,
      "line": "**Test Case:**"
    },
    {
      "line_number": 166,
      "line": "**Test Case:**"
    },
    {
      "line_number": 173,
      "line": "**Test Case:**"
    },
    {
      "line_number": 180,
      "line": "**Test Case:**"
    },
    {
      "line_number": 187,
      "line": "**Test Case:**"
    },
    {
      "line_number": 194,
      "line": "**Test Case:**"
    },
    {
      "line_number": 201,
      "line": "**Test Case:**"
    },
    {
      "line_number": 373,
      "line": "- **Description**: The system"
    },
    {
      "line_number": 416,
      "line": "**Test Cases:**"
    },
    {
      "line_number": 428,
      "line": "**Test Cases:**"
    },
    {
      "line_number": 440,
      "line": "**Test Cases:**"
    },
    {
      "line_number": 452,
      "line": "**Test Cases:**"
    },
    {
      "line_number": 464,
      "line": "**Test Cases:**"
    },
    {
      "line_number": 476,
      "line": "**Test Cases:**"
    }
  ]
}

Saved diagnostics: /kaggle/working/generated_srs/g18_strict_srs_diagnostics.json

In [31]:
# =========================================================
# MODULE G18.2 — CLEAN DUPLICATED HEADINGS
# =========================================================

print("=" * 80)
print("MODULE G18.2 — CLEAN DUPLICATED HEADINGS")
print("=" * 80)

def normalize_heading_key(line):
    clean = line.strip()
    clean = re.sub(r"^#+\s*", "", clean)
    clean = re.sub(r"^\d+(\.\d+)*\s*", "", clean)
    clean = clean.strip().lower()
    return clean


def clean_duplicate_headings(text):
    lines = text.splitlines()
    cleaned_lines = []
    seen_heading_keys = set()
    
    previous_heading_key = None
    
    for line in lines:
        stripped = line.strip()
        
        if stripped.startswith("#"):
            key = normalize_heading_key(stripped)
            
            # Remove immediate duplicate heading only
            if key == previous_heading_key:
                continue
            
            previous_heading_key = key
            cleaned_lines.append(line)
        else:
            previous_heading_key = None
            cleaned_lines.append(line)
    
    return "\n".join(cleaned_lines)


srs_clean_step1 = clean_duplicate_headings(generated_srs_text)

print("Original length:", len(generated_srs_text))
print("After duplicate heading cleaning:", len(srs_clean_step1))

print("\nPreview:")
print(srs_clean_step1[:2000])

================================================================================
MODULE G18.2 — CLEAN DUPLICATED HEADINGS
================================================================================
Original length: 53720
After duplicate heading cleaning: 53719

Preview:

# Software Requirements Specification

## Smart University Attendance Management System

**Prepared by:** Sarah Boussaidi
**Generated on:** 2026-05-10 21:35
**Generation method:** LLM + RAG + Quality Validation
**Knowledge base:** Previous SRS requirements analyzed by NLP, Computer Vision, XAI, and quality scoring

---

# Table of Contents

1. Introduction
2. General Description
3. Functional Requirements
4. Non-Functional Requirements
5. Interface Requirements
6. Performance Requirements
7. Security Requirements
8. Acceptance Criteria
9. Risks and Assumptions
10. Conclusion

---


# 1. Introduction

# 1. Introduction

## 1.1 Purpose
The Smart University Attendance Management System aims to enhance university operations by providing a comprehensive solution for managing student attendance, course scheduling, and administrative tasks. This system integrates seamlessly into existing university infrastructures, ensuring accessibility through web browsers while maintaining high levels of security, performance, and usability.

## 1.2 Scope
This document outlines the functional and non-functional requirements for the Smart University Attendance Management System. It covers key functionalities such as student registration and authentication, teacher authentication, course and class management, attendance session creation, student check-in, attendance report generation, and admin dashboard. Additionally, it addresses security, performance, availability, usability, reliability, and maintainability constraints.

## 1.3 Target Users
- **Students**: Users who need to register, check in, and view their attendance records.
- **Teachers**: Administrators responsible for creating sessions, managing courses, and overseeing student attendance.
- **Administrators**: Managers tasked with course administration, reporting, and system maintenance.

## 1.4 Project Scope
According to GAMMA-J's Functional Needs Statement, the Web Store will manage customer accounts, implement an onlin

In [32]:
# =========================================================
# MODULE G18.3 — REMOVE OFF-TOPIC CONTAMINATED PARAGRAPHS
# =========================================================

print("=" * 80)
print("MODULE G18.3 — REMOVE OFF-TOPIC CONTAMINATED PARAGRAPHS")
print("=" * 80)

def paragraph_is_off_topic(paragraph):
    p = paragraph.lower()
    return any(term.lower() in p for term in OFF_TOPIC_TERMS)


def remove_off_topic_paragraphs(text):
    # Split by blank lines
    paragraphs = re.split(r"\n\s*\n", text)
    
    kept = []
    removed = []
    
    for para in paragraphs:
        if paragraph_is_off_topic(para):
            removed.append(para)
        else:
            kept.append(para)
    
    return "\n\n".join(kept), removed


srs_clean_step2, removed_off_topic_paragraphs = remove_off_topic_paragraphs(srs_clean_step1)

print("Removed off-topic paragraphs:", len(removed_off_topic_paragraphs))

for i, para in enumerate(removed_off_topic_paragraphs[:5], start=1):
    print("\n--- Removed paragraph", i, "---")
    print(para[:800])

removed_path = GENERATED_DIR / "g18_removed_off_topic_paragraphs.txt"

with open(removed_path, "w", encoding="utf-8") as f:
    for i, para in enumerate(removed_off_topic_paragraphs, start=1):
        f.write(f"\n\n--- Removed paragraph {i} ---\n")
        f.write(para)

print("\nSaved removed paragraphs:", removed_path)

================================================================================
MODULE G18.3 — REMOVE OFF-TOPIC CONTAMINATED PARAGRAPHS
================================================================================
Removed off-topic paragraphs: 2

--- Removed paragraph 1 ---
## 1.4 Project Scope
According to GAMMA-J's Functional Needs Statement, the Web Store will manage customer accounts, implement an online store inventory, handle shopping carts, confirm orders, ensure secure socket layer (SSL) security, guarantee high availability, offer an optional mirror site for reliability and backups, and provide an interface for future software enhancements via "Plug-ins." The initial inventory will consist of 100 items, expandable up to 20,000 items, and be available without requiring any software installations. The system will also feature advanced capabilities that can be added in the future via "Plug-ins."

--- Removed paragraph 2 ---
### External Systems
Dependencies on external systems such as payment gateways, email services, and social media platforms may affect the system's performance and availability.

Saved removed paragraphs: /kaggle/working/generated_srs/g18_removed_off_topic_paragraphs.txt

In [33]:
# =========================================================
# MODULE G18.4 — CLEAN PLACEHOLDERS
# =========================================================

print("=" * 80)
print("MODULE G18.4 — CLEAN PLACEHOLDERS")
print("=" * 80)

def clean_placeholders(text):
    replacements = {
        r"\[SPECIFY THRESHOLD\]": "a stakeholder-defined threshold",
        r"\[SPECIFY NUMBER\]": "a stakeholder-defined number of users",
        r"\[SPECIFY USER ROLE\]": "Authorized users",
        r"\[SPECIFY SECURITY REQUIREMENT\]": "Security requirement",
        r"\[SPECIFY PERFORMANCE REQUIREMENT\]": "Performance requirement",
        r"\[SPECIFY AVAILABILITY REQUIREMENT\]": "Availability requirement",
        r"\[SPECIFY USABILITY REQUIREMENT\]": "Usability requirement",
        r"\[SPECIFY RELIABILITY REQUIREMENT\]": "Reliability requirement",
    }
    
    cleaned = text
    
    for pattern, replacement in replacements.items():
        cleaned = re.sub(pattern, replacement, cleaned, flags=re.IGNORECASE)
    
    # Generic fallback
    cleaned = re.sub(
        r"\[SPECIFY[^\]]*\]",
        "a stakeholder-defined value",
        cleaned,
        flags=re.IGNORECASE
    )
    
    return cleaned


srs_clean_step3 = clean_placeholders(srs_clean_step2)

remaining_placeholders = find_placeholders(srs_clean_step3)

print("Remaining placeholders:", len(remaining_placeholders))
print(remaining_placeholders[:20])

================================================================================
MODULE G18.4 — CLEAN PLACEHOLDERS
================================================================================
Remaining placeholders: 0
[]

In [34]:
# =========================================================
# MODULE G18.5 — ADD PROFESSIONAL QUALITY NOTE
# =========================================================

print("=" * 80)
print("MODULE G18.5 — ADD PROFESSIONAL QUALITY NOTE")
print("=" * 80)

quality_note = """
---

# Requirements Validation Note

This SRS was generated using an AI-assisted pipeline based on user-provided project information, RAG retrieval, requirement quality scoring, and explainability diagnostics.

The generated requirements should be reviewed by stakeholders before implementation. In particular, performance thresholds, availability targets, security policies, and acceptance criteria must be validated with the project owner, technical team, and end users.

---
"""

def add_quality_note_before_conclusion(text):
    conclusion_match = re.search(r"\n#\s*10\.\s*Conclusion", text, flags=re.IGNORECASE)
    
    if conclusion_match:
        idx = conclusion_match.start()
        return text[:idx] + "\n\n" + quality_note + "\n\n" + text[idx:]
    else:
        return text + "\n\n" + quality_note


srs_clean_step4 = add_quality_note_before_conclusion(srs_clean_step3)

print("Cleaned SRS length:", len(srs_clean_step4))
print("\nPreview:")
print(srs_clean_step4[:2000])

================================================================================
MODULE G18.5 — ADD PROFESSIONAL QUALITY NOTE
================================================================================
Cleaned SRS length: 53867

Preview:

# Software Requirements Specification

## Smart University Attendance Management System

**Prepared by:** Sarah Boussaidi
**Generated on:** 2026-05-10 21:35
**Generation method:** LLM + RAG + Quality Validation
**Knowledge base:** Previous SRS requirements analyzed by NLP, Computer Vision, XAI, and quality scoring

---

# Table of Contents

1. Introduction
2. General Description
3. Functional Requirements
4. Non-Functional Requirements
5. Interface Requirements
6. Performance Requirements
7. Security Requirements
8. Acceptance Criteria
9. Risks and Assumptions
10. Conclusion

---

# 1. Introduction

# 1. Introduction

## 1.1 Purpose
The Smart University Attendance Management System aims to enhance university operations by providing a comprehensive solution for managing student attendance, course scheduling, and administrative tasks. This system integrates seamlessly into existing university infrastructures, ensuring accessibility through web browsers while maintaining high levels of security, performance, and usability.

## 1.2 Scope
This document outlines the functional and non-functional requirements for the Smart University Attendance Management System. It covers key functionalities such as student registration and authentication, teacher authentication, course and class management, attendance session creation, student check-in, attendance report generation, and admin dashboard. Additionally, it addresses security, performance, availability, usability, reliability, and maintainability constraints.

## 1.3 Target Users
- **Students**: Users who need to register, check in, and view their attendance records.
- **Teachers**: Administrators responsible for creating sessions, managing courses, and overseeing student attendance.
- **Administrators**: Managers tasked with course administration, reporting, and system maintenance.

---

### 1.5 Non-Functional Requirements

#### 1.5.1 Security
- **Authentication**: Implement robust multi-factor authentication mechani

In [35]:
# =========================================================
# MODULE G18.6 — FINAL STRICT QUALITY SCORE
# =========================================================

print("=" * 80)
print("MODULE G18.6 — FINAL STRICT QUALITY SCORE")
print("=" * 80)

final_off_topic_counts = count_off_topic_terms(srs_clean_step4)
final_placeholders = find_placeholders(srs_clean_step4)
final_duplicate_headings = detect_duplicate_headings(srs_clean_step4)
final_section_presence = detect_expected_sections(srs_clean_step4)
final_incomplete_lines = detect_incomplete_lines(srs_clean_step4)

def compute_strict_srs_score(
    off_topic_counts,
    placeholders,
    duplicate_headings,
    section_presence,
    incomplete_lines
):
    score = 100.0
    
    # Heavy penalty for off-topic contamination
    score -= min(40, sum(off_topic_counts.values()) * 8)
    
    # Placeholder penalty
    score -= min(25, len(placeholders) * 2)
    
    # Duplicate heading penalty
    score -= min(15, len(duplicate_headings) * 2)
    
    # Missing section penalty
    missing = [k for k, v in section_presence.items() if not v]
    score -= len(missing) * 5
    
    # Incomplete lines penalty
    score -= min(20, len(incomplete_lines) * 3)
    
    return max(0, min(100, round(score, 2)))


strict_score = compute_strict_srs_score(
    final_off_topic_counts,
    final_placeholders,
    final_duplicate_headings,
    final_section_presence,
    final_incomplete_lines
)

def strict_quality_label(score):
    if score >= 90:
        return "PRODUCTION_READY_SRS"
    elif score >= 75:
        return "GOOD_SRS_NEEDS_LIGHT_REVIEW"
    elif score >= 60:
        return "NEEDS_HUMAN_REVIEW"
    else:
        return "NOT_READY_FOR_USE"


strict_label = strict_quality_label(strict_score)

strict_report = {
    "strict_srs_score": strict_score,
    "strict_srs_label": strict_label,
    "remaining_off_topic_counts": final_off_topic_counts,
    "remaining_placeholders": final_placeholders,
    "remaining_duplicate_headings": final_duplicate_headings,
    "missing_sections": [k for k, v in final_section_presence.items() if not v],
    "remaining_incomplete_lines": final_incomplete_lines[:20]
}

print(json.dumps(strict_report, indent=2))

strict_report_path = GENERATED_DIR / "g18_final_strict_quality_report.json"

with open(strict_report_path, "w", encoding="utf-8") as f:
    json.dump(strict_report, f, indent=2)

print("\nSaved strict quality report:", strict_report_path)

================================================================================
MODULE G18.6 — FINAL STRICT QUALITY SCORE
================================================================================
{
  "strict_srs_score": 65.0,
  "strict_srs_label": "NEEDS_HUMAN_REVIEW",
  "remaining_off_topic_counts": {},
  "remaining_placeholders": [],
  "remaining_duplicate_headings": {
    "security": 8,
    "availability": 8,
    "performance": 7,
    "usability": 7,
    "reliability": 6,
    "test cases": 6,
    "student registration and authentication": 5,
    "course and class management": 5,
    "teacher authentication": 5,
    "attendance report generation": 5,
    "student check-in": 5,
    "admin dashboard": 5,
    "attendance session creation": 5,
    "maintainability": 5,
    "non-functional requirements": 4,
    ". general description": 2,
    "assumptions": 2,
    ". introduction": 2,
    "functional requirements": 2,
    "requirement improvement": 2,
    "introduction": 2,
    ". functional requirements": 2,
    ". conclusion": 2,
    ". acceptance criteria": 2,
    ". performance requirements": 2,
    ". non-functional requirements": 2
  },
  "missing_sections": [],
  "remaining_incomplete_lines": [
    {
      "line_number": 111,
      "line": "**Test Case:**"
    },
    {
      "line_number": 118,
      "line": "**Test Case:**"
    },
    {
      "line_number": 125,
      "line": "**Test Case:**"
    },
    {
      "line_number": 132,
      "line": "**Test Case:**"
    },
    {
      "line_number": 139,
      "line": "**Test Case:**"
    },
    {
      "line_number": 146,
      "line": "**Test Case:**"
    },
    {
      "line_number": 153,
      "line": "**Test Case:**"
    },
    {
      "line_number": 162,
      "line": "**Test Case:**"
    },
    {
      "line_number": 169,
      "line": "**Test Case:**"
    },
    {
      "line_number": 176,
      "line": "**Test Case:**"
    },
    {
      "line_number": 183,
      "line": "**Test Case:**"
    },
    {
      "line_number": 190,
      "line": "**Test Case:**"
    },
    {
      "line_number": 197,
      "line": "**Test Case:**"
    },
    {
      "line_number": 369,
      "line": "- **Description**: The system"
    },
    {
      "line_number": 412,
      "line": "**Test Cases:**"
    },
    {
      "line_number": 424,
      "line": "**Test Cases:**"
    },
    {
      "line_number": 436,
      "line": "**Test Cases:**"
    },
    {
      "line_number": 448,
      "line": "**Test Cases:**"
    },
    {
      "line_number": 460,
      "line": "**Test Cases:**"
    },
    {
      "line_number": 472,
      "line": "**Test Cases:**"
    }
  ]
}

Saved strict quality report: /kaggle/working/generated_srs/g18_final_strict_quality_report.json

In [36]:
# =========================================================
# MODULE G18.7 — EXPORT CORRECTED SRS
# =========================================================

print("=" * 80)
print("MODULE G18.7 — EXPORT CORRECTED SRS")
print("=" * 80)

project_slug = "smart_university_attendance_management_system"

corrected_md_path = GENERATED_DIR / f"{project_slug}_srs_corrected.md"
corrected_html_path = GENERATED_DIR / f"{project_slug}_srs_corrected.html"

with open(corrected_md_path, "w", encoding="utf-8") as f:
    f.write(srs_clean_step4)

def markdown_to_simple_html(md_text, title):
    html = md_text
    
    # Escape minimal unsafe chars
    html = html.replace("&", "&amp;")
    html = html.replace("<", "&lt;")
    html = html.replace(">", "&gt;")
    
    # Headers
    html = re.sub(r"^# (.*)$", r"<h1>\1</h1>", html, flags=re.MULTILINE)
    html = re.sub(r"^## (.*)$", r"<h2>\1</h2>", html, flags=re.MULTILINE)
    html = re.sub(r"^### (.*)$", r"<h3>\1</h3>", html, flags=re.MULTILINE)
    html = re.sub(r"^#### (.*)$", r"<h4>\1</h4>", html, flags=re.MULTILINE)
    
    # Bold
    html = re.sub(r"\*\*(.*?)\*\*", r"<strong>\1</strong>", html)
    
    # Line breaks
    html = html.replace("\n", "<br>\n")
    
    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>{title}</title>
<style>
body {{
    font-family: Arial, sans-serif;
    margin: 50px;
    line-height: 1.65;
    color: #222;
}}
h1 {{
    color: #12355b;
    border-bottom: 2px solid #12355b;
    padding-bottom: 6px;
}}
h2 {{
    color: #1f5f8b;
    margin-top: 28px;
}}
h3 {{
    color: #2a6f97;
}}
strong {{
    color: #111;
}}
</style>
</head>
<body>
{html}
</body>
</html>
"""

corrected_html = markdown_to_simple_html(
    srs_clean_step4,
    "Corrected Smart University Attendance Management System SRS"
)

with open(corrected_html_path, "w", encoding="utf-8") as f:
    f.write(corrected_html)

print("Saved corrected Markdown:", corrected_md_path)
print("Saved corrected HTML:", corrected_html_path)

================================================================================
MODULE G18.7 — EXPORT CORRECTED SRS
================================================================================
Saved corrected Markdown: /kaggle/working/generated_srs/smart_university_attendance_management_system_srs_corrected.md
Saved corrected HTML: /kaggle/working/generated_srs/smart_university_attendance_management_system_srs_corrected.html

In [37]:
# =========================================================
# MODULE G18.8 — EXPORT CORRECTED DOCX
# =========================================================

print("=" * 80)
print("MODULE G18.8 — EXPORT CORRECTED DOCX")
print("=" * 80)

try:
    from docx import Document
    from docx.shared import Pt
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    
    corrected_docx_path = GENERATED_DIR / f"{project_slug}_srs_corrected.docx"
    
    doc = Document()
    
    for line in srs_clean_step4.splitlines():
        stripped = line.strip()
        
        if not stripped:
            doc.add_paragraph("")
            continue
        
        if stripped.startswith("# "):
            p = doc.add_heading(stripped.replace("# ", "").strip(), level=1)
        elif stripped.startswith("## "):
            p = doc.add_heading(stripped.replace("## ", "").strip(), level=2)
        elif stripped.startswith("### "):
            p = doc.add_heading(stripped.replace("### ", "").strip(), level=3)
        elif stripped.startswith("#### "):
            p = doc.add_heading(stripped.replace("#### ", "").strip(), level=4)
        elif stripped.startswith("- "):
            p = doc.add_paragraph(stripped[2:].strip(), style="List Bullet")
        else:
            clean_line = stripped.replace("**", "")
            p = doc.add_paragraph(clean_line)
    
    doc.save(corrected_docx_path)
    
    print("Saved corrected DOCX:", corrected_docx_path)

except Exception as e:
    corrected_docx_path = None
    print("DOCX export failed:", e)

================================================================================
MODULE G18.8 — EXPORT CORRECTED DOCX
================================================================================
Saved corrected DOCX: /kaggle/working/generated_srs/smart_university_attendance_management_system_srs_corrected.docx

In [48]:
# =========================================================
# MODULE G18.9 — CREATE FINAL DEPLOYMENT ZIP
# =========================================================

print("=" * 80)
print("MODULE G18.9 — CREATE FINAL DEPLOYMENT ZIP")
print("=" * 80)

import zipfile

deployment_zip_path = Path("/kaggle/working/srs_generator_deployment_package.zip")

files_to_zip = []

# Add all generated SRS files
for p in GENERATED_DIR.rglob("*"):
    if p.is_file():
        files_to_zip.append(p)

# Add notebook-friendly config summary
deployment_readme = Path("/kaggle/working/README_DEPLOYMENT.txt")

readme_text = f"""
SRS Generator Deployment Package

Project:
Smart University Attendance Management System

Main outputs:
- Corrected Markdown SRS
- Corrected HTML SRS
- Corrected DOCX SRS
- Generated requirements CSV
- Generated sections CSV
- RAG references CSV
- Evaluation reports
- XAI reports
- Strict SRS quality diagnostics

Strict final quality:
Score: {strict_score}
Label: {strict_label}

Recommended deployment usage:
1. User enters project title, prepared-by name, description, functional needs, non-functional needs.
2. System retrieves high-quality SRS examples using RAG.
3. Instruction-tuned LLM generates the SRS section by section.
4. Quality validator checks generated requirements.
5. XAI module explains RAG evidence and quality scores.
6. Strict quality gate removes off-topic contamination and detects placeholders.
7. Final SRS is exported in Markdown, HTML, and DOCX formats.

Important:
The generated SRS should still be reviewed by a human stakeholder before real implementation.
"""

with open(deployment_readme, "w", encoding="utf-8") as f:
    f.write(readme_text)

files_to_zip.append(deployment_readme)

with zipfile.ZipFile(deployment_zip_path, "w", zipfile.ZIP_DEFLATED) as zipf:
    for file_path in files_to_zip:
        arcname = file_path.relative_to("/kaggle/working")
        zipf.write(file_path, arcname)

print("Deployment ZIP created:")
print(deployment_zip_path)

print("\nFiles included:", len(files_to_zip))
for p in files_to_zip[:30]:
    print("-", p)

================================================================================
MODULE G18.9 — CREATE FINAL DEPLOYMENT ZIP
================================================================================
Deployment ZIP created:
/kaggle/working/srs_generator_deployment_package.zip

Files included: 28
- /kaggle/working/generated_srs/smart_university_attendance_management_system_srs.md
- /kaggle/working/generated_srs/smart_university_attendance_management_system_professional_srs.docx
- /kaggle/working/generated_srs/g18_strict_srs_diagnostics.json
- /kaggle/working/generated_srs/smart_university_attendance_management_system_professional_srs.html
- /kaggle/working/generated_srs/smart_university_attendance_management_system_srs_corrected.md
- /kaggle/working/generated_srs/smart_university_attendance_management_system_professional_srs_validation.json
- /kaggle/working/generated_srs/smart_university_attendance_management_system_professional_srs.md
- /kaggle/working/generated_srs/g18_final_strict_quality_report.json
- /kaggle/working/generated_srs/smart_university_attendance_management_system_srs_corrected.docx
- /kaggle/working/generated_srs/smart_university_attendance_management_system_generated_requirements.csv
- /kaggle/working/generated_srs/smart_university_attendance_management_system_srs_corrected.html
- /kaggle/working/generated_srs/smart_university_attendance_management_system_rag_references.csv
- /kaggle/working/generated_srs/smart_university_attendance_management_system_professional_requirements.csv
- /kaggle/working/generated_srs/g18_removed_off_topic_paragraphs.txt
- /kaggle/working/generated_srs/smart_university_attendance_management_system_generation_summary.txt
- /kaggle/working/generated_srs/smart_university_attendance_management_system_srs.html
- /kaggle/working/generated_srs/smart_university_attendance_management_system_srs.docx
- /kaggle/working/generated_srs/smart_university_attendance_management_system_generated_sections.csv
- /kaggle/working/generated_srs/evaluation_xai/smart_university_attendance_management_system_final_generation_score.csv
- /kaggle/working/generated_srs/evaluation_xai/smart_university_attendance_management_system_evaluation_xai_manifest.csv
- /kaggle/working/generated_srs/evaluation_xai/smart_university_attendance_management_system_generation_structure_evaluation.csv
- /kaggle/working/generated_srs/evaluation_xai/smart_university_attendance_management_system_requirement_quality_evaluation.csv
- /kaggle/working/generated_srs/evaluation_xai/smart_university_attendance_management_system_rag_xai_evidence.csv
- /kaggle/working/generated_srs/evaluation_xai/smart_university_attendance_management_system_section_generation_xai.csv
- /kaggle/working/generated_srs/evaluation_xai/smart_university_attendance_management_system_rag_evaluation.csv
- /kaggle/working/generated_srs/evaluation_xai/smart_university_attendance_management_system_global_xai_report.md
- /kaggle/working/generated_srs/evaluation_xai/smart_university_attendance_management_system_requirement_quality_xai.csv
- /kaggle/working/README_DEPLOYMENT.txt

# MODULE G19 — PROFESSIONAL SRS REGENERATION & VALIDATION

This module regenerates the final SRS using a strict professional SRS template.

The goal is to transform the initial generated SRS into a clean, complete, structured, and validated Software Requirements Specification document.

The regenerated SRS must:
- avoid duplicated section titles
- avoid question-style requirements
- use clear “The system shall...” requirement statements
- include requirement IDs
- include priorities
- include acceptance criteria
- include risks and assumptions
- include traceability matrix
- include references
- include a final validation report

In [38]:
# =========================================================
# MODULE G19.0 — LOAD PREVIOUS GENERATION OUTPUTS
# =========================================================

from pathlib import Path
import os
import re
import json
import pandas as pd
import numpy as np
from datetime import datetime

print("=" * 80)
print("MODULE G19.0 — LOAD PREVIOUS GENERATION OUTPUTS")
print("=" * 80)

BASE_OUTPUT_DIR = Path("/kaggle/working/generated_srs")
BASE_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

def find_file(filename):
    search_roots = [
        Path("/kaggle/working"),
        Path("/kaggle/input")
    ]
    
    for root in search_roots:
        direct = root / filename
        if direct.exists():
            return direct
    
    for root in search_roots:
        if root.exists():
            matches = list(root.rglob(filename))
            if len(matches) > 0:
                return matches[0]
    
    return None


candidate_files = {
    "generated_requirements": "smart_university_attendance_management_system_generated_requirements.csv",
    "generated_sections": "smart_university_attendance_management_system_generated_sections.csv",
    "rag_references": "smart_university_attendance_management_system_rag_references.csv",
    "generation_summary": "smart_university_attendance_management_system_generation_summary.txt",
    "old_srs_md": "smart_university_attendance_management_system_srs.md"
}

found_g19_paths = {}

for key, filename in candidate_files.items():
    path = find_file(filename)
    found_g19_paths[key] = path
    print(key, "=>", path)

if found_g19_paths["generated_requirements"] is None:
    raise FileNotFoundError("Missing generated requirements CSV from previous generation module.")

df_generated_requirements = pd.read_csv(found_g19_paths["generated_requirements"])

if found_g19_paths["generated_sections"] is not None:
    df_generated_sections = pd.read_csv(found_g19_paths["generated_sections"])
else:
    df_generated_sections = pd.DataFrame()

if found_g19_paths["rag_references"] is not None:
    df_rag_references = pd.read_csv(found_g19_paths["rag_references"])
else:
    df_rag_references = pd.DataFrame()

print("\nGenerated requirements shape:", df_generated_requirements.shape)
print("Generated sections shape:", df_generated_sections.shape)
print("RAG references shape:", df_rag_references.shape)

display(df_generated_requirements.head(10))

================================================================================
MODULE G19.0 — LOAD PREVIOUS GENERATION OUTPUTS
================================================================================
generated_requirements => /kaggle/working/generated_srs/smart_university_attendance_management_system_generated_requirements.csv
generated_sections => /kaggle/working/generated_srs/smart_university_attendance_management_system_generated_sections.csv
rag_references => /kaggle/working/generated_srs/smart_university_attendance_management_system_rag_references.csv
generation_summary => /kaggle/working/generated_srs/smart_university_attendance_management_system_generation_summary.txt
old_srs_md => /kaggle/working/generated_srs/smart_university_attendance_management_system_srs.md

Generated requirements shape: (144, 15)
Generated sections shape: (10, 4)
RAG references shape: (80, 12)

,section_id,section_title,generated_requirement_id,generated_requirement_text,generated_word_count,generated_has_modal,generated_has_vague_terms,generated_has_numeric_or_quality_constraint,generated_has_actor_or_system,generated_clarity_score,generated_testability_score,generated_measurability_score,generated_completeness_score,generated_quality_score,generated_quality_label
0,2,General Description,GREQ-2-001,Accessibility: The system must be accessible v...,9,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
1,2,General Description,GREQ-2-002,Scalability: The system should support high tr...,11,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
2,2,General Description,GREQ-2-003,Requirement:** Students must be able to regist...,16,True,False,True,False,100,100,100,80,95.0,STRONG_GENERATED_REQUIREMENT
3,2,General Description,GREQ-2-004,Requirement:** Teachers must be authenticated ...,12,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
4,2,General Description,GREQ-2-005,Requirement:** Administrators must be able to ...,17,True,False,False,False,100,100,80,80,90.0,STRONG_GENERATED_REQUIREMENT
5,2,General Description,GREQ-2-006,Requirement:** Teachers must be able to create...,14,True,False,False,False,100,100,80,80,90.0,STRONG_GENERATED_REQUIREMENT
6,2,General Description,GREQ-2-007,Requirement:** Students must be able to check ...,12,True,False,False,False,100,100,80,80,90.0,STRONG_GENERATED_REQUIREMENT
7,2,General Description,GREQ-2-008,Requirement:** Administrators must be able to ...,15,True,False,False,False,100,100,80,80,90.0,STRONG_GENERATED_REQUIREMENT
8,2,General Description,GREQ-2-009,Requirement:** Administrators must have a dedi...,20,True,False,False,False,100,100,80,80,90.0,STRONG_GENERATED_REQUIREMENT
9,2,General Description,GREQ-2-010,Requirement:** All user data must be protected...,12,True,False,True,True,100,100,100,100,100.0,STRONG_GENERATED_REQUIREMENT

In [39]:
# =========================================================
# MODULE G19.1 — DEFINE STRICT PROFESSIONAL SRS TEMPLATE
# =========================================================

print("=" * 80)
print("MODULE G19.1 — DEFINE STRICT PROFESSIONAL SRS TEMPLATE")
print("=" * 80)

SRS_TEMPLATE = {
    "cover_page": [
        "Project title",
        "Prepared by",
        "Version",
        "Generation date",
        "Generation method"
    ],
    "sections": [
        "1. Introduction",
        "2. Overall Description",
        "3. System Features and Functional Requirements",
        "4. External Interface Requirements",
        "5. Non-Functional Requirements",
        "6. Data Requirements",
        "7. Security and Privacy Requirements",
        "8. Acceptance Criteria",
        "9. Risks, Assumptions, and Dependencies",
        "10. Requirement Traceability Matrix",
        "11. Conclusion",
        "12. References"
    ]
}

SRS_RULES = """
Professional SRS writing rules:

1. Do not duplicate section titles.
2. Do not write requirements as questions.
3. Every functional requirement must start with: "The system shall..."
4. Every non-functional requirement must start with: "The system shall..."
5. Every requirement must have:
   - Requirement ID
   - Requirement statement
   - Priority
   - Rationale
   - Acceptance criteria
6. Do not include unfinished sentences.
7. Do not include unrelated project content.
8. Do not use vague terms such as fast, easy, user-friendly, appropriate, sufficient unless they are measurable.
9. If a numeric threshold is unknown, use: [TO BE VALIDATED WITH STAKEHOLDERS].
10. Keep sections clean and non-repetitive.
11. Separate functional requirements from non-functional requirements.
12. Include a final validation note.
"""

print("Strict SRS template loaded.")
print(json.dumps(SRS_TEMPLATE, indent=2))
print(SRS_RULES)

================================================================================
MODULE G19.1 — DEFINE STRICT PROFESSIONAL SRS TEMPLATE
================================================================================
Strict SRS template loaded.
{
  "cover_page": [
    "Project title",
    "Prepared by",
    "Version",
    "Generation date",
    "Generation method"
  ],
  "sections": [
    "1. Introduction",
    "2. Overall Description",
    "3. System Features and Functional Requirements",
    "4. External Interface Requirements",
    "5. Non-Functional Requirements",
    "6. Data Requirements",
    "7. Security and Privacy Requirements",
    "8. Acceptance Criteria",
    "9. Risks, Assumptions, and Dependencies",
    "10. Requirement Traceability Matrix",
    "11. Conclusion",
    "12. References"
  ]
}

Professional SRS writing rules:

1. Do not duplicate section titles.
2. Do not write requirements as questions.
3. Every functional requirement must start with: "The system shall..."
4. Every non-functional requirement must start with: "The system shall..."
5. Every requirement must have:
   - Requirement ID
   - Requirement statement
   - Priority
   - Rationale
   - Acceptance criteria
6. Do not include unfinished sentences.
7. Do not include unrelated project content.
8. Do not use vague terms such as fast, easy, user-friendly, appropriate, sufficient unless they are measurable.
9. If a numeric threshold is unknown, use: [TO BE VALIDATED WITH STAKEHOLDERS].
10. Keep sections clean and non-repetitive.
11. Separate functional requirements from non-functional requirements.
12. Include a final validation note.

In [40]:
# =========================================================
# MODULE G19.2 — CLEAN AND NORMALIZE GENERATED REQUIREMENTS
# =========================================================

print("=" * 80)
print("MODULE G19.2 — CLEAN AND NORMALIZE GENERATED REQUIREMENTS")
print("=" * 80)

df_g19_reqs = df_generated_requirements.copy()

def clean_generated_text(text):
    text = str(text)
    text = re.sub(r"\*\*", "", text)
    text = re.sub(r"Requirement:\s*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"Description:\s*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"Note:\s*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\s+", " ", text).strip()
    return text

text_col_candidates = [
    "generated_requirement_text",
    "requirement_text",
    "text"
]

text_col = None
for col in text_col_candidates:
    if col in df_g19_reqs.columns:
        text_col = col
        break

if text_col is None:
    raise ValueError("Could not find generated requirement text column.")

df_g19_reqs["clean_requirement_text"] = df_g19_reqs[text_col].apply(clean_generated_text)

def normalize_requirement_statement(text):
    text = str(text).strip()
    
    if len(text) == 0:
        return ""
    
    # Remove question form
    text = re.sub(r"^Shall\s+the\s+system\s+", "The system shall ", text, flags=re.IGNORECASE)
    text = re.sub(r"\?$", ".", text)
    
    # If not starting with system shall, repair
    low = text.lower()
    if not low.startswith("the system shall"):
        if low.startswith("shall "):
            text = "The system " + text[0].lower() + text[1:]
        elif low.startswith("the system must"):
            text = re.sub(r"^The system must", "The system shall", text, flags=re.IGNORECASE)
        elif low.startswith("system must"):
            text = re.sub(r"^System must", "The system shall", text, flags=re.IGNORECASE)
        else:
            text = "The system shall " + text[0].lower() + text[1:]
    
    # Ensure final period
    if not text.endswith("."):
        text += "."
    
    return text

df_g19_reqs["normalized_requirement"] = df_g19_reqs["clean_requirement_text"].apply(
    normalize_requirement_statement
)

def infer_req_type(row):
    text = str(row["normalized_requirement"]).lower()
    section = str(row.get("section_title", "")).lower()
    
    nfr_keywords = [
        "security", "performance", "availability", "usability",
        "reliability", "maintainability", "scalability", "privacy",
        "response time", "throughput", "encryption", "authentication"
    ]
    
    if "non-functional" in section:
        return "NFR"
    
    if any(k in text for k in nfr_keywords):
        return "NFR"
    
    return "FR"

df_g19_reqs["professional_requirement_type"] = df_g19_reqs.apply(infer_req_type, axis=1)

df_g19_reqs = df_g19_reqs[
    df_g19_reqs["normalized_requirement"].str.len() > 20
].copy()

df_g19_reqs = df_g19_reqs.drop_duplicates(
    subset=["normalized_requirement"]
).reset_index(drop=True)

df_g19_reqs["professional_requirement_id"] = [
    f"REQ-{i+1:03d}" for i in range(len(df_g19_reqs))
]

print("Clean professional requirements shape:", df_g19_reqs.shape)

print("\nRequirement type distribution:")
print(df_g19_reqs["professional_requirement_type"].value_counts())

display(df_g19_reqs[
    [
        "professional_requirement_id",
        "professional_requirement_type",
        "normalized_requirement"
    ]
].head(30))

================================================================================
MODULE G19.2 — CLEAN AND NORMALIZE GENERATED REQUIREMENTS
================================================================================
Clean professional requirements shape: (143, 19)

Requirement type distribution:
professional_requirement_type
FR     95
NFR    48
Name: count, dtype: int64

,professional_requirement_id,professional_requirement_type,normalized_requirement
0,REQ-001,FR,The system shall accessibility: The system mus...
1,REQ-002,NFR,The system shall scalability: The system shoul...
2,REQ-003,FR,The system shall students must be able to regi...
3,REQ-004,FR,The system shall teachers must be authenticate...
4,REQ-005,FR,The system shall administrators must be able t...
5,REQ-006,FR,The system shall teachers must be able to crea...
6,REQ-007,FR,The system shall students must be able to chec...
7,REQ-008,FR,The system shall administrators must be able t...
8,REQ-009,FR,The system shall administrators must have a de...
9,REQ-010,FR,The system shall all user data must be protect...
10,REQ-011,NFR,The system shall perform well under heavy load...
11,REQ-012,FR,The system shall be available 24/7 without any...
12,REQ-013,FR,The system shall the interface must be intuiti...
13,REQ-014,FR,The system shall function reliably without fre...
14,REQ-015,FR,The system shall be easily maintainable and sc...
15,REQ-016,NFR,The system shall demonstrate a high level of s...
16,REQ-017,FR,The system shall comply with the latest indust...
17,REQ-018,NFR,The system shall support multi-tier authentica...
18,REQ-019,FR,The system shall provide a secure and efficien...
19,REQ-020,FR,The system shall students shall be able to sig...
20,REQ-021,FR,The system shall enable teachers to log in sec...
21,REQ-022,NFR,The system shall teachers shall be able to acc...
22,REQ-023,FR,The system shall facilitate the creation and m...
23,REQ-024,FR,The system shall teachers shall be able to cre...
24,REQ-025,FR,The system shall allow teachers to schedule an...
25,REQ-026,FR,The system shall teachers shall be able to cre...
26,REQ-027,FR,The system shall enable students to check into...
27,REQ-028,FR,The system shall students shall be able to log...
28,REQ-029,FR,The system shall generate detailed attendance ...
29,REQ-030,FR,The system shall automatically generate attend...

In [41]:
# =========================================================
# MODULE G19.3 — BUILD PROFESSIONAL REQUIREMENT TABLES
# =========================================================

print("=" * 80)
print("MODULE G19.3 — BUILD PROFESSIONAL REQUIREMENT TABLES")
print("=" * 80)

def infer_priority(text, req_type):
    text = str(text).lower()
    
    high_keywords = [
        "security", "authentication", "authorization", "encrypt",
        "attendance", "check in", "report", "administrator"
    ]
    
    medium_keywords = [
        "dashboard", "notification", "course", "class", "profile",
        "usability", "maintainability"
    ]
    
    if any(k in text for k in high_keywords):
        return "High"
    
    if any(k in text for k in medium_keywords):
        return "Medium"
    
    return "Medium"

def build_rationale(text, req_type):
    if req_type == "FR":
        return "This requirement supports the core business functionality expected by students, teachers, and administrators."
    else:
        return "This requirement ensures that the system satisfies quality attributes such as security, performance, reliability, and maintainability."

def build_acceptance_criteria(text, req_type):
    text_low = str(text).lower()
    
    criteria = []
    
    if "login" in text_low or "authenticat" in text_low:
        criteria.append("Given valid credentials, the user shall be authenticated successfully.")
        criteria.append("Given invalid credentials, the system shall deny access and display an error message.")
    
    elif "check" in text_low and "attendance" in text_low:
        criteria.append("Given an active attendance session, the student shall be able to check in successfully.")
        criteria.append("The system shall record the attendance status with timestamp and session identifier.")
    
    elif "report" in text_low:
        criteria.append("Given valid filter parameters, the system shall generate an attendance report.")
        criteria.append("The report shall include attendance status, student information, course information, and date range.")
    
    elif "course" in text_low or "class" in text_low:
        criteria.append("Given valid course or class data, the system shall save the record successfully.")
        criteria.append("The created or updated course/class shall be visible to authorized users.")
    
    elif req_type == "NFR":
        criteria.append("The requirement shall be verified using an agreed test or audit procedure.")
        criteria.append("The final threshold shall be validated with stakeholders before deployment.")
    
    else:
        criteria.append("The requirement shall be testable through a defined functional scenario.")
        criteria.append("The expected result shall match the described system behavior.")
    
    return criteria

df_professional_requirements = df_g19_reqs.copy()

df_professional_requirements["priority"] = df_professional_requirements.apply(
    lambda row: infer_priority(row["normalized_requirement"], row["professional_requirement_type"]),
    axis=1
)

df_professional_requirements["rationale"] = df_professional_requirements.apply(
    lambda row: build_rationale(row["normalized_requirement"], row["professional_requirement_type"]),
    axis=1
)

df_professional_requirements["acceptance_criteria"] = df_professional_requirements.apply(
    lambda row: build_acceptance_criteria(row["normalized_requirement"], row["professional_requirement_type"]),
    axis=1
)

df_functional_reqs = df_professional_requirements[
    df_professional_requirements["professional_requirement_type"] == "FR"
].copy()

df_nonfunctional_reqs = df_professional_requirements[
    df_professional_requirements["professional_requirement_type"] == "NFR"
].copy()

print("Functional requirements:", len(df_functional_reqs))
print("Non-functional requirements:", len(df_nonfunctional_reqs))

display(df_professional_requirements[
    [
        "professional_requirement_id",
        "professional_requirement_type",
        "priority",
        "normalized_requirement",
        "rationale",
        "acceptance_criteria"
    ]
].head(20))

================================================================================
MODULE G19.3 — BUILD PROFESSIONAL REQUIREMENT TABLES
================================================================================
Functional requirements: 95
Non-functional requirements: 48

,professional_requirement_id,professional_requirement_type,priority,normalized_requirement,rationale,acceptance_criteria
0,REQ-001,FR,Medium,The system shall accessibility: The system mus...,This requirement supports the core business fu...,[The requirement shall be testable through a d...
1,REQ-002,NFR,Medium,The system shall scalability: The system shoul...,This requirement ensures that the system satis...,[The requirement shall be verified using an ag...
2,REQ-003,FR,Medium,The system shall students must be able to regi...,This requirement supports the core business fu...,"[Given valid credentials, the user shall be au..."
3,REQ-004,FR,Medium,The system shall teachers must be authenticate...,This requirement supports the core business fu...,"[Given valid credentials, the user shall be au..."
4,REQ-005,FR,High,The system shall administrators must be able t...,This requirement supports the core business fu...,"[Given valid course or class data, the system ..."
5,REQ-006,FR,High,The system shall teachers must be able to crea...,This requirement supports the core business fu...,"[Given valid course or class data, the system ..."
6,REQ-007,FR,High,The system shall students must be able to chec...,This requirement supports the core business fu...,[The requirement shall be testable through a d...
7,REQ-008,FR,High,The system shall administrators must be able t...,This requirement supports the core business fu...,"[Given valid filter parameters, the system sha..."
8,REQ-009,FR,High,The system shall administrators must have a de...,This requirement supports the core business fu...,"[Given an active attendance session, the stude..."
9,REQ-010,FR,Medium,The system shall all user data must be protect...,This requirement supports the core business fu...,[The requirement shall be testable through a d...
10,REQ-011,NFR,Medium,The system shall perform well under heavy load...,This requirement ensures that the system satis...,[The requirement shall be verified using an ag...
11,REQ-012,FR,Medium,The system shall be available 24/7 without any...,This requirement supports the core business fu...,[The requirement shall be testable through a d...
12,REQ-013,FR,Medium,The system shall the interface must be intuiti...,This requirement supports the core business fu...,[The requirement shall be testable through a d...
13,REQ-014,FR,Medium,The system shall function reliably without fre...,This requirement supports the core business fu...,[The requirement shall be testable through a d...
14,REQ-015,FR,Medium,The system shall be easily maintainable and sc...,This requirement supports the core business fu...,[The requirement shall be testable through a d...
15,REQ-016,NFR,High,The system shall demonstrate a high level of s...,This requirement ensures that the system satis...,[The requirement shall be verified using an ag...
16,REQ-017,FR,Medium,The system shall comply with the latest indust...,This requirement supports the core business fu...,[The requirement shall be testable through a d...
17,REQ-018,NFR,High,The system shall support multi-tier authentica...,This requirement ensures that the system satis...,"[Given valid credentials, the user shall be au..."
18,REQ-019,FR,Medium,The system shall provide a secure and efficien...,This requirement supports the core business fu...,"[Given valid credentials, the user shall be au..."
19,REQ-020,FR,Medium,The system shall students shall be able to sig...,This requirement supports the core business fu...,"[Given valid credentials, the user shall be au..."

In [42]:
# =========================================================
# MODULE G19.4 — BUILD FINAL PROFESSIONAL SRS MARKDOWN
# =========================================================

print("=" * 80)
print("MODULE G19.4 — BUILD FINAL PROFESSIONAL SRS MARKDOWN")
print("=" * 80)

PROJECT_TITLE = project_info.get(
    "project_title",
    "Smart University Attendance Management System"
)

PREPARED_BY = project_info.get(
    "prepared_by",
    "Sarah Boussaidi"
)

generation_date = datetime.now().strftime("%Y-%m-%d %H:%M")

def md_escape(text):
    return str(text).replace("\n", " ").strip()

def format_requirement_block(row):
    req_id = row["professional_requirement_id"]
    req_type = row["professional_requirement_type"]
    priority = row["priority"]
    statement = md_escape(row["normalized_requirement"])
    rationale = md_escape(row["rationale"])
    acceptance = row["acceptance_criteria"]
    
    block = f"""
### {req_id} — {req_type}

**Requirement statement:**  
{statement}

**Priority:** {priority}

**Rationale:**  
{rationale}

**Acceptance criteria:**
"""
    for i, criterion in enumerate(acceptance, start=1):
        block += f"{i}. {criterion}\n"
    
    return block.strip()


functional_blocks = "\n\n".join(
    df_functional_reqs.apply(format_requirement_block, axis=1).tolist()
)

nonfunctional_blocks = "\n\n".join(
    df_nonfunctional_reqs.apply(format_requirement_block, axis=1).tolist()
)

if len(functional_blocks.strip()) == 0:
    functional_blocks = "No functional requirements were generated."

if len(nonfunctional_blocks.strip()) == 0:
    nonfunctional_blocks = "No non-functional requirements were generated."

traceability_rows = []
for _, row in df_professional_requirements.iterrows():
    traceability_rows.append(
        f"| {row['professional_requirement_id']} | {row['professional_requirement_type']} | {row['priority']} | {md_escape(row['normalized_requirement'])[:90]}... | Generated from user prompt + RAG evidence |"
    )

traceability_table = """
| Requirement ID | Type | Priority | Short Description | Source |
|---|---|---|---|---|
""" + "\n".join(traceability_rows)

references_text = """
1. User-provided project description.
2. Functional and non-functional needs provided in the project prompt.
3. RAG knowledge base built from previous SRS requirement analysis.
4. NLP requirement quality scoring outputs.
5. LLM-assisted generation and validation pipeline.
"""

professional_srs_md = f"""# Software Requirements Specification

## {PROJECT_TITLE}

**Prepared by:** {PREPARED_BY}  
**Version:** 2.0 — Professional Regenerated Version  
**Generated on:** {generation_date}  
**Generation method:** LLM + RAG + Professional SRS Validation  
**Validation status:** Automatically checked and ready for stakeholder review  

---

# Revision History

| Version | Date | Author | Description |
|---|---|---|---|
| 1.0 | 2026-05-10 | AI-assisted pipeline | Initial generated SRS |
| 2.0 | {generation_date} | {PREPARED_BY} + AI-assisted validation | Professional regenerated and validated SRS |

---

# Table of Contents

1. Introduction  
2. Overall Description  
3. System Features and Functional Requirements  
4. External Interface Requirements  
5. Non-Functional Requirements  
6. Data Requirements  
7. Security and Privacy Requirements  
8. Acceptance Criteria  
9. Risks, Assumptions, and Dependencies  
10. Requirement Traceability Matrix  
11. Conclusion  
12. References  

---

# 1. Introduction

## 1.1 Purpose

The purpose of this document is to define the Software Requirements Specification for the **{PROJECT_TITLE}**. This SRS describes the expected functional behavior, non-functional constraints, external interfaces, data requirements, security requirements, acceptance criteria, risks, and traceability information required to guide design, development, testing, and validation.

## 1.2 Scope

The system supports university attendance management through student registration, teacher authentication, course and class management, attendance session creation, student check-in, attendance report generation, and administrator monitoring. The system is intended to improve attendance accuracy, reduce manual work, and provide reliable reporting for academic stakeholders.

## 1.3 Intended Users

The main users of the system are:

- **Students**, who register, authenticate, check in to attendance sessions, and view attendance status.
- **Teachers**, who create attendance sessions, monitor attendance, and manage course-level attendance activities.
- **Administrators**, who manage users, courses, classes, reports, and system-level configuration.

## 1.4 Definitions and Acronyms

| Term | Meaning |
|---|---|
| SRS | Software Requirements Specification |
| FR | Functional Requirement |
| NFR | Non-Functional Requirement |
| RBAC | Role-Based Access Control |
| MFA | Multi-Factor Authentication |
| GDPR | General Data Protection Regulation |

---

# 2. Overall Description

## 2.1 Product Perspective

The system is a web-based attendance management platform designed for universities. It may integrate with existing university information systems, authentication services, notification services, and reporting tools.

## 2.2 Product Functions

At a high level, the system shall provide:

- user registration and authentication
- teacher and administrator access management
- course and class management
- attendance session creation
- student check-in
- attendance reporting
- administrative dashboards
- security and privacy controls
- audit and monitoring capabilities

## 2.3 User Classes and Characteristics

| User Class | Description |
|---|---|
| Student | Uses the system to check in and view attendance records |
| Teacher | Creates and manages attendance sessions |
| Administrator | Manages users, courses, permissions, and reports |

## 2.4 Operating Environment

The system shall be accessible through modern web browsers. It may also support mobile access if required by stakeholders.

## 2.5 Constraints

- The system shall protect student and teacher data.
- The system shall support role-based access.
- Performance thresholds shall be validated with stakeholders.
- Availability targets shall be validated before deployment.

---

# 3. System Features and Functional Requirements

{functional_blocks}

---

# 4. External Interface Requirements

## 4.1 User Interface

The system shall provide a responsive, accessible, and role-based user interface for students, teachers, and administrators.

## 4.2 Hardware Interfaces

The system shall not require specialized hardware for standard web access. If biometric or QR-based attendance is added, the required devices shall be validated with stakeholders.

## 4.3 Software Interfaces

The system may interface with:

- university authentication systems
- student information systems
- email notification services
- reporting and analytics tools
- database management systems

## 4.4 Communication Interfaces

The system shall use secure communication protocols such as HTTPS for all client-server communication.

---

# 5. Non-Functional Requirements

{nonfunctional_blocks}

---

# 6. Data Requirements

## 6.1 Student Data

The system shall store student identity, enrollment information, attendance records, and authentication-related metadata.

## 6.2 Teacher Data

The system shall store teacher identity, assigned courses, attendance sessions, and access permissions.

## 6.3 Attendance Data

The system shall store attendance session details, check-in timestamps, attendance status, and reportable attendance history.

## 6.4 Data Retention

The system shall retain attendance data according to university policy and applicable legal requirements.

---

# 7. Security and Privacy Requirements

## 7.1 Authentication

The system shall require authenticated access for all users.

## 7.2 Authorization

The system shall enforce role-based access control for students, teachers, and administrators.

## 7.3 Data Protection

The system shall encrypt sensitive data in transit and protect stored sensitive data using appropriate security mechanisms.

## 7.4 Audit Logging

The system shall maintain audit logs for authentication attempts, attendance changes, report generation, and administrative actions.

## 7.5 Privacy

The system shall process personal data according to applicable privacy regulations and institutional policies.

---

# 8. Acceptance Criteria

A requirement shall be considered accepted when:

1. Its implementation satisfies the requirement statement.
2. Its acceptance criteria pass during testing.
3. Its behavior is verified by stakeholders or authorized reviewers.
4. Security and privacy constraints are respected.
5. Performance and availability thresholds are validated where applicable.
6. No critical ambiguity remains unresolved.

---

# 9. Risks, Assumptions, and Dependencies

## 9.1 Risks

| Risk | Impact | Mitigation |
|---|---|---|
| Incomplete stakeholder thresholds | NFRs may remain partially unspecified | Validate thresholds before deployment |
| Authentication weaknesses | Unauthorized access may occur | Enforce MFA and RBAC |
| Poor network connectivity | Users may experience failed check-ins | Provide retry and offline-tolerant mechanisms if required |
| High concurrent usage | Performance may degrade | Conduct load testing and scale infrastructure |
| Data privacy breach | Legal and trust impact | Apply encryption, access control, and audit logging |

## 9.2 Assumptions

- Users will have access to a web browser.
- The university will define final performance thresholds.
- Administrators will maintain user and course data.
- Stakeholders will validate acceptance criteria before deployment.

## 9.3 Dependencies

- University authentication system
- Database infrastructure
- Notification service
- Network availability
- Security policy approval

---

# 10. Requirement Traceability Matrix

{traceability_table}

---

# 11. Conclusion

This SRS defines the requirements for the **{PROJECT_TITLE}**. The system is expected to improve attendance management by supporting secure authentication, attendance session creation, student check-in, course management, reporting, and administrative monitoring. The requirements in this document should be reviewed and validated by stakeholders before implementation.

---

# 12. References

{references_text}

---

# Requirements Validation Note

This SRS was regenerated using an AI-assisted pipeline based on:

- user project description
- RAG retrieval from previous SRS requirement intelligence outputs
- generated requirement extraction
- requirement quality validation
- professional SRS formatting rules

Final stakeholder review is required before implementation.
"""

print(professional_srs_md[:5000])

================================================================================
MODULE G19.4 — BUILD FINAL PROFESSIONAL SRS MARKDOWN
================================================================================
# Software Requirements Specification

## Smart University Attendance Management System

**Prepared by:** Sarah Boussaidi
**Version:** 2.0 — Professional Regenerated Version
**Generated on:** 2026-05-10 22:10
**Generation method:** LLM + RAG + Professional SRS Validation
**Validation status:** Automatically checked and ready for stakeholder review

---

# Revision History

| Version | Date | Author | Description |
|---|---|---|---|
| 1.0 | 2026-05-10 | AI-assisted pipeline | Initial generated SRS |
| 2.0 | 2026-05-10 22:10 | Sarah Boussaidi + AI-assisted validation | Professional regenerated and validated SRS |

---

# Table of Contents

1. Introduction
2. Overall Description
3. System Features and Functional Requirements
4. External Interface Requirements
5. Non-Functional Requirements
6. Data Requirements
7. Security and Privacy Requirements
8. Acceptance Criteria
9. Risks, Assumptions, and Dependencies
10. Requirement Traceability Matrix
11. Conclusion
12. References

---

# 1. Introduction

## 1.1 Purpose

The purpose of this document is to define the Software Requirements Specification for the **Smart University Attendance Management System**. This SRS describes the expected functional behavior, non-functional constraints, external interfaces, data requirements, security requirements, acceptance criteria, risks, and traceability information required to guide design, development, testing, and validation.

## 1.2 Scope

The system supports university attendance management through student registration, teacher authentication, course and class management, attendance session creation, student check-in, attendance report generation, and administrator monitoring. The system is intended to improve attendance accuracy, reduce manual work, and provide reliable reporting for academic stakeholders.

## 1.3 Intended Users

The main users of the system are:

- **Students**, who register, authenticate, check in to attendance sessions, and view attendance status.
- **Teachers**, who create attendance sessions, monitor attendance, and manage course-level attendance activities.
- **Administrators**, who manage users, courses, classes, reports, and system-level configuration.

## 1.4 Definitions and Acronyms

| Term | Meaning |
|---|---|
| SRS | Software Requirements Specification |
| FR | Functional Requirement |
| NFR | Non-Functional Requirement |
| RBAC | Role-Based Access Control |
| MFA | Multi-Factor Authentication |
| GDPR | General Data Protection Regulation |

---

# 2. Overall Description

## 2.1 Product Perspective

The system is a web-based attendance management platform designed for universities. It may integrate with existing university information systems, authentication services, notification services, and reporting tools.

## 2.2 Product Functions

At a high level, the system shall provide:

- user registration and authentication
- teacher and administrator access management
- course and class management
- attendance session creation
- student check-in
- attendance reporting
- administrative dashboards
- security and privacy controls
- audit and monitoring capabilities

## 2.3 User Classes and Characteristics

| User Class | Description |
|---|---|
| Student | Uses the system to check in and view attendance records |
| Teacher | Creates and manages attendance sessions |
| Administrator | Manages users, courses, permissions, and reports |

## 2.4 Operating Environment

The system shall be accessible through modern web browsers. It may also support mobile access if required by stakeholders.

## 2.5 Constraints

- The system shall protect student and teacher data.
- The system shall support role-based access.
- Performance thresholds shall be validated with stakeholders.
- Availability targets shall be validated before deployment.

---

# 3. System Features and Functional Requirements

### REQ-001 — FR

**Requirement statement:**
The system shall accessibility: The system must be accessible via web browsers.

**Priority:** Medium

**Rationale:**
This requirement supports the core business functionality expected by students, teachers, and administrators.

**Acceptance criteria:**
1. The requirement shall be testable through a defined functional scenario.
2. The expected result shall match the described system behavior.

### REQ-003 — FR

**Requirement statement:**
The system shall students must be able to register and authenticate themselves using a unique identifier and password.

**Priority:** Medium

**Rationale:**
This requirement supports the core business functionality expected by students, teachers, and administrators.

**Acceptance criteria:**
1. Given valid credentials, the user shall be authenticated successfully.
2. Given invalid credentials, the system shall deny access and display an error message.

### REQ-004 — FR

**Requirement statement:**
The system shall teachers must be authenticated before they can access the teacher dashboard.

**Priority:**

In [43]:
# =========================================================
# MODULE G19.5 — VALIDATE PROFESSIONAL SRS
# =========================================================

print("=" * 80)
print("MODULE G19.5 — VALIDATE PROFESSIONAL SRS")
print("=" * 80)

def validate_professional_srs(srs_text):
    checks = {}
    
    checks["has_cover_title"] = "# Software Requirements Specification" in srs_text
    checks["has_revision_history"] = "# Revision History" in srs_text
    checks["has_table_of_contents"] = "# Table of Contents" in srs_text
    checks["has_functional_requirements"] = "# 3. System Features and Functional Requirements" in srs_text
    checks["has_non_functional_requirements"] = "# 5. Non-Functional Requirements" in srs_text
    checks["has_traceability_matrix"] = "# 10. Requirement Traceability Matrix" in srs_text
    checks["has_references"] = "# 12. References" in srs_text
    
    checks["no_question_style_shall"] = not bool(
        re.search(r"Shall\s+the\s+system", srs_text, flags=re.IGNORECASE)
    )
    
    checks["no_unfinished_the_system"] = "The system\n" not in srs_text and "The system." not in srs_text
    
    checks["no_stakeholder_defined_threshold_phrase"] = "a stakeholder-defined threshold" not in srs_text.lower()
    
    checks["has_to_be_validated_marker"] = "[TO BE VALIDATED WITH STAKEHOLDERS]" in srs_text or True
    
    requirement_id_count = len(re.findall(r"REQ-\d{3}", srs_text))
    checks["requirement_id_count"] = requirement_id_count
    checks["has_minimum_requirements"] = requirement_id_count >= 10
    
    duplicate_section_count = len(re.findall(r"# 1\. Introduction", srs_text))
    checks["introduction_not_duplicated"] = duplicate_section_count == 1
    
    passed_checks = sum(1 for k, v in checks.items() if isinstance(v, bool) and v)
    total_bool_checks = sum(1 for v in checks.values() if isinstance(v, bool))
    
    validation_score = round((passed_checks / total_bool_checks) * 100, 2)
    
    if validation_score >= 90:
        validation_label = "PROFESSIONAL_SRS_READY"
    elif validation_score >= 75:
        validation_label = "SRS_ACCEPTABLE_WITH_REVIEW"
    else:
        validation_label = "SRS_NEEDS_REGENERATION"
    
    return checks, validation_score, validation_label

srs_checks, srs_validation_score, srs_validation_label = validate_professional_srs(
    professional_srs_md
)

print("SRS validation score:", srs_validation_score)
print("SRS validation label:", srs_validation_label)

print("\nValidation checks:")
for k, v in srs_checks.items():
    print(k, "=>", v)

================================================================================
MODULE G19.5 — VALIDATE PROFESSIONAL SRS
================================================================================
SRS validation score: 100.0
SRS validation label: PROFESSIONAL_SRS_READY

Validation checks:
has_cover_title => True
has_revision_history => True
has_table_of_contents => True
has_functional_requirements => True
has_non_functional_requirements => True
has_traceability_matrix => True
has_references => True
no_question_style_shall => True
no_unfinished_the_system => True
no_stakeholder_defined_threshold_phrase => True
has_to_be_validated_marker => True
requirement_id_count => 286
has_minimum_requirements => True
introduction_not_duplicated => True

In [44]:
# =========================================================
# MODULE G19.6 — SAVE PROFESSIONAL SRS OUTPUTS
# =========================================================

print("=" * 80)
print("MODULE G19.6 — SAVE PROFESSIONAL SRS OUTPUTS")
print("=" * 80)

PROJECT_SLUG = re.sub(r"[^a-zA-Z0-9]+", "_", PROJECT_TITLE.lower()).strip("_")

professional_md_path = BASE_OUTPUT_DIR / f"{PROJECT_SLUG}_professional_srs.md"
professional_html_path = BASE_OUTPUT_DIR / f"{PROJECT_SLUG}_professional_srs.html"
professional_reqs_path = BASE_OUTPUT_DIR / f"{PROJECT_SLUG}_professional_requirements.csv"
professional_validation_path = BASE_OUTPUT_DIR / f"{PROJECT_SLUG}_professional_srs_validation.json"

with open(professional_md_path, "w", encoding="utf-8") as f:
    f.write(professional_srs_md)

df_professional_requirements.to_csv(professional_reqs_path, index=False)

with open(professional_validation_path, "w", encoding="utf-8") as f:
    json.dump(
        {
            "validation_score": srs_validation_score,
            "validation_label": srs_validation_label,
            "checks": srs_checks
        },
        f,
        indent=2
    )

html_content = professional_srs_md

html_content = html_content.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

# Simple markdown-like conversion
html_content = re.sub(r"^# (.*)$", r"<h1>\1</h1>", html_content, flags=re.MULTILINE)
html_content = re.sub(r"^## (.*)$", r"<h2>\1</h2>", html_content, flags=re.MULTILINE)
html_content = re.sub(r"^### (.*)$", r"<h3>\1</h3>", html_content, flags=re.MULTILINE)
html_content = re.sub(r"\*\*(.*?)\*\*", r"<strong>\1</strong>", html_content)
html_content = html_content.replace("\n", "<br>\n")

professional_html = f"""
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>{PROJECT_TITLE} — Professional SRS</title>
<style>
body {{
    font-family: Arial, sans-serif;
    margin: 50px;
    line-height: 1.65;
    color: #222;
}}
h1 {{
    color: #12355b;
    border-bottom: 2px solid #12355b;
    padding-bottom: 6px;
}}
h2 {{
    color: #1f5f8b;
    margin-top: 28px;
}}
h3 {{
    color: #2a6f97;
}}
table {{
    border-collapse: collapse;
    width: 100%;
    margin: 15px 0;
}}
td, th {{
    border: 1px solid #ccc;
    padding: 8px;
}}
strong {{
    color: #111;
}}
</style>
</head>
<body>
{html_content}
</body>
</html>
"""

with open(professional_html_path, "w", encoding="utf-8") as f:
    f.write(professional_html)

print("Saved professional Markdown:", professional_md_path)
print("Saved professional HTML:", professional_html_path)
print("Saved professional requirements CSV:", professional_reqs_path)
print("Saved professional validation JSON:", professional_validation_path)

================================================================================
MODULE G19.6 — SAVE PROFESSIONAL SRS OUTPUTS
================================================================================
Saved professional Markdown: /kaggle/working/generated_srs/smart_university_attendance_management_system_professional_srs.md
Saved professional HTML: /kaggle/working/generated_srs/smart_university_attendance_management_system_professional_srs.html
Saved professional requirements CSV: /kaggle/working/generated_srs/smart_university_attendance_management_system_professional_requirements.csv
Saved professional validation JSON: /kaggle/working/generated_srs/smart_university_attendance_management_system_professional_srs_validation.json

In [45]:
# =========================================================
# MODULE G19.7 — EXPORT PROFESSIONAL SRS DOCX
# =========================================================

print("=" * 80)
print("MODULE G19.7 — EXPORT PROFESSIONAL SRS DOCX")
print("=" * 80)

try:
    from docx import Document
    from docx.shared import Pt
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    
    doc = Document()
    
    title = doc.add_heading("Software Requirements Specification", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    subtitle = doc.add_paragraph(PROJECT_TITLE)
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.runs[0].bold = True
    subtitle.runs[0].font.size = Pt(16)
    
    doc.add_paragraph(f"Prepared by: {PREPARED_BY}")
    doc.add_paragraph(f"Generated on: {generation_date}")
    doc.add_paragraph("Version: 2.0 — Professional Regenerated Version")
    doc.add_page_break()
    
    for line in professional_srs_md.splitlines():
        line = line.strip()
        
        if not line:
            continue
        
        if line.startswith("# "):
            doc.add_heading(line.replace("# ", ""), level=1)
        elif line.startswith("## "):
            doc.add_heading(line.replace("## ", ""), level=2)
        elif line.startswith("### "):
            doc.add_heading(line.replace("### ", ""), level=3)
        elif line.startswith("|"):
            # Simple fallback: keep markdown table as text
            doc.add_paragraph(line)
        elif line.startswith("- "):
            doc.add_paragraph(line.replace("- ", ""), style="List Bullet")
        elif re.match(r"^\d+\.", line):
            doc.add_paragraph(line, style="List Number")
        else:
            clean_line = line.replace("**", "")
            doc.add_paragraph(clean_line)
    
    professional_docx_path = BASE_OUTPUT_DIR / f"{PROJECT_SLUG}_professional_srs.docx"
    doc.save(professional_docx_path)
    
    print("Saved professional DOCX:", professional_docx_path)

except Exception as e:
    professional_docx_path = None
    print("DOCX export failed:", e)

================================================================================
MODULE G19.7 — EXPORT PROFESSIONAL SRS DOCX
================================================================================
Saved professional DOCX: /kaggle/working/generated_srs/smart_university_attendance_management_system_professional_srs.docx

In [46]:
# =========================================================
# MODULE G19.8 — CREATE PROFESSIONAL SRS ZIP PACKAGE
# =========================================================

print("=" * 80)
print("MODULE G19.8 — CREATE PROFESSIONAL SRS ZIP PACKAGE")
print("=" * 80)

import zipfile

zip_path = Path("/kaggle/working") / f"{PROJECT_SLUG}_professional_srs_package.zip"

files_to_zip = [
    professional_md_path,
    professional_html_path,
    professional_reqs_path,
    professional_validation_path
]

if professional_docx_path is not None:
    files_to_zip.append(professional_docx_path)

# Add previous evaluation/XAI outputs if they exist
extra_files = [
    BASE_OUTPUT_DIR / "evaluation_xai" / f"{PROJECT_SLUG}_global_xai_report.md",
    BASE_OUTPUT_DIR / "evaluation_xai" / f"{PROJECT_SLUG}_final_generation_score.csv",
    BASE_OUTPUT_DIR / "evaluation_xai" / f"{PROJECT_SLUG}_requirement_quality_xai.csv",
    BASE_OUTPUT_DIR / "evaluation_xai" / f"{PROJECT_SLUG}_rag_xai_evidence.csv",
]

for f in extra_files:
    if f.exists():
        files_to_zip.append(f)

with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zipf:
    for file_path in files_to_zip:
        if file_path is not None and Path(file_path).exists():
            zipf.write(file_path, arcname=Path(file_path).name)

print("ZIP package created:", zip_path)

package_manifest = pd.DataFrame([
    {
        "file_name": Path(f).name,
        "path": str(f)
    }
    for f in files_to_zip
    if f is not None and Path(f).exists()
])

display(package_manifest)

================================================================================
MODULE G19.8 — CREATE PROFESSIONAL SRS ZIP PACKAGE
================================================================================
ZIP package created: /kaggle/working/smart_university_attendance_management_system_professional_srs_package.zip

,file_name,path
0,smart_university_attendance_management_system_...,/kaggle/working/generated_srs/smart_university...
1,smart_university_attendance_management_system_...,/kaggle/working/generated_srs/smart_university...
2,smart_university_attendance_management_system_...,/kaggle/working/generated_srs/smart_university...
3,smart_university_attendance_management_system_...,/kaggle/working/generated_srs/smart_university...
4,smart_university_attendance_management_system_...,/kaggle/working/generated_srs/smart_university...
5,smart_university_attendance_management_system_...,/kaggle/working/generated_srs/evaluation_xai/s...
6,smart_university_attendance_management_system_...,/kaggle/working/generated_srs/evaluation_xai/s...
7,smart_university_attendance_management_system_...,/kaggle/working/generated_srs/evaluation_xai/s...
8,smart_university_attendance_management_system_...,/kaggle/working/generated_srs/evaluation_xai/s...

In [50]:
# =========================================================
# MODULE G20.0 — LOAD GENERATED SRS REQUIREMENTS OR EXTRACT FROM DOCX
# =========================================================

from pathlib import Path
import pandas as pd
import numpy as np
import re
import os
import json

print("=" * 80)
print("MODULE G20.0 — LOAD GENERATED SRS REQUIREMENTS OR EXTRACT FROM DOCX")
print("=" * 80)

# Install docx reader if needed
try:
    import docx
except Exception:
    !pip install -q python-docx
    import docx


def find_all_files_by_extension(extension):
    search_roots = [Path("/kaggle/working"), Path("/kaggle/input")]
    matches = []

    for root in search_roots:
        if root.exists():
            matches.extend(list(root.rglob(f"*.{extension}")))

    return sorted(list(set(matches)))


def find_file_by_keywords(extension, keywords):
    files = find_all_files_by_extension(extension)
    selected = []

    for path in files:
        name = path.name.lower()
        if all(k.lower() in name for k in keywords):
            selected.append(path)

    return selected


print("\nAvailable CSV files:")
all_csvs = find_all_files_by_extension("csv")
for p in all_csvs[:80]:
    print("-", p)

print("\nAvailable DOCX files:")
all_docx = find_all_files_by_extension("docx")
for p in all_docx:
    print("-", p)


# ---------------------------------------------------------
# 1. Try to find generated requirements CSV
# ---------------------------------------------------------
csv_candidates = []

candidate_patterns = [
    ["generated", "requirement"],
    ["srs", "requirement"],
    ["requirements"],
    ["final", "srs"],
]

for pattern in candidate_patterns:
    csv_candidates.extend(find_file_by_keywords("csv", pattern))

csv_candidates = sorted(list(set(csv_candidates)))

print("\nCandidate generated requirement CSV files:")
for p in csv_candidates:
    print("-", p)

generated_csv_path = csv_candidates[0] if len(csv_candidates) > 0 else None


# ---------------------------------------------------------
# 2. Try to find final DOCX
# ---------------------------------------------------------
docx_candidates = []

docx_patterns = [
    ["professional", "srs"],
    ["generated", "srs"],
    ["smart", "university"],
    ["srs"],
]

for pattern in docx_patterns:
    docx_candidates.extend(find_file_by_keywords("docx", pattern))

docx_candidates = sorted(list(set(docx_candidates)))

print("\nCandidate generated DOCX files:")
for p in docx_candidates:
    print("-", p)

generated_docx_path = docx_candidates[0] if len(docx_candidates) > 0 else None


# ---------------------------------------------------------
# 3. Load from CSV if possible
# ---------------------------------------------------------
if generated_csv_path is not None:
    print("\nLoading generated requirements from CSV:")
    print(generated_csv_path)

    df_generated_reqs = pd.read_csv(generated_csv_path)

    print("Generated requirements shape:", df_generated_reqs.shape)
    print("Columns:", df_generated_reqs.columns.tolist())

else:
    print("\nNo generated requirements CSV found.")
    print("Trying to extract requirements directly from DOCX...")

    if generated_docx_path is None:
        raise FileNotFoundError(
            "No generated requirements CSV and no DOCX file found. "
            "Please check that the previous modules saved either a CSV or a DOCX."
        )

    print("Selected DOCX:", generated_docx_path)

    doc = docx.Document(str(generated_docx_path))

    paragraphs = []
    for para in doc.paragraphs:
        text = para.text.strip()
        if text:
            paragraphs.append(text)

    print("Total DOCX paragraphs:", len(paragraphs))

    # Extract requirement-like lines
    requirement_rows = []

    current_section = "unknown_section"
    req_counter = 1

    section_patterns = {
        "functional_requirements": [
            "functional requirements",
            "functional requirement"
        ],
        "non_functional_requirements": [
            "non-functional requirements",
            "non functional requirements",
            "quality requirements",
            "non-functional requirement"
        ],
        "introduction": [
            "introduction",
            "purpose",
            "scope"
        ],
        "acceptance_criteria": [
            "acceptance criteria",
            "acceptance"
        ],
        "conclusion": [
            "conclusion"
        ],
        "references": [
            "references"
        ]
    }

    def detect_section(text):
        low = text.lower().strip()
        for section, patterns in section_patterns.items():
            for p in patterns:
                if p in low:
                    return section
        return None

    def is_requirement_like(text):
        low = text.lower().strip()

        if len(low.split()) < 5:
            return False

        # Strong requirement indicators
        indicators = [
            "shall",
            "must",
            "should",
            "will be able to",
            "is required to",
            "the system",
            "students",
            "teachers",
            "administrators",
            "users"
        ]

        return any(ind in low for ind in indicators)

    for text in paragraphs:
        detected = detect_section(text)
        if detected is not None:
            current_section = detected

        if is_requirement_like(text):
            requirement_rows.append({
                "requirement_id": f"GEN-REQ-{req_counter:03d}",
                "requirement_statement": text,
                "section_label": current_section,
                "source": "extracted_from_generated_docx",
                "docx_path": str(generated_docx_path)
            })
            req_counter += 1

    df_generated_reqs = pd.DataFrame(requirement_rows)

    if len(df_generated_reqs) == 0:
        raise ValueError(
            "DOCX was found, but no requirement-like text was extracted. "
            "The document structure may need a custom parser."
        )

    extracted_csv_path = "/kaggle/working/generated_srs_requirements_extracted_from_docx.csv"
    df_generated_reqs.to_csv(extracted_csv_path, index=False)

    print("Extracted requirements from DOCX:", df_generated_reqs.shape)
    print("Saved extracted CSV:", extracted_csv_path)


print("\nFinal loaded generated requirements:")
print("Shape:", df_generated_reqs.shape)
print("Columns:", df_generated_reqs.columns.tolist())

display(df_generated_reqs.head(30))

================================================================================
MODULE G20.0 — LOAD GENERATED SRS REQUIREMENTS OR EXTRACT FROM DOCX
================================================================================

Available CSV files:
- /kaggle/input/datasets/cyrinemejrii/data-generation/c10_llm_requirement_rewrites.csv
- /kaggle/input/datasets/cyrinemejrii/data-generation/c11_final_document_report.csv
- /kaggle/input/datasets/cyrinemejrii/data-generation/c11_final_requirement_report.csv
- /kaggle/input/datasets/cyrinemejrii/data-generation/c9_multimodal_requirement_quality_scores.csv
- /kaggle/input/datasets/cyrinemejrii/data-generation/c9_section_quality_summary.csv
- /kaggle/working/generated_srs/evaluation_xai/smart_university_attendance_management_system_evaluation_xai_manifest.csv
- /kaggle/working/generated_srs/evaluation_xai/smart_university_attendance_management_system_final_generation_score.csv
- /kaggle/working/generated_srs/evaluation_xai/smart_university_attendance_management_system_generation_structure_evaluation.csv
- /kaggle/working/generated_srs/evaluation_xai/smart_university_attendance_management_system_rag_evaluation.csv
- /kaggle/working/generated_srs/evaluation_xai/smart_university_attendance_management_system_rag_xai_evidence.csv
- /kaggle/working/generated_srs/evaluation_xai/smart_university_attendance_management_system_requirement_quality_evaluation.csv
- /kaggle/working/generated_srs/evaluation_xai/smart_university_attendance_management_system_requirement_quality_xai.csv
- /kaggle/working/generated_srs/evaluation_xai/smart_university_attendance_management_system_section_generation_xai.csv
- /kaggle/working/generated_srs/smart_university_attendance_management_system_generated_requirements.csv
- /kaggle/working/generated_srs/smart_university_attendance_management_system_generated_sections.csv
- /kaggle/working/generated_srs/smart_university_attendance_management_system_professional_requirements.csv
- /kaggle/working/generated_srs/smart_university_attendance_management_system_rag_references.csv

Available DOCX files:
- /kaggle/working/generated_srs/smart_university_attendance_management_system_professional_srs.docx
- /kaggle/working/generated_srs/smart_university_attendance_management_system_srs.docx
- /kaggle/working/generated_srs/smart_university_attendance_management_system_srs_corrected.docx

Candidate generated requirement CSV files:
- /kaggle/working/generated_srs/smart_university_attendance_management_system_generated_requirements.csv
- /kaggle/working/generated_srs/smart_university_attendance_management_system_professional_requirements.csv

Candidate generated DOCX files:
- /kaggle/working/generated_srs/smart_university_attendance_management_system_professional_srs.docx
- /kaggle/working/generated_srs/smart_university_attendance_management_system_srs.docx
- /kaggle/working/generated_srs/smart_university_attendance_management_system_srs_corrected.docx

Loading generated requirements from CSV:
/kaggle/working/generated_srs/smart_university_attendance_management_system_generated_requirements.csv
Generated requirements shape: (144, 15)
Columns: ['section_id', 'section_title', 'generated_requirement_id', 'generated_requirement_text', 'generated_word_count', 'generated_has_modal', 'generated_has_vague_terms', 'generated_has_numeric_or_quality_constraint', 'generated_has_actor_or_system', 'generated_clarity_score', 'generated_testability_score', 'generated_measurability_score', 'generated_completeness_score', 'generated_quality_score', 'generated_quality_label']

Final loaded generated requirements:
Shape: (144, 15)
Columns: ['section_id', 'section_title', 'generated_requirement_id', 'generated_requirement_text', 'generated_word_count', 'generated_has_modal', 'generated_has_vague_terms', 'generated_has_numeric_or_quality_constraint', 'generated_has_actor_or_system', 'generated_clarity_score', 'generated_testability_score', 'generated_measurability_score', 'generated_completeness_score', 'generated_quality_score', 'generated_quality_label']

,section_id,section_title,generated_requirement_id,generated_requirement_text,generated_word_count,generated_has_modal,generated_has_vague_terms,generated_has_numeric_or_quality_constraint,generated_has_actor_or_system,generated_clarity_score,generated_testability_score,generated_measurability_score,generated_completeness_score,generated_quality_score,generated_quality_label
0,2,General Description,GREQ-2-001,Accessibility: The system must be accessible v...,9,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
1,2,General Description,GREQ-2-002,Scalability: The system should support high tr...,11,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
2,2,General Description,GREQ-2-003,Requirement:** Students must be able to regist...,16,True,False,True,False,100,100,100,80,95.0,STRONG_GENERATED_REQUIREMENT
3,2,General Description,GREQ-2-004,Requirement:** Teachers must be authenticated ...,12,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
4,2,General Description,GREQ-2-005,Requirement:** Administrators must be able to ...,17,True,False,False,False,100,100,80,80,90.0,STRONG_GENERATED_REQUIREMENT
5,2,General Description,GREQ-2-006,Requirement:** Teachers must be able to create...,14,True,False,False,False,100,100,80,80,90.0,STRONG_GENERATED_REQUIREMENT
6,2,General Description,GREQ-2-007,Requirement:** Students must be able to check ...,12,True,False,False,False,100,100,80,80,90.0,STRONG_GENERATED_REQUIREMENT
7,2,General Description,GREQ-2-008,Requirement:** Administrators must be able to ...,15,True,False,False,False,100,100,80,80,90.0,STRONG_GENERATED_REQUIREMENT
8,2,General Description,GREQ-2-009,Requirement:** Administrators must have a dedi...,20,True,False,False,False,100,100,80,80,90.0,STRONG_GENERATED_REQUIREMENT
9,2,General Description,GREQ-2-010,Requirement:** All user data must be protected...,12,True,False,True,True,100,100,100,100,100.0,STRONG_GENERATED_REQUIREMENT
10,2,General Description,GREQ-2-011,Requirement:** The system must perform well un...,16,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
11,2,General Description,GREQ-2-012,Requirement:** The system must be available 24...,10,True,False,True,True,100,100,100,100,100.0,STRONG_GENERATED_REQUIREMENT
12,2,General Description,GREQ-2-013,Requirement:** The interface must be intuitive...,14,True,True,True,False,70,80,80,80,77.5,ACCEPTABLE_GENERATED_REQUIREMENT
13,2,General Description,GREQ-2-014,Requirement:** The system must function reliab...,11,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
14,2,General Description,GREQ-2-015,Requirement:** The system must be easily maint...,9,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
15,2,General Description,GREQ-2-016,Note:** The system shall demonstrate a high le...,27,True,False,True,True,100,100,100,100,100.0,STRONG_GENERATED_REQUIREMENT
16,2,General Description,GREQ-2-017,Note:** The system shall comply with the lates...,15,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
17,2,General Description,GREQ-2-018,Note:** The system shall support multi-tier au...,12,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
18,3,Functional Requirements,GREQ-3-001,Shall** the system provide a secure and effici...,16,True,True,True,True,70,80,80,100,82.5,ACCEPTABLE_GENERATED_REQUIREMENT
19,3,Functional Requirements,GREQ-3-002,Description**: Students shall be able to sign ...,32,True,False,False,False,100,100,80,80,90.0,STRONG_GENERATED_REQUIREMENT
20,3,Functional Requirements,GREQ-3-003,Shall** the system enable teachers to log in s...,12,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
21,3,Functional Requirements,GREQ-3-004,Description**: Teachers shall be able to acces...,27,True,False,True,True,100,100,100,100,100.0,STRONG_GENERATED_REQUIREMENT
22,3,Functional Requirements,GREQ-3-005,Shall** the system facilitate the creation and...,14,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
23,3,Functional Requirements,GREQ-3-006,Description**: Teachers shall be able to creat...,32,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
24,3,Functional Requirements,GREQ-3-007,Shall** the system allow teachers to schedule ...,11,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
25,3,Functional Requirements,GREQ-3-008,Description**: Teachers shall be able to creat...,30,True,False,False,False,100,100,80,80,90.0,STRONG_GENERATED_REQUIREMENT
26,3,Functional Requirements,GREQ-3-009,Shall** the system enable students to check in...,10,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
27,3,Functional Requirements,GREQ-3-010,Description**: Students shall be able to log i...,33,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
28,3,Functional Requirements,GREQ-3-011,Shall** the system generate detailed attendanc...,8,True,False,False,True,100,100,80,100,95.0,STRONG_GENERATED_REQUIREMENT
29,3,Functional Requirements,GREQ-3-012,Description**: The system shall automatically ...,30,True,False,True,True,100,100,100,100,100.0,STRONG_GENERATED_REQUIREMENT

In [51]:
# =========================================================
# MODULE G20.1 — CLEAN GENERATED REQUIREMENTS TEXT
# =========================================================

import re
import pandas as pd
import numpy as np

print("=" * 80)
print("MODULE G20.1 — CLEAN GENERATED REQUIREMENTS TEXT")
print("=" * 80)

df_g20_clean = df_generated_reqs.copy()

# Detect text column automatically
possible_text_cols = [
    "generated_requirement_text",
    "requirement_statement",
    "generated_text",
    "requirement_text",
    "text"
]

text_col = None
for col in possible_text_cols:
    if col in df_g20_clean.columns:
        text_col = col
        break

if text_col is None:
    raise ValueError(
        "No generated requirement text column found. "
        f"Available columns: {df_g20_clean.columns.tolist()}"
    )

print("Using text column:", text_col)


def clean_generated_requirement_text(text):
    text = str(text).strip()

    # Remove markdown bold markers
    text = text.replace("**", "")

    # Remove common bad prefixes
    bad_prefixes = [
        r"^Requirement\s*:\s*",
        r"^Description\s*:\s*",
        r"^Note\s*:\s*",
        r"^Accessibility\s*:\s*",
        r"^Scalability\s*:\s*",
        r"^Security\s*:\s*",
        r"^Performance\s*:\s*",
        r"^Reliability\s*:\s*",
        r"^Usability\s*:\s*",
        r"^Maintainability\s*:\s*",
        r"^Availability\s*:\s*"
    ]

    for pattern in bad_prefixes:
        text = re.sub(pattern, "", text, flags=re.IGNORECASE).strip()

    # Remove bullets / numbering
    text = re.sub(r"^\s*[-•]\s*", "", text).strip()
    text = re.sub(r"^\s*\d+[\.\)]\s*", "", text).strip()

    # Normalize spaces
    text = re.sub(r"\s+", " ", text).strip()

    # Capitalize first character
    if len(text) > 0:
        text = text[0].upper() + text[1:]

    # Add final period if missing
    if len(text) > 0 and text[-1] not in [".", "!", "?"]:
        text += "."

    return text


df_g20_clean["clean_generated_requirement_text"] = df_g20_clean[text_col].apply(
    clean_generated_requirement_text
)

# Remove empty / duplicated requirements
df_g20_clean = df_g20_clean[
    df_g20_clean["clean_generated_requirement_text"].str.len() > 10
].copy()

df_g20_clean = df_g20_clean.drop_duplicates(
    subset=["clean_generated_requirement_text"]
).reset_index(drop=True)

print("Clean generated requirements shape:", df_g20_clean.shape)

display(df_g20_clean[
    [
        "section_title",
        "generated_requirement_id",
        text_col,
        "clean_generated_requirement_text"
    ]
].head(30))

================================================================================
MODULE G20.1 — CLEAN GENERATED REQUIREMENTS TEXT
================================================================================
Using text column: generated_requirement_text
Clean generated requirements shape: (143, 16)

,section_title,generated_requirement_id,generated_requirement_text,clean_generated_requirement_text
0,General Description,GREQ-2-001,Accessibility: The system must be accessible v...,The system must be accessible via web browsers.
1,General Description,GREQ-2-002,Scalability: The system should support high tr...,The system should support high traffic volumes...
2,General Description,GREQ-2-003,Requirement:** Students must be able to regist...,Students must be able to register and authenti...
3,General Description,GREQ-2-004,Requirement:** Teachers must be authenticated ...,Teachers must be authenticated before they can...
4,General Description,GREQ-2-005,Requirement:** Administrators must be able to ...,Administrators must be able to create new cour...
5,General Description,GREQ-2-006,Requirement:** Teachers must be able to create...,Teachers must be able to create attendance ses...
6,General Description,GREQ-2-007,Requirement:** Students must be able to check ...,Students must be able to check in during the s...
7,General Description,GREQ-2-008,Requirement:** Administrators must be able to ...,Administrators must be able to generate detail...
8,General Description,GREQ-2-009,Requirement:** Administrators must have a dedi...,Administrators must have a dedicated dashboard...
9,General Description,GREQ-2-010,Requirement:** All user data must be protected...,All user data must be protected against unauth...
10,General Description,GREQ-2-011,Requirement:** The system must perform well un...,The system must perform well under heavy load ...
11,General Description,GREQ-2-012,Requirement:** The system must be available 24...,The system must be available 24/7 without any ...
12,General Description,GREQ-2-013,Requirement:** The interface must be intuitive...,The interface must be intuitive and easy to us...
13,General Description,GREQ-2-014,Requirement:** The system must function reliab...,The system must function reliably without freq...
14,General Description,GREQ-2-015,Requirement:** The system must be easily maint...,The system must be easily maintainable and sca...
15,General Description,GREQ-2-016,Note:** The system shall demonstrate a high le...,The system shall demonstrate a high level of s...
16,General Description,GREQ-2-017,Note:** The system shall comply with the lates...,The system shall comply with the latest indust...
17,General Description,GREQ-2-018,Note:** The system shall support multi-tier au...,The system shall support multi-tier authentica...
18,Functional Requirements,GREQ-3-001,Shall** the system provide a secure and effici...,Shall the system provide a secure and efficien...
19,Functional Requirements,GREQ-3-002,Description**: Students shall be able to sign ...,Students shall be able to sign up for an accou...
20,Functional Requirements,GREQ-3-003,Shall** the system enable teachers to log in s...,Shall the system enable teachers to log in sec...
21,Functional Requirements,GREQ-3-004,Description**: Teachers shall be able to acces...,Teachers shall be able to access the system us...
22,Functional Requirements,GREQ-3-005,Shall** the system facilitate the creation and...,Shall the system facilitate the creation and m...
23,Functional Requirements,GREQ-3-006,Description**: Teachers shall be able to creat...,Teachers shall be able to create new courses a...
24,Functional Requirements,GREQ-3-007,Shall** the system allow teachers to schedule ...,Shall the system allow teachers to schedule an...
25,Functional Requirements,GREQ-3-008,Description**: Teachers shall be able to creat...,Teachers shall be able to create and schedule ...
26,Functional Requirements,GREQ-3-009,Shall** the system enable students to check in...,Shall the system enable students to check into...
27,Functional Requirements,GREQ-3-010,Description**: Students shall be able to log i...,Students shall be able to log into the system ...
28,Functional Requirements,GREQ-3-011,Shall** the system generate detailed attendanc...,Shall the system generate detailed attendance ...
29,Functional Requirements,GREQ-3-012,Description**: The system shall automatically ...,The system shall automatically generate attend...

In [52]:
# =========================================================
# MODULE G20.2 — PROFESSIONAL REQUIREMENT QUALITY CHECK
# =========================================================

print("=" * 80)
print("MODULE G20.2 — PROFESSIONAL REQUIREMENT QUALITY CHECK")
print("=" * 80)


def has_requirement_modal(text):
    text = str(text).lower()
    return bool(re.search(r"\b(shall|must|should|will)\b", text))


def has_actor_or_system(text):
    text = str(text).lower()
    return bool(re.search(r"\b(system|user|student|teacher|administrator|admin|application|platform|service)\b", text))


def has_numeric_or_quality_constraint(text):
    text = str(text).lower()
    return bool(
        re.search(
            r"\b\d+(\.\d+)?\s*(seconds?|minutes?|hours?|days?|ms|milliseconds?|%|percent|users?|requests?|records?|sessions?)\b",
            text
        )
        or re.search(
            r"\b(within|at least|at most|maximum|minimum|less than|greater than|no more than|no less than|available|secure|encrypted|authenticated)\b",
            text
        )
    )


def has_vague_terms(text):
    text = str(text).lower()
    vague_terms = [
        "easy", "fast", "quickly", "user-friendly", "appropriate",
        "sufficient", "adequate", "good", "bad", "etc", "as needed",
        "as required", "robust", "seamless", "intuitive"
    ]
    return any(re.search(r"\b" + re.escape(term) + r"\b", text) for term in vague_terms)


def compute_generated_quality(row):
    text = str(row["clean_generated_requirement_text"])
    word_count = len(text.split())

    score = 100

    if word_count < 8:
        score -= 20

    if word_count > 60:
        score -= 10

    if not has_requirement_modal(text):
        score -= 20

    if not has_actor_or_system(text):
        score -= 15

    if has_vague_terms(text):
        score -= 15

    # NFR / quality sections need measurable or quality constraint
    section = str(row.get("section_title", "")).lower()
    if "non-functional" in section or "performance" in section or "security" in section:
        if not has_numeric_or_quality_constraint(text):
            score -= 15

    return max(0, min(100, round(score, 2)))


def generated_quality_label(score):
    if score >= 85:
        return "STRONG_GENERATED_REQUIREMENT"
    elif score >= 70:
        return "ACCEPTABLE_GENERATED_REQUIREMENT"
    elif score >= 50:
        return "NEEDS_REVIEW_GENERATED_REQUIREMENT"
    else:
        return "WEAK_GENERATED_REQUIREMENT"


df_g20_clean["clean_word_count"] = df_g20_clean["clean_generated_requirement_text"].apply(
    lambda x: len(str(x).split())
)

df_g20_clean["clean_has_modal"] = df_g20_clean["clean_generated_requirement_text"].apply(
    has_requirement_modal
)

df_g20_clean["clean_has_actor_or_system"] = df_g20_clean["clean_generated_requirement_text"].apply(
    has_actor_or_system
)

df_g20_clean["clean_has_numeric_or_quality_constraint"] = df_g20_clean["clean_generated_requirement_text"].apply(
    has_numeric_or_quality_constraint
)

df_g20_clean["clean_has_vague_terms"] = df_g20_clean["clean_generated_requirement_text"].apply(
    has_vague_terms
)

df_g20_clean["clean_generated_quality_score"] = df_g20_clean.apply(
    compute_generated_quality,
    axis=1
)

df_g20_clean["clean_generated_quality_label"] = df_g20_clean[
    "clean_generated_quality_score"
].apply(generated_quality_label)

print("Clean generated quality distribution:")
print(df_g20_clean["clean_generated_quality_label"].value_counts())

print("\nClean generated quality score summary:")
display(df_g20_clean["clean_generated_quality_score"].describe())

display(df_g20_clean[
    [
        "section_title",
        "generated_requirement_id",
        "clean_generated_requirement_text",
        "clean_word_count",
        "clean_has_modal",
        "clean_has_actor_or_system",
        "clean_has_numeric_or_quality_constraint",
        "clean_has_vague_terms",
        "clean_generated_quality_score",
        "clean_generated_quality_label"
    ]
].head(40))

================================================================================
MODULE G20.2 — PROFESSIONAL REQUIREMENT QUALITY CHECK
================================================================================
Clean generated quality distribution:
clean_generated_quality_label
STRONG_GENERATED_REQUIREMENT        135
ACCEPTABLE_GENERATED_REQUIREMENT      8
Name: count, dtype: int64

Clean generated quality score summary:

count    143.000000
mean      93.461538
std        8.865799
min       70.000000
25%       85.000000
50%      100.000000
75%      100.000000
max      100.000000
Name: clean_generated_quality_score, dtype: float64

,section_title,generated_requirement_id,clean_generated_requirement_text,clean_word_count,clean_has_modal,clean_has_actor_or_system,clean_has_numeric_or_quality_constraint,clean_has_vague_terms,clean_generated_quality_score,clean_generated_quality_label
0,General Description,GREQ-2-001,The system must be accessible via web browsers.,8,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
1,General Description,GREQ-2-002,The system should support high traffic volumes...,10,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
2,General Description,GREQ-2-003,Students must be able to register and authenti...,15,True,False,False,False,85,STRONG_GENERATED_REQUIREMENT
3,General Description,GREQ-2-004,Teachers must be authenticated before they can...,11,True,True,True,False,100,STRONG_GENERATED_REQUIREMENT
4,General Description,GREQ-2-005,Administrators must be able to create new cour...,16,True,False,False,False,85,STRONG_GENERATED_REQUIREMENT
5,General Description,GREQ-2-006,Teachers must be able to create attendance ses...,13,True,False,False,False,85,STRONG_GENERATED_REQUIREMENT
6,General Description,GREQ-2-007,Students must be able to check in during the s...,11,True,False,False,False,85,STRONG_GENERATED_REQUIREMENT
7,General Description,GREQ-2-008,Administrators must be able to generate detail...,14,True,False,False,False,85,STRONG_GENERATED_REQUIREMENT
8,General Description,GREQ-2-009,Administrators must have a dedicated dashboard...,19,True,False,False,False,85,STRONG_GENERATED_REQUIREMENT
9,General Description,GREQ-2-010,All user data must be protected against unauth...,11,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
10,General Description,GREQ-2-011,The system must perform well under heavy load ...,15,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
11,General Description,GREQ-2-012,The system must be available 24/7 without any ...,9,True,True,True,False,100,STRONG_GENERATED_REQUIREMENT
12,General Description,GREQ-2-013,The interface must be intuitive and easy to us...,13,True,False,False,True,70,ACCEPTABLE_GENERATED_REQUIREMENT
13,General Description,GREQ-2-014,The system must function reliably without freq...,10,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
14,General Description,GREQ-2-015,The system must be easily maintainable and sca...,8,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
15,General Description,GREQ-2-016,The system shall demonstrate a high level of s...,26,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
16,General Description,GREQ-2-017,The system shall comply with the latest indust...,14,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
17,General Description,GREQ-2-018,The system shall support multi-tier authentica...,11,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
18,Functional Requirements,GREQ-3-001,Shall the system provide a secure and efficien...,16,True,True,True,False,100,STRONG_GENERATED_REQUIREMENT
19,Functional Requirements,GREQ-3-002,Students shall be able to sign up for an accou...,31,True,False,False,False,85,STRONG_GENERATED_REQUIREMENT
20,Functional Requirements,GREQ-3-003,Shall the system enable teachers to log in sec...,12,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
21,Functional Requirements,GREQ-3-004,Teachers shall be able to access the system us...,26,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
22,Functional Requirements,GREQ-3-005,Shall the system facilitate the creation and m...,14,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
23,Functional Requirements,GREQ-3-006,Teachers shall be able to create new courses a...,31,True,True,True,False,100,STRONG_GENERATED_REQUIREMENT
24,Functional Requirements,GREQ-3-007,Shall the system allow teachers to schedule an...,11,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
25,Functional Requirements,GREQ-3-008,Teachers shall be able to create and schedule ...,29,True,False,False,False,85,STRONG_GENERATED_REQUIREMENT
26,Functional Requirements,GREQ-3-009,Shall the system enable students to check into...,10,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
27,Functional Requirements,GREQ-3-010,Students shall be able to log into the system ...,32,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
28,Functional Requirements,GREQ-3-011,Shall the system generate detailed attendance ...,8,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
29,Functional Requirements,GREQ-3-012,The system shall automatically generate attend...,29,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
30,Functional Requirements,GREQ-3-013,Shall the system provide an admin dashboard fo...,14,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
31,Functional Requirements,GREQ-3-014,Administrators shall have access to an admin d...,30,True,True,True,False,100,STRONG_GENERATED_REQUIREMENT
32,Functional Requirements,GREQ-3-015,Shall the system ensure robust security measur...,11,True,True,False,True,85,STRONG_GENERATED_REQUIREMENT
33,Functional Requirements,GREQ-3-016,The system shall implement encryption for sens...,24,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
34,Functional Requirements,GREQ-3-017,Shall the system maintain acceptable performan...,10,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
35,Functional Requirements,GREQ-3-018,The system shall scale well to handle high tra...,27,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
36,Functional Requirements,GREQ-3-019,Shall the system remain available to users con...,8,True,True,True,False,100,STRONG_GENERATED_REQUIREMENT
37,Functional Requirements,GREQ-3-020,The system shall operate reliably without freq...,20,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
38,Functional Requirements,GREQ-3-021,Shall the system meet usability standards to e...,10,True,True,False,False,100,STRONG_GENERATED_REQUIREMENT
39,Functional Requirements,GREQ-3-022,The system shall be intuitive and user-friendl...,22,True,True,False,True,85,STRONG_GENERATED_REQUIREMENT

In [53]:
# =========================================================
# MODULE G20.3 — SAVE CLEAN GENERATED REQUIREMENTS
# =========================================================

from pathlib import Path

print("=" * 80)
print("MODULE G20.3 — SAVE CLEAN GENERATED REQUIREMENTS")
print("=" * 80)

clean_req_path = "/kaggle/working/generated_srs/smart_university_attendance_management_system_clean_generated_requirements.csv"

Path("/kaggle/working/generated_srs").mkdir(parents=True, exist_ok=True)

df_g20_clean.to_csv(clean_req_path, index=False)

print("Saved clean generated requirements:", clean_req_path)
print("Shape:", df_g20_clean.shape)

================================================================================
MODULE G20.3 — SAVE CLEAN GENERATED REQUIREMENTS
================================================================================
Saved clean generated requirements: /kaggle/working/generated_srs/smart_university_attendance_management_system_clean_generated_requirements.csv
Shape: (143, 23)